### ISSUE TITLE
Postgres output: support condensed JSONDicts

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#1107]
The extra-field should be submitted as one field, not splitted in sub-fields:
```
postgresql-output: Bot has found a problem.
Traceback (most recent call last):
  File "/home/sebastianw/intelmq/intelmq/lib/bot.py", line 163, in start
    self.process()
  File "/home/sebastianw/intelmq/intelmq/bots/outputs/postgresql/output.py", line 63, in process
    self.cur.execute(query, values)
psycopg2.ProgrammingError: column "extra.hostname_examples" of relation "events" does not exist
LINE 1: ...uracy", "feed.name", "classification.identifier", "extra.hos...
                                                             ^
```

**Comment by wagner-certat** [comment]
Fixed in c57d03995317e5e82c0372e93a570d9808777f2a since 2017-10-17 (typo in commit message is the reason for the missing automatic close here)
