### ISSUE TITLE
intelmqctl bug - pid referenced before assignment

### ISSUE THREAD

**Issue by SYNchroACK** [certtools/intelmq#1159]
Inserting on purpose, bad code on a bot:
```
git diff intelmq/bots/parsers/spamhaus/parser_drop.py
diff --git a/intelmq/bots/parsers/spamhaus/parser_drop.py b/intelmq/bots/parsers/spamhaus/parser_drop.py
index a67260f..c68e3ef 100644
--- a/intelmq/bots/parsers/spamhaus/parser_drop.py
+++ b/intelmq/bots/parsers/spamhaus/parser_drop.py
@@ -1,7 +1,7 @@
 # -*- coding: utf-8 -*-
 """ Single IntelMQ parser for Spamhaus drop feeds """
 
-import dateutil.parser
+import dateutil.parsersss
 
 from intelmq.lib.bot import ParserBot
```

Run `intelmqctl`:
```
$ intelmqctl start spamhaus-drop-parser
intelmqctl: Starting spamhaus-drop-parser...
Traceback (most recent call last):
  File "/usr/local/bin/intelmqctl", line 9, in <module>
    load_entry_point('intelmq', 'console_scripts', 'intelmqctl')()
  File "/intelmq/intelmq/bin/intelmqctl.py", line 1100, in main
    return x.run()
  File "/intelmq/intelmq/bin/intelmqctl.py", line 562, in run
    retval, results = args.func(**args_dict)
  File "/intelmq/intelmq/bin/intelmqctl.py", line 575, in bot_start
    status = self.bot_process_manager.bot_start(bot_id, getstatus)
  File "/intelmq/intelmq/bin/intelmqctl.py", line 183, in bot_start
    return self.bot_status(bot_id, proc=proc)
  File "/intelmq/intelmq/bin/intelmqctl.py", line 261, in bot_status
    if pid:
UnboundLocalError: local variable 'pid' referenced before assignment
```

**Comment by hugeox** [comment]
I had the same issue.
I commented out line 261 and 262 in intelmqctl.py
Then I ran the problematic bot and it worked.
Then I uncommented the two lines. It still works.

**Comment by wagner-certat** [comment]
Thanks for the report, pushed a fix
