### ISSUE TITLE
sieve expert: incompatibility with textX 1.7.0

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#1246]
See the failing tests: https://travis-ci.org/certtools/intelmq/jobs/386565350#L842
```
Traceback (most recent call last):
  File "/home/travis/build/certtools/intelmq/intelmq/lib/bot.py", line 163, in start
    self.process()
  File "/home/travis/build/certtools/intelmq/intelmq/bots/experts/sieve/expert.py", line 86, in process
    procedure = self.process_rule(rule, event)
  File "/home/travis/build/certtools/intelmq/intelmq/bots/experts/sieve/expert.py", line 104, in process_rule
    self.logger.debug('Matched event based on rule at %s: %s.', self.get_linecol(rule.if_), event)
  File "/home/travis/build/certtools/intelmq/intelmq/bots/experts/sieve/expert.py", line 323, in get_linecol
    metamodel = textx.model.metamodel(model_obj)
AttributeError: module 'textx.model' has no attribute 'metamodel'
```

From the [changelog of textX](https://github.com/igordejanovic/textX/blob/master/CHANGELOG.md) I don't see where this model has gone to. Probably related to igordejanovic/textX#57

cc @antoinet 

I'll set textX < 1.7.0 for now

**Comment by antoinet** [comment]
Obviously an API change appeared with igordejanovic/textX@90667f29, so the solution would be simply to change `metamodel = textx.model.metamodel(...)` to `metamodel = textx.model.get_metamodel(...)`, but then I get another error related to textx:
```
  File "/private/tmp/venv/lib/python3.6/site-packages/arpeggio/__init__.py", line 1612, in pos_to_linecol
    if not self.line_ends:
AttributeError: 'TextXModelParser' object has no attribute 'line_ends'
```
Will investigate some more...

**Comment by wagner-certat** [comment]
I now opened igordejanovic/textX#89 upstream
