### ISSUE TITLE
Exception in shutdown methods are not catched

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#1266]
If some action in shutdown() of a bot raises an Exception this hides the actually error. For example:
```
Traceback (most recent call last):
  File "/home/sebastian/dev/intelmq/intelmq/lib/bot.py", line 86, in __init__
    self.init()
  File "/home/sebastian/dev/intelmq/intelmq/bots/outputs/file/output.py", line 18, in init
    self.file = io.open(self.parameters.file, mode='at', encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: '/opt/intelmq/var/lib/bots/file-output/{event[source.geolocation.cc]}/events.txt'
file-output: Error during shutdown of bot.
Traceback (most recent call last):
  File "/home/sebastian/dev/intelmq/intelmq/lib/bot.py", line 86, in __init__
    self.init()
  File "/home/sebastian/dev/intelmq/intelmq/bots/outputs/file/output.py", line 18, in init
    self.file = io.open(self.parameters.file, mode='at', encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: '/opt/intelmq/var/lib/bots/file-output/{event[source.geolocation.cc]}/events.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sebastian/dev/intelmq/intelmq/lib/bot.py", line 287, in stop
    self.shutdown()
  File "/home/sebastian/dev/intelmq/intelmq/bots/outputs/file/output.py", line 48, in shutdown
    self.file.close()
AttributeError: 'FileOutputBot' object has no attribute 'file'
```

Errors in shutdown() should be treated different.

**Comment by wagner-certat** [comment]
Ok, it's actually handled correctly.
