### ISSUE TITLE
AMQP Output: declares default exchange

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#1295]
The default exchange must not be declared AFAIK

**Comment by wagner-certat** [comment]
RabbitMQ error log:
```
{amqp_error,access_refused,"operation not permitted on the default exchange",
            'exchange.declare'}
```

**Comment by wagner-certat** [comment]
IntelMQ log:
```
2018-08-16 17:09:24,558 - amqp-output - ERROR - Bot initialization failed.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/intelmq/lib/bot.py", line 86, in __init__
    self.init()
  File "/usr/lib/python3/dist-packages/intelmq/bots/outputs/amqptopic/output.py", line 37, in init
    self.connect_server()
  File "/usr/lib/python3/dist-packages/intelmq/bots/outputs/amqptopic/output.py", line 58, in connect_server
    durable=self.durable)
  File "/usr/lib/python3/dist-packages/pika/adapters/blocking_connection.py", line 2207, in exchange_declare
    self._flush_output(declare_ok_result.is_ready)
  File "/usr/lib/python3/dist-packages/pika/adapters/blocking_connection.py", line 1181, in _flush_output
    raise exceptions.ChannelClosed(method.reply_code, method.reply_text)
pika.exceptions.ChannelClosed: (403, 'ACCESS_REFUSED - operation not permitted on the default exchange')
```
