### ISSUE TITLE
intelmqctl run: can't delete pid file

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#1303]
With any `intelmqctl run` call, this error is given:

```
^Cintelmq-dev-amqp-output: Received KeyboardInterrupt.
intelmq-dev-amqp-output: Bot stopped.
Bot exited with code 0.
Traceback (most recent call last):
  File "/usr/bin/intelmqctl", line 11, in <module>
    load_entry_point('intelmq==1.1.0', 'console_scripts', 'intelmqctl')()
  File "/usr/lib/python3/dist-packages/intelmq/bin/intelmqctl.py", line 1173, in main
    return x.run()
  File "/usr/lib/python3/dist-packages/intelmq/bin/intelmqctl.py", line 598, in run
    retval, results = args.func(**args_dict)
  File "/usr/lib/python3/dist-packages/intelmq/bin/intelmqctl.py", line 605, in bot_run
    return self.bot_process_manager.bot_run(**kwargs), None
  File "/usr/lib/python3/dist-packages/intelmq/bin/intelmqctl.py", line 161, in bot_run
    self.__remove_pidfile(bot_id)
  File "/usr/lib/python3/dist-packages/intelmq/bin/intelmqctl.py", line 295, in __remove_pidfile
    os.remove(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/var/run/intelmq/intelmq-dev-amqp-output.pid'
```

Seems like the PID file is not created (correctly).

**Comment by wagner-certat** [comment]
Hm, can't reproduce it.
