### ISSUE TITLE
bot debugger requires configured source pipeline

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#1307]
Image a bot which has no configured source pipeline and we use `intelmqctl run bot-id process` to run it for testing purposes:
```
$ intelmqctl run abuse-contacts-sieve-expert process -d -m '{"source.ip": "194.33.108.254", "source.abuse_contact": "abuse@kapper.net", "source.asn": 8972}' -s
intelmqctl: Starting abuse-contacts-sieve-expert...
abuse-contacts-sieve-expert: SieveExpertBot initialized with id abuse-contacts-sieve-expert and intelmq 1.1.0.rc2 and python 3.4.2 (default, Oct  8 2014, 10:45:20) as process 12951.
abuse-contacts-sieve-expert: Bot is starting.
abuse-contacts-sieve-expert: Pipeline ready.
Traceback (most recent call last):
  File "/usr/local/bin/intelmqctl", line 9, in <module>
    load_entry_point('intelmq==1.1.0.rc1', 'console_scripts', 'intelmqctl')()
  File "/home/aaron/intelmq/intelmq/bin/intelmqctl.py", line 1211, in main
    return x.run()
  File "/home/aaron/intelmq/intelmq/bin/intelmqctl.py", line 636, in run
    retval, results = args.func(**args_dict)
  File "/home/aaron/intelmq/intelmq/bin/intelmqctl.py", line 643, in bot_run
    return self.bot_process_manager.bot_run(**kwargs), None
  File "/home/aaron/intelmq/intelmq/bin/intelmqctl.py", line 158, in bot_run
    loglevel=loglevel)
  File "/home/aaron/intelmq/intelmq/lib/bot_debugger.py", line 59, in __init__
    self._process(dryrun, msg, show)
  File "/home/aaron/intelmq/intelmq/lib/bot_debugger.py", line 122, in _process
    self.instance._Bot__source_pipeline.receive = lambda: msg
AttributeError: 'NoneType' object has no attribute 'receive'
```

`self.instance._Bot__source_pipeline` is None because the pipeline is unconfigured.

We do not need a configured source pipeline to run this. We could mimick it if unconfigured. Or just do proper error handling and require it.

Not a release blocker.

**Comment by wagner-certat** [comment]
fixed in 7c3fb352134a7a9c320e3c2db7f048eef9353f4a
