### ISSUE TITLE
sieve expert crashes if sieve file contains no rules

### ISSUE THREAD

**Issue by th-certbund** [certtools/intelmq#1343]
The sieve expert crashes if the sieve file exists but does not contain any rules.

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/intelmq/lib/bot.py", line 167, in start
    self.process()
  File "/usr/lib/python3/dist-packages/intelmq/bots/experts/sieve/expert.py", line 86, in process
    for rule in self.sieve.rules:
AttributeError: 'str' object has no attribute 'rules'
```

**Comment by wagner-certat** [comment]
cc @antoinet
