### ISSUE TITLE
intelmqctl = SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by adamziaja** [certtools/intelmq#1346]
Version from Github:
```
root@ubuntu:~# intelmqctl -h
Traceback (most recent call last):
  File "/usr/local/bin/intelmqctl", line 9, in <module>
    load_entry_point('intelmq==1.2.0a1', 'console_scripts', 'intelmqctl')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.2.0a1-py2.7.egg/intelmq/bin/intelmqctl.py", line 285
    def bot_status(self, bot_id, *, proc=None):
                                  ^
SyntaxError: invalid syntax
```
```
root@ubuntu:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial
```

**Comment by wagner-certat** [comment]
We do not support Python 2.

How did you install IntelMQ?

**Comment by wagner-certat** [comment]
Closing because of inactivity. Please reopen if needed.
