### ISSUE TITLE
Twitter Parser test fails

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#1356]
```
> INTELMQ_TEST_EXOTIC=1 nosetests tests/bots/parsers/twitter/test_parser.py 
.F
======================================================================
FAIL: test_parse (intelmq.tests.bots.parsers.twitter.test_parser.TestTwitterParserBot)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/dev/intelmq/intelmq/tests/bots/parsers/twitter/test_parser.py", line 71, in test_parse
    self.assertMessageEqual(0, EVENTS[0])
  File "/home/sebastian/dev/intelmq/intelmq/lib/test.py", line 481, in assertMessageEqual
    self.assertDictEqual(expected, event_dict)
AssertionError: {'source.url': 'http://testweb.com/sales-in[486 chars]20K'} != {'feed.name': 'Twitter', 'feed.url': 'https[487 chars]ent'}
  {'__type': 'Event',
   'classification.type': 'blacklist',
   'feed.name': 'Twitter',
   'feed.url': 'https://twitter.com/El_carlos/1234456',
   'raw': 'SGVyZSBpcyBteSBsaW5rLiBJIGhhdmUgcnVuIFNhbGVzLmV4ZSB3aXRoIFZNLgoKaHh4cDovL3Rlc3R3ZWJbLl1jb20vU2FsZXMtSW52b2ljZS8KY2MucHJvL2ltYWdlcy5odG1sClRoZXJlIGlzIGFub3RoZXIgdGhyZWF0LCBhbmQgdGhhdCBpcyBhdCAKaHR0cF1dOi8va2FybG9zIC5uZXQvCgp0YWsgYSBsb29rIGF0IGh4eHA6Ly9ibG9ja1suXWRlWy5dY29tL21hbHdhcmUuZXhlCkFub3RoZXIgdGhyZWF0IGlzIHBsYWNlZCBhdCAgZ2h6eixjb20K',
-  'source.url': 'http://testweb.com/sales-invoice/'}
+  'source.url': 'https://testweb.com/sales-invoice/'}
?                     +

-------------------- >> begin captured logging << --------------------
test-bot: INFO: TwitterParserBot initialized with id test-bot and intelmq 1.1.1.alpha1 and python 3.6.5 (default, Mar 31 2018, 19:45:04) [GCC] as process 3356.
test-bot: INFO: Bot is starting.
test-bot: INFO: Processed 5 messages since last logging.
test-bot: INFO: Bot stopped.
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 2 tests in 0.041s

FAILED (failures=1)
```

@hugeox / @robcza  can you please have a look? I don't see any obvious error.

**Comment by wagner-certat** [comment]
The test only fails on Python 3.6

**Comment by hugeox** [comment]
This is purely a result of a change in the default scheme for url_normalize (https://github.com/niksite/url-normalize/pull/10).
