### ISSUE TITLE
Interactive multi-threaded bots require multiple Keyboard Interrupts

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#1403]
Using bots the new multihreading with `instances_threads` parameter requires multiple SIGTERMs to kill them.

It *did* work correctly at an intermediate step of developing this feature, so there must be a solution :)

For example:

```
wait-expert.0: Received message {'feed.accuracy': 100.0, 'feed.name': 'Spamhaus Drop', 'feed.provider': 'Spamhaus', 'feed.url': 'https://www.spamhaus.org/drop/drop.txt', 'time.observation': '2019-04-09T15:04:40+00:00', 'time.source': '2019-04-05T23:33:22+00:00', 'classification.type': 'spam', 'raw': 'MTU5LjIyOS4wLjAvMTYgOyBTQkwyMTQxNTU=', 'source.network': '159.229.0.0/16', 'extra.blocklist': 'SBL214155'}.
^CKeyboard interrupt.
^CException ignored in: <module 'threading' from '/usr/lib64/python3.6/threading.py'>
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/lib64/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/lib64/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
^C
wait-expert.0: Disconnected from source pipeline.
wait-expert.0: Disconnected from destination pipeline.
wait-expert.0: Bot stopped.
```

**Comment by wagner-certat** [comment]
Only affects `intelmqctl run`

**Comment by dipenpatel235** [comment]
intelmqctl run my-ip-collector
intelmqctl: Starting my-ip-collector...
Traceback (most recent call last):
  File "/usr/local/bin/intelmqctl", line 11, in <module>
    load_entry_point('intelmq==2.0.1a1', 'console_scripts', 'intelmqctl')()
  File "/usr/local/lib/python3.6/dist-packages/intelmq/bin/intelmqctl.py", line 1425, in main
    return x.run()
  File "/usr/local/lib/python3.6/dist-packages/intelmq/bin/intelmqctl.py", line 912, in run
    retval, results = args.func(**args_dict)
  File "/usr/local/lib/python3.6/dist-packages/intelmq/bin/intelmqctl.py", line 919, in bot_run
    return self.bot_process_manager.bot_run(**kwargs), None
  File "/usr/local/lib/python3.6/dist-packages/intelmq/bin/intelmqctl.py", line 165, in bot_run
    loglevel=loglevel)
  File "/usr/local/lib/python3.6/dist-packages/intelmq/lib/bot_debugger.py", line 47, in __init__
    self.instance = bot(bot_id, disable_multithreading=True)
TypeError: __init__() got an unexpected keyword argument 'disable_multithreading'
