### ISSUE TITLE
`intelmqctl run` broken for collectors

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#1414]
```
intelmqctl run my-ip-collector
intelmqctl: Starting my-ip-collector...
Traceback (most recent call last):
  File "/usr/local/bin/intelmqctl", line 11, in <module>
    load_entry_point('intelmq==2.0.1a1', 'console_scripts', 'intelmqctl')()
  File "/usr/local/lib/python3.6/dist-packages/intelmq/bin/intelmqctl.py", line 1425, in main
    return x.run()
  File "/usr/local/lib/python3.6/dist-packages/intelmq/bin/intelmqctl.py", line 912, in run
    retval, results = args.func(**args_dict)
  File "/usr/local/lib/python3.6/dist-packages/intelmq/bin/intelmqctl.py", line 919, in bot_run
    return self.bot_process_manager.bot_run(**kwargs), None
  File "/usr/local/lib/python3.6/dist-packages/intelmq/bin/intelmqctl.py", line 165, in bot_run
    loglevel=loglevel)
  File "/usr/local/lib/python3.6/dist-packages/intelmq/lib/bot_debugger.py", line 47, in __init__
    self.instance = bot(bot_id, disable_multithreading=True)
TypeError: __init__() got an unexpected keyword argument 'disable_multithreading'
```
_Originally posted by @dipenpatel235 in https://github.com/certtools/intelmq/issues/1403#issuecomment-498993389_

**Comment by wagner-certat** [comment]
Thanks for reporting @dipenpatel235 I just fixed this on maintenance and develop. I see that you are using the maintenance branch, so you can just do a pull.
