### ISSUE TITLE
Errors on reload with Pipeline's _has_message at acknowledge

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#1438]
The introduction of the Pipeline's `_has_message` safety flag in 100d342c4198d46e875d9cf0be4bd57e0dff12a8 discloses an error at reload:

```
2019-08-23 02:17:12,380 - maxmind-geoip-expert - INFO - Handling SIGHUP, initializing again now.
2019-08-23 02:17:12,381 - maxmind-geoip-expert - INFO - GeoIPExpertBot initialized with id maxmind-geoip-expert and intelmq 2.1.0.alpha.1 and python 3.4.2 (default, Aug 17 2019, 10:19:24) as process 27276.
2019-08-23 02:17:12,382 - maxmind-geoip-expert - INFO - Bot is starting.
2019-08-23 02:17:12,419 - maxmind-geoip-expert - INFO - Bot initialization completed.
2019-08-23 02:17:12,420 - maxmind-geoip-expert - INFO - Loading source pipeline and queue 'maxmind-geoip-expert-queue'.
2019-08-23 02:17:12,426 - maxmind-geoip-expert - INFO - Acknowledge called.
2019-08-23 02:17:12,427 - maxmind-geoip-expert - ERROR - Pipeline failed.
Traceback (most recent call last):
  File "/home/aaron/intelmq/intelmq/lib/bot.py", line 269, in start
    self.process()
  File "/home/aaron/intelmq/intelmq/bots/experts/maxmind_geoip/expert.py", line 72, in process
    self.acknowledge_message()
  File "/home/aaron/intelmq/intelmq/lib/bot.py", line 616, in acknowledge_message
    self.__source_pipeline.acknowledge()
  File "/home/aaron/intelmq/intelmq/lib/pipeline.py", line 132, in acknowledge
    raise exceptions.PipelineError("No message to acknowledge.")
intelmq.lib.exceptions.PipelineError: pipeline failed - 'No message to acknowledge.'
```

The `INFO - Acknowledge called.` message was added for debugging purposes. So the pipeline is reset at reload, but the bot still knows of the previously processed message.

**Comment by wagner-certat** [comment]
Probably cause: https://github.com/certtools/intelmq/blob/4ea27b9d6660358be7d7e7375837f165d484d1bd/intelmq/lib/bot.py#L572-L573 in `receive_message`
