### ISSUE TITLE
Discard line in parser

### ISSUE THREAD

**Issue by kalyparker** [certtools/intelmq#1441]
Hello,

I'm trying to create a new bot, but feed is not a good feed... Lots of ioc are rejected when I try to insert value in IMQ field (url, ip...)
I wish to discard these lines instead of raising error.
My problem is in the parse_line function, I used this kind of code:

```python
event = self.new_event(report)
event.add('destination.url', value, raise_failure=False)
yield event
self.acknowledge_message()
```

=> everything works except this line is meaningless when there is no value in destination.url.

and if I did that:
```python
event = self.new_event(report)
if not event.add('destination.url', value, raise_failure=False):
     return
yield event
self.acknowledge_message()
```

I have this error:
```
Traceback (most recent call last):
  File "/usr/bin/intelmqctl", line 11, in <module>
    load_entry_point('intelmq==2.0.1', 'console_scripts', 'intelmqctl')()
  File "/usr/lib/python3/dist-packages/intelmq/bin/intelmqctl.py", line 1710, in main
    return x.run()
  File "/usr/lib/python3/dist-packages/intelmq/bin/intelmqctl.py", line 948, in run
    retval, results = args.func(**args_dict)
  File "/usr/lib/python3/dist-packages/intelmq/bin/intelmqctl.py", line 955, in bot_run
    return self.bot_process_manager.bot_run(**kwargs), None
  File "/usr/lib/python3/dist-packages/intelmq/bin/intelmqctl.py", line 162, in bot_run
    loglevel=loglevel)
  File "/usr/lib/python3/dist-packages/intelmq/lib/bot_debugger.py", line 59, in __init__
    self._process(dryrun, msg, show)
  File "/usr/lib/python3/dist-packages/intelmq/lib/bot_debugger.py", line 140, in _process
    self.instance.process()
  File "/usr/lib/python3/dist-packages/intelmq/lib/bot.py", line 913, in process
    self.send_message(*events)
TypeError: <lambda>() missing 1 required positional argument: 'msg'
```

It is probably because I create the event, but never send it.
Any idea how to solve this problem?

**Comment by wagner-certat** [comment]
Don't acknowledge the message in `parse_line`. AFAIR you can just do `return` in `parse_line` to skip a line (see autoshun parser for example).

**Comment by bernhardreiter** [comment]
@kalyparker did the last hint solve your problem?

**Comment by wagner-certat** [comment]
Closing because of inactivity. Please reopen if needed.
