### ISSUE TITLE
SMTP Output bot errors

### ISSUE THREAD

**Issue by grodriguezl** [certtools/intelmq#1464]
SMTP Output bot fails when it tries authentication:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/intelmq/lib/bot.py", line 264, in start
    self.process()
  File "/usr/lib/python3.6/site-packages/intelmq/bots/outputs/smtp/output.py", line 52, in process
    smtp.auth(smtp.auth_plain, user=self.username, password=self.password)
TypeError: auth() got an unexpected keyword argument 'user'
```
Parameters:
* `starttls: True`
* `ssl: False`
* `http_verify_cert: True`

https://github.com/certtools/intelmq/blob/85d31c272a9ec4a20fd2039ca73c0fce27d31149/intelmq/bots/outputs/smtp/output.py#L53
I could bypass it by calling `smtp.login(user,pass)` instead, but I'm not sure if it's the best way.

Additionally, the bot doesn't work properly when it tries to send an email with multiple addresses.
Acording to smtplib, `mail_to` parameter of `sendmail` (which is called by `send_message`), should be a string with one address or a list, instead of a comma separated string as docs say.
It can't accept a list as a parameter because the value is later formatted.

**Comment by wagner-certat** [comment]
Which Python version do you use?
