### ISSUE TITLE
feodo-tracker-browse-parser 

### ISSUE THREAD

**Issue by carmezsa** [certtools/intelmq#1471]
I can not start parser "feodo-tracker-browse-parser". I install "beautifulsoup4" but it resolve the issue.

_apt install python-pip_
_pip install beautifulsoup4_

**LOGS**:
.:.......:.........:::...::....
_tail -f /opt/intelmq/var/log/feodo-tracker-browse-parser.log_ 
2019-11-23 01:06:55,901 - feodo-tracker-browse-parser - INFO - HTMLTableParserBot initialized with id feodo-tracker-browse-parser and intelmq 2.2.0.alpha.1 and python 3.7.3 (default, Oct  7 2019, 12:56:13) as process 8741.
2019-11-23 01:06:55,901 - feodo-tracker-browse-parser - INFO - Bot is starting.
2019-11-23 01:06:55,902 - feodo-tracker-browse-parser - ERROR - Bot initialization failed.
Traceback (most recent call last):
  File "/opt/dev_intelmq/intelmq/lib/bot.py", line 158, in __init__
    self.init()
  File "/opt/dev_intelmq/intelmq/bots/parsers/html_table/parser.py", line 36, in init
    raise ValueError("Could not import 'beautifulsoup4'. Please install it.")
ValueError: Could not import 'beautifulsoup4'. Please install it.
2019-11-23 01:06:55,904 - feodo-tracker-browse-parser - INFO - Bot stopped.
.:.......:.........:::...::....
Reference to install intelMQ 
- https://github.com/certtools/intelmq/blob/develop/docs/Developers-Guide.md#how-to-develop
- https://github.com/certtools/intelmq/blob/develop/docs/INSTALL.md#pypi

Thanks

**Comment by carmezsa** [comment]
Hi,
I resov it:
Reference:  https://stackoverflow.com/questions/43172192/import-error-with-beautifulsoup

.:.::.
You need to do pip3 install beautifulsoup4 or pip3 install bs4 to install BeautifulSoup4

and then you can just use it like this :

from bs4 import BeautifulSoup

.:.:.::..

**Comment by wagner-certat** [comment]
Citing from the error message you posted:

>  Could not import 'beautifulsoup4'. Please install it.

**Comment by wagner-certat** [comment]
The message is now:

> Could not load dependency 'beautifulsoup4', please install it with apt/yum/dnf/zypper (possibly named python3-beautifulsoup4) or pip3.
