### ISSUE TITLE
Error in feodo-tracker-browse-parser bot

### ISSUE THREAD

**Issue by kuchynkap** [certtools/intelmq#1474]
Hi,

feodo-tracker-browse-parser bot produces an error on version 2.1.1:

2019-11-27 10:13:10,571 - feodo-tracker-browse-parser - INFO - HTMLTableParserBot initialized with id feodo-tracker-browse-parser and intelmq 2.1.1 and python 3.6.8 (default, Oct  7 2019, 12:59:55) as process 58531.
2019-11-27 10:13:10,571 - feodo-tracker-browse-parser - INFO - Bot is starting.
2019-11-27 10:13:10,571 - feodo-tracker-browse-parser - INFO - Bot initialization completed.
2019-11-27 10:13:10,576 - feodo-tracker-browse-parser - ERROR - Bot has found a problem.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/intelmq/lib/bot.py", line 267, in start
    self.process()
  File "/usr/lib/python3/dist-packages/intelmq/bots/parsers/html_table/parser.py", line 79, in process
    table = table[self.table_index]
IndexError: list index out of range

**Comment by wagner-certat** [comment]
Which configuration do you have in use for this feed (especially the `table_index` parameter)?

**Comment by kuchynkap** [comment]
> Which configuration do you have in use for this feed (especially the `table_index` parameter)?

I kept the default value: 0

**Comment by wagner-certat** [comment]
Then I can't reproduce the error. The fetched URL is `https://feodotracker.abuse.ch/browse`?

Could you maybe start the bot with `intelmqctl run feodo-tracker-browse-parser -l DEBUG` to see all active parameters and post the output here? You can abort the execution after `Waiting for incoming message.` with Ctrl-C if there is no message

**Comment by kuchynkap** [comment]
Starting feodo-tracker-browse-parser...
feodo-tracker-browse-parser: HTMLTableParserBot initialized with id feodo-tracker-browse-parser and intelmq 2.1.1 and python 3.6.8 (default, Oct  7 2019, 12:59:55) as process 50100.
feodo-tracker-browse-parser: Library path: '/usr/lib/python3/dist-packages/intelmq/lib/bot.py'.
feodo-tracker-browse-parser: Loading defaults configuration from '/etc/intelmq/defaults.conf'.
feodo-tracker-browse-parser: Defaults configuration: parameter 'accuracy' loaded with value 100.
feodo-tracker-browse-parser: Defaults configuration: parameter 'destination_pipeline_broker' loaded with value 'redis'.
feodo-tracker-browse-parser: Defaults configuration: parameter 'destination_pipeline_db' loaded with value 2.
feodo-tracker-browse-parser: Defaults configuration: parameter 'destination_pipeline_host' loaded with value '127.0.0.1'.
feodo-tracker-browse-parser: Defaults configuration: parameter 'destination_pipeline_password' loaded with value 'HIDDEN'.
feodo-tracker-browse-parser: Defaults configuration: parameter 'destination_pipeline_port' loaded with value 6379.
feodo-tracker-browse-parser: Defaults configuration: parameter 'error_dump_message' loaded with value True.
feodo-tracker-browse-parser: Defaults configuration: parameter 'error_log_exception' loaded with value True.
feodo-tracker-browse-parser: Defaults configuration: parameter 'error_log_message' loaded with value False.
feodo-tracker-browse-parser: Defaults configuration: parameter 'error_max_retries' loaded with value 3.
feodo-tracker-browse-parser: Defaults configuration: parameter 'error_procedure' loaded with value 'pass'.
feodo-tracker-browse-parser: Defaults configuration: parameter 'error_retry_delay' loaded with value 15.
feodo-tracker-browse-parser: Defaults configuration: parameter 'http_proxy' loaded with value '192.168.240.116:3128'.
feodo-tracker-browse-parser: Defaults configuration: parameter 'http_timeout_max_tries' loaded with value 3.
feodo-tracker-browse-parser: Defaults configuration: parameter 'http_timeout_sec' loaded with value 30.
feodo-tracker-browse-parser: Defaults configuration: parameter 'http_user_agent' loaded with value 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36'.
feodo-tracker-browse-parser: Defaults configuration: parameter 'http_verify_cert' loaded with value True.
feodo-tracker-browse-parser: Defaults configuration: parameter 'https_proxy' loaded with value '192.168.240.116:3128'.
feodo-tracker-browse-parser: Defaults configuration: parameter 'load_balance' loaded with value False.
feodo-tracker-browse-parser: Defaults configuration: parameter 'log_processed_messages_count' loaded with value 500.
feodo-tracker-browse-parser: Defaults configuration: parameter 'log_processed_messages_seconds' loaded with value 900.
feodo-tracker-browse-parser: Defaults configuration: parameter 'logging_handler' loaded with value 'file'.
feodo-tracker-browse-parser: Defaults configuration: parameter 'logging_level' loaded with value 'DEBUG'.
feodo-tracker-browse-parser: Defaults configuration: parameter 'logging_path' loaded with value '/var/log/intelmq/'.
feodo-tracker-browse-parser: Defaults configuration: parameter 'logging_syslog' loaded with value '/dev/log'.
feodo-tracker-browse-parser: Defaults configuration: parameter 'process_manager' loaded with value 'intelmq'.
feodo-tracker-browse-parser: Defaults configuration: parameter 'rate_limit' loaded with value 0.
feodo-tracker-browse-parser: Defaults configuration: parameter 'source_pipeline_broker' loaded with value 'redis'.
feodo-tracker-browse-parser: Defaults configuration: parameter 'source_pipeline_db' loaded with value 2.
feodo-tracker-browse-parser: Defaults configuration: parameter 'source_pipeline_host' loaded with value '127.0.0.1'.
feodo-tracker-browse-parser: Defaults configuration: parameter 'source_pipeline_password' loaded with value 'HIDDEN'.
feodo-tracker-browse-parser: Defaults configuration: parameter 'source_pipeline_port' loaded with value 6379.
feodo-tracker-browse-parser: Defaults configuration: parameter 'ssl_ca_certificate' loaded with value None.
feodo-tracker-browse-parser: Defaults configuration: parameter 'statistics_database' loaded with value 3.
feodo-tracker-browse-parser: Defaults configuration: parameter 'statistics_host' loaded with value '127.0.0.1'.
feodo-tracker-browse-parser: Defaults configuration: parameter 'statistics_password' loaded with value 'HIDDEN'.
feodo-tracker-browse-parser: Defaults configuration: parameter 'statistics_port' loaded with value 6379.
feodo-tracker-browse-parser: Bot is starting.
feodo-tracker-browse-parser: Loading runtime configuration from '/etc/intelmq/runtime.conf'.
feodo-tracker-browse-parser: Runtime configuration: parameter 'attribute_name' loaded with value ''.
feodo-tracker-browse-parser: Runtime configuration: parameter 'attribute_value' loaded with value ''.
feodo-tracker-browse-parser: Runtime configuration: parameter 'columns' loaded with value 'time.source,source.ip,malware.name,status,extra.SBL,source.as_name,source.geolocation.cc'.
feodo-tracker-browse-parser: Runtime configuration: parameter 'default_url_protocol' loaded with value 'http://'.
feodo-tracker-browse-parser: Runtime configuration: parameter 'ignore_values' loaded with value ',,,,Not listed,,'.
feodo-tracker-browse-parser: Runtime configuration: parameter 'skip_table_head' loaded with value True.
feodo-tracker-browse-parser: Runtime configuration: parameter 'split_column' loaded with value ''.
feodo-tracker-browse-parser: Runtime configuration: parameter 'split_index' loaded with value 0.
feodo-tracker-browse-parser: Runtime configuration: parameter 'split_separator' loaded with value ''.
feodo-tracker-browse-parser: Runtime configuration: parameter 'table_index' loaded with value 0.
feodo-tracker-browse-parser: Runtime configuration: parameter 'time_format' loaded with value None.
feodo-tracker-browse-parser: Runtime configuration: parameter 'type' loaded with value 'c2server'.
feodo-tracker-browse-parser: Loading pipeline configuration from '/etc/intelmq/pipeline.conf'.
feodo-tracker-browse-parser: Loading Harmonization configuration from '/etc/intelmq/harmonization.conf'.
feodo-tracker-browse-parser: Bot initialization completed.
feodo-tracker-browse-parser: Loading source pipeline and queue 'feodo-tracker-browse-parser-queue'.
feodo-tracker-browse-parser: Connected to source queue.
feodo-tracker-browse-parser: Loading destination pipeline and queues ['deduplicator-expert-queue'].
feodo-tracker-browse-parser: Connected to destination queues.
feodo-tracker-browse-parser: Waiting for incoming message.

**Comment by kuchynkap** [comment]
> hen I can't reproduce the error. The fetched URL is `https://feodotracker.abuse.ch/browse`?

Hm it seems that the default url is https://feodotracker.abuse.ch/downloads/ipblocklist.csv

**Comment by wagner-certat** [comment]
> > hen I can't reproduce the error. The fetched URL is `https://feodotracker.abuse.ch/browse`?
> 
> Hm it seems that the default url is https://feodotracker.abuse.ch/downloads/ipblocklist.csv

That's wrong. For the browse feed it should be https://feodotracker.abuse.ch/browse

https://feodotracker.abuse.ch/downloads/ipblocklist.csv is for the Feodo Tracker IPs, and can be parsed with the Abuse.CH IP Parser.

Was this configuration based on wrong docs, wrong default config, etc? (So something we need to fix or improve)

**Comment by kuchynkap** [comment]
It was fresh new install with all config left as default for training purposes.

**Comment by wagner-certat** [comment]
That's strange. I have no idea yet where the wrong URL comes from.

By which method / from which source did you install?

**Comment by kuchynkap** [comment]
By adding repository and installing manually using APT

**Comment by wagner-certat** [comment]
Which operating system?

Sorry for the late response, I was travelling

**Comment by wagner-certat** [comment]
Closing because of inactivity. Please reopen if needed.
