### ISSUE TITLE
Generic-CSV-Parser Error

### ISSUE THREAD

**Issue by arikmro** [certtools/intelmq#1477]
Hi, 
When i trying to start generic csv parser i get the following error. Does anyone have any idea how to fix this?

```
Bot initialization failed.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/intelmq/lib/bot.py", line 154, in __init__
    self.__load_pipeline_configuration()
  File "/usr/lib/python3/dist-packages/intelmq/lib/bot.py", line 734, in __load_pipeline_configuration
    "{!r}.".format(self.__bot_id))
intelmq.lib.exceptions.ConfigurationError: pipeline configuration failed - no key 'Generic-CSV-Parser'.
```

**Comment by wagner-certat** [comment]
Is your parser bot connected with other bots? Especially a collector bot?

**Comment by wagner-certat** [comment]
Closing because of inactivity. Please reopen if needed.
