### ISSUE TITLE
University of Toulouse Parsing

### ISSUE THREAD

**Issue by cirt1234** [certtools/intelmq#1482]
Hi,
Has anyone encountered parsing these feeds (https://dsi.ut-capitole.fr/blacklists/) because I don’t have any ideas how to do this and I get the following error in the parser: 

```
Bot has found a problem.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/intelmq/lib/bot.py", line 267, in start
    self.process()
  File "/usr/lib/python3/dist-packages/intelmq/lib/bot.py", line 941, in process
    for line in self.parse(report):
  File "/usr/lib/python3/dist-packages/intelmq/bots/parsers/generic/parser_csv.py", line 78, in parse
    delimiter=str(self.parameters.delimiter)):
TypeError: "delimiter" must be a 1-character string
```
If someone has already done this, could you share your settings for this parser (Generic-CSV-Parser).
Thanks in advance!

**Comment by wagner-certat** [comment]
How did you configure the parser? Like in the docs? https://github.com/certtools/intelmq/blob/82ce60af541bff18c941c7f99d12f37e3a8393d1/docs/Feeds.md#university-of-toulouse

**Comment by wagner-certat** [comment]
Closing because of inactivity. Please reopen if needed.
