### ISSUE TITLE
Can't install on centos7 and centos8 

### ISSUE THREAD

**Issue by Nedfire2347** [certtools/intelmq#1515]
Hi, 
I've got some issues during installation on centos7 and centos8
I've follow the installation process step by step as wrote on docs/INSTALL
On centos7, during intelmqsetup.py 
```
Not overwriting existing 'defaults.conf' with example.
Not overwriting existing 'harmonization.conf' with example.
Not overwriting existing 'pipeline.conf' with example.
Not overwriting existing 'runtime.conf' with example.
Writing BOTS file.
Setting intelmq as owner for it's directories.
Calling `intelmqctl upgrade-config to update/create state file
Traceback (most recent call last):
  File "intelmqsetup.py", line 88, in <module>
    main()
  File "intelmqsetup.py", line 84, in main
    state_file=args.state_file)
  File "intelmqsetup.py", line 70, in intelmqsetup
    drop_privileges=False)
TypeError: __init__() got an unexpected keyword argument 'no_file_logging'
```

On centos8, 
Same error + Unable to find dependencies :  python34 and python34-devel

**Comment by bernhardreiter** [comment]
@Nedfire2347 which of the two methods did you take a) native packages or b) pypi?

Can you give a more complete lists of your steps?

**Comment by wagner-certat** [comment]
I guess the installation has been done from the develop branch, so actually a developer's installation (because `no_file_logging` only exists there in `intelmqsetup`). Maybe it's an upgrade?

> On centos8,
Same error + Unable to find dependencies : python34 and python34-devel

We don't have instructions for CentOS 8 yet. I assume the package names are different, i.e. python36

**Comment by Nedfire2347** [comment]
Hi again
It works on centos7, with new permissions ^^ 
find /opt/intelmq/ -type d -exec chmod 775 {} +
find /opt/intelmq/ -type f -exec chmod 664 {} +

And by redefining env path of intelmq user in order to use intelmqctl 
sudo -u intelmq env PATH=$PATH:/usr/local/bin >/dev/null && /usr/local/bin/intelmqctl"

but despite this, centos8 is more problematic for intelmq-manager 
intelmqctl can't see the /usr/local/bin when apache try to use it on check 
and redifinition of the env & path dont work .

**Comment by wagner-certat** [comment]
> It works on centos7, with new permissions ^^
> find /opt/intelmq/ -type d -exec chmod 775 {} +
> find /opt/intelmq/ -type f -exec chmod 664 {} +

Do you know what the permissions were before that?

> And by redefining env path of intelmq user in order to use intelmqctl
> sudo -u intelmq env PATH=$PATH:/usr/local/bin >/dev/null && /usr/local/bin/intelmqctl"

I guess there is one `"` missing somewhere.
Anyway, that's an important issue as intelmq replies on $PATH as provided by the system. However, we could change the behavior to *also* look in the path where intelmqctl resides, i.e. maybe `/usr/local/bin` in this case. Alternatively, easier, PATH needs to be added in `/etc/environment`/`/etc/environment.d/*.conf`.

> but despite this, centos8 is more problematic for intelmq-manager
> intelmqctl can't see the /usr/local/bin when apache try to use it on check
> and redifinition of the env & path dont work .

Concerning CentOS 8: Contributions are appreciated (documentation, hints for implementation etc.).
