### ISSUE TITLE
Missing "requests" package dependency in setup.py

### ISSUE THREAD

**Issue by gethvi** [certtools/intelmq#1519]
Requests package is required by utils.py, but not listed in setup.py.

```
root@#####:/tmp# git clone git@github.com:certtools/intelmq.git
root@#####:/tmp# cd intelmq
root@#####:/tmp/intelmq# python3 -m venv venv
root@#####:/tmp/intelmq# source venv/bin/activate
(venv) root@#####:/tmp/intelmq# pip install .
(venv) root@#####:/tmp/intelmq# intelmqctl --help
Traceback (most recent call last):
  File "/tmp/intelmq/venv/bin/intelmqctl", line 11, in <module>
    load_entry_point('intelmq', 'console_scripts', 'intelmqctl')()
  File "/tmp/intelmq/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/tmp/intelmq/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/tmp/intelmq/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/tmp/intelmq/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/tmp/intelmq/intelmq/bin/intelmqctl.py", line 31, in <module>
    from intelmq.lib import utils
  File "/tmp/intelmq/intelmq/lib/utils.py", line 25, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by wagner-certat** [comment]
True, I think we can safely (again) require the requests library, even if it is not necessarily required by the core itself as some helpers in utils require it.

Thanks for your report!
