### ISSUE TITLE
Microsoft Bot Requirements deprecated

### ISSUE THREAD

**Issue by chappi6** [certtools/intelmq#1530]
I would like to us the Microsoft collector bot but i cant install the requirements. 
Is it possible to use one of the other packages that are suggested?  

```
 Collecting azure-storage>=0.33 (from -r lib/python3.6/site-packages/intelmq/bots/collectors/microsoft/REQUIREMENTS.txt (line 1))
  Using cached https://artifactory.3ve.bmlv.at/artifactory/api/pypi/pypi-virt/packages/packages/5d/cd/cac628adf6cb0086a24c20d76609445f1bf841483d56ec9f5645bbaa9ab7/azure-storage-0.37.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ftdy4ebv/azure-storage/setup.py", line 55, in <module>
        raise RuntimeError(message)
    RuntimeError:

    Starting with v0.37.0, the 'azure-storage' meta-package is deprecated and cannot be installed anymore.
    Please install the service specific packages prefixed by `azure` needed for your application.
    The complete list of available packages can be found at:
    https://aka.ms/azsdk/python/all

    Here's a non-exhaustive list of common packages:
    - [azure-storage-blob](https://pypi.org/project/azure-storage-blob) : Blob storage client
    - [azure-storage-file-share](https://pypi.org/project/azure-storage-file-share) : Storage file share client
    - [azure-storage-file-datalake](https://pypi.org/project/azure-storage-file-datalake) : ADLS Gen2 client
    - [azure-storage-queue](https://pypi.org/project/azure-storage-queue): Queue storage client
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ftdy4ebv/azure-storage/
```

**Comment by chappi6** [comment]
I actually edited the Requiremts.txt from azure-storage>=0.33 to
azure-storage==0.36 
this looks like it is working with python3.6. 
You may also change this in the master. Otherwise just close the ticket. ;)

**Comment by bernhardreiter** [comment]
chappi6, can you eventually create a pull request? :)

Reading https://pip.pypa.io/en/latest/reference/pip_install/#requirement-specifiers it probably should be
```
azure-storage >=0.33,<0.37
```
so old, working installations have no need to upgrade.

**Comment by wagner-certat** [comment]
Thanks for your contribution!

That will work for now, but is just a temporary solution. Unfortunately, they changed their API and we need to rework the collector bot to be able to retrieve the CTIP/bingmurls data after their switch from Interflow back to Azure planned for End of May.
