### ISSUE TITLE
Mail attachment collector: Error on mails without attachment file name

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#1538]
imbox 0.9.6

branch develop

```
mail-collector: Bot has found a problem.
Traceback (most recent call last):
  File "/home/sebastianw/intelmq/intelmq/lib/bot.py", line 267, in start
    self.process()
  File "/home/sebastianw/intelmq/intelmq/bots/collectors/mail/lib.py", line 53, in process
    if self.process_message(uid, message):
  File "/home/sebastianw/intelmq/intelmq/bots/collectors/mail/collector_mail_attach.py", line 30, in process_message
    attach_filename = attach['filename']
KeyError: 'filename'
```

**Comment by wagner-certat** [comment]
attachments without filenames are just content parts which are not attachments itself

**Comment by wagner-certat** [comment]
For the tests: `attach` could be `{'content-type': 'multipart/mixed', 'size': 2, 'content': <_io.BytesIO object at 0x7f05fed7e5c8>}`
