### ISSUE TITLE
Redis pipeline: acknowledge failed: "Return value was None"

### ISSUE THREAD

**Issue by chappi6** [certtools/intelmq#1542]
I have a new installation of intelmq and I sometimes get this error from the deduplicator expert: 

```
Pipeline failed.
Traceback (most recent call last):
  File "/opt/intelmq/venv36/lib64/python3.6/site-packages/intelmq/lib/bot.py", line 267, in start
    self.process()
  File "/opt/intelmq/venv36/lib64/python3.6/site-packages/intelmq/bots/experts/deduplicator/expert.py", line 60, in process
    self.acknowledge_message()
  File "/opt/intelmq/venv36/lib64/python3.6/site-packages/intelmq/lib/bot.py", line 616, in acknowledge_message
    self.__source_pipeline.acknowledge()
  File "/opt/intelmq/venv36/lib64/python3.6/site-packages/intelmq/lib/pipeline.py", line 134, in acknowledge
    self._acknowledge()
  File "/opt/intelmq/venv36/lib64/python3.6/site-packages/intelmq/lib/pipeline.py", line 262, in _acknowledge
    "" % retval)
intelmq.lib.exceptions.PipelineError: pipeline failed - 'Could not pop message from internal queuefor acknowledgement. Return value was None.'
```

The next message in the log is : Bot will continue in 15 seconds.

I am not sure what this error causes but could it be that this is the result of high CPU utilization? Because the error seems only to appear during high load.

**Comment by wagner-certat** [comment]
Weird. Either it's a bug in redis/the redis python library (unlikely) or a bug in the IntelMQ core. Could you please check if there are multiple instances of the bot running?

> I am not sure what this error causes but could it be that this is the result of high CPU utilization? Because the error seems only to appear during high load.

The behavior should be deterministic anyway :)

**Comment by chappi6** [comment]
Ah great Thanks!!! 
It seams that there was an old deduplicator process running. 
After ending the old process and restarting the new one the error is gone.
