### ISSUE TITLE
'Parameters' object has no attribute 'logging_level'

### ISSUE THREAD

**Issue by vetsolution** [certtools/intelmq#1547]
Hello,
I'm trying the develop branch of intelmq but I get the following error when I run intelmqctl.
```
Traceback (most recent call last):
  File "/usr/local/bin/intelmqctl", line 11, in <module>
    load_entry_point('intelmq', 'console_scripts', 'intelmqctl')()
  File "/opt/dev_intelmq/intelmq/bin/intelmqctl.py", line 1864, in main
    x = IntelMQController(interactive=True)
  File "/opt/dev_intelmq/intelmq/bin/intelmqctl.py", line 703, in __init__
    log_level = self.parameters.logging_level.upper()
AttributeError: #'Parameters' object has no attribute 'logging_level'
```
I don't know if is it normal.
I made a quick workaround by replacing line 703 with
```python
log_level = 'DEBUG' #self.parameters.logging_level.upper()
```

**Comment by wagner-certat** [comment]
Could you please show the output of `intelmqctl debug` as well as `intelmqctl debug | awk -F\' '/DEFAULTS_CONF_FILE/ {print $2}' | xargs cat`? (The latter is the content of the defaults config file)

Looks like the logging level is not defined in your `defaults.conf`, but the file seems to exist.

**Comment by wagner-certat** [comment]
Closing because of inactivity. Please reopen if needed.
