### ISSUE TITLE
dshield bot has an issue

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#160]
6434	2015-03-06 10:32:23,533	dshield-parser	ERROR	Pipeline connection failed (UnboundLocalError("local variable 'ip' referenced before assignment",))	

Stack trace in the dshield bot:

Check the following exception: 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/intelmq-0.0.9-py2.7.egg/intelmq/lib/bot.py", line 60, in start
    self.process()
  File "/usr/local/lib/python2.7/dist-packages/intelmq-0.0.9-py2.7.egg/intelmq/bots/parsers/dshield/parser.py", line 30, in process
    event.add("source_ip", ip)
UnboundLocalError: local variable 'ip' referenced before assignment

**Comment by aaronkaplan** [comment]
Fixed with commit 662df80521254856c4c504575449e857cc02cd3e
