### ISSUE TITLE
 URL Fetcher collector failed to download the PhishTank CSV file

### ISSUE THREAD

**Issue by kunforall** [certtools/intelmq#1615]
I am using IntelMQ version 2.2.1.
Recently, I found the URL Fetcher collector failed to download the PhishTank CSV file.
  CSV file: http://data.phishtank.com/data/online-valid.csv

And the error message as below:
```
Bot has found a problem.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/intelmq/lib/bot.py", line 269, in start
    self.process()
  File "/usr/local/lib/python3.6/dist-packages/intelmq/bots/collectors/http/collector_http.py", line 74, in process
    raise ValueError('HTTP response status code was %i.' % resp.status_code)
ValueError: HTTP response status code was 403.
```
I think the error was due to the redirect of PhishTank download url.
So, I modified the bot: `/usr/local/lib/python3.6/dist-packages/intelmq/bots/collectors/http/collector_http.py`
I added two lines after `resp = self...` to the `collector_http.py` as below.
```
resp = self.session.get(url=http_url)
if self.parameters.provider.lower() == 'phishtank':
    resp = requests.get(url=http_url)
```

**Comment by wagner-certat** [comment]
What you are basically doing is to ignore some of your settings, like proxy, user-agent, etc. See [Bots/Common parameters](https://github.com/certtools/intelmq/blob/master/docs/Bots.md#user-content-common-parameters) (HTTP parameters). Do you have any of those set (as defaults)?

**Comment by kunforall** [comment]
I only edited the following fields, others are the default BOT setting from version 2.2.1.
The OS is Ubuntu 18.04.5 Server (64-bit). 

id: PhishTank-Collector
http_url: http://data.phishtank.com/data/online-valid.csv
name: Online
provider: PhishTank

**Comment by wagner-certat** [comment]
That's strange. The 403 error usually comes from too many requests from the source address and the server sends some information on that in the response headers. Unfortunately that's hard to debug with the current debug logs of the HTTP collector, but that can be changed :) I'll add some debugging output to the collector output.

**Comment by wagner-certat** [comment]
With 303ef38504443307ab3258ac3f787d7e43a6a2eb and ab6c7c7a22cccff9b3804ef63e43fd11b9954a2c the develop branch now contains a new feature: In DEBUG logging level, the HTTP collector logs the request's and request's response's headers and body if the status code is not 2xx (as it is the case here). The change will also be in the next feature release. I hope we can shed some more light on this behavior then, as we could then make a diff using the debug output with and without your fix.

**Comment by wagner-certat** [comment]
Closing because of inactivity. Please reopen if needed.
