### ISSUE TITLE
Run custom bot

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#1646]
_Originally posted by @exitnode in https://github.com/certtools/intelmq/issues/440#issuecomment-721019553_

I wrote my own Bot and added it to the BOTS file. It works when manually executed like this:

`intelmqctl run tldextract-Expert`

The problem is that it is not controllable e.g. via IntelMQ Manager since there is no file "/usr/bin/intelmq.bots.experts.tldextract.expert". Manually creating and editing this file leads to the following error:

```
$ /usr/bin/intelmq.bots.experts.tldextract.expert
Traceback (most recent call last):
  File "/usr/bin/intelmq.bots.experts.tldextract.expert", line 11, in <module>
    load_entry_point('intelmq==2.2.1', 'console_scripts', 'intelmq.bots.experts.tldextract.expert')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2792, in load_entry_point
    raise ImportError("Entry point %r not found" % ((group, name),))
ImportError: Entry point ('console_scripts', 'intelmq.bots.experts.tldextract.expert') not found
```

This is how the file looks like:
```
#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'intelmq==2.2.1','console_scripts','intelmq.bots.experts.tldextract.expert'
__requires__ = 'intelmq==2.2.1'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('intelmq==2.2.1', 'console_scripts', 'intelmq.bots.experts.tldextract.expert')()
    )
```

The configuration inside the BOTS file:
```
        "tldextract": {
            "description": "REDACTED",
            "module": "intelmq.bots.experts.tldextract.expert",
            "parameters": {}
        }
```

The bot itself is located in /usr/lib/python3/dist-packages/intelmq/bots/experts/tldextract/expert.py and looks like this:

```
# -*- coding: utf-8 -*-
from urllib.parse import urlparse

from intelmq.lib.bot import Bot
import tldextract


class TLDExtractExpertBot(Bot):

    def process(self):
        event = self.receive_message()

        [...LOGIC...]

        self.send_message(event)
        self.acknowledge_message()

BOT = TLDExtractExpertBot
```

What else is there to do? Is there a tool that installs self-developed bots so it will be correctly recognized by IntelMQ? Did I miss something?

_Originally posted by @exitnode in https://github.com/certtools/intelmq/issues/440#issuecomment-721019553_

**Comment by wagner-certat** [comment]
@exitnode Before going into details, does the Domain Suffix bot what you are looking for? https://intelmq.readthedocs.io/en/latest/user/bots.html#domain-suffix

**Comment by exitnode** [comment]
First of all: Thank you very much for your fast response!
No, this bot doesn't help but thanks. The custom bot dissects the URL and puts single parts into custom extra.* fields, so they can be read out and written into a csv file, which is then used as a proxy blacklist file. It furthermore does some pattern recognition which leads to adding a flag to the event in order to filter it out some time later in the queue with the generic filter expert.

**Comment by wagner-certat** [comment]
> No, this bot doesn't help but thanks. The custom bot dissects the URL and puts single parts into custom extra.* fields, so they can be read out and written into a csv file, which is then used as a proxy blacklist file. It furthermore does some pattern recognition which leads to adding a flag to the event in order to filter it out some time later in the queue with the generic filter expert.

Ok. If you think this bot can be useful for other IntelMQ users, please consider contributing it.

Creating (basically faking) python entrypoints by hand doesn't sound like a good idea. It won't cause harm, but it's troublesome.
Did you have a look at the developer's guide? Especially the sections installation and update: https://intelmq.readthedocs.io/en/latest/dev/guide.html#installation https://intelmq.readthedocs.io/en/latest/dev/guide.html#update (you may need to adapt the paths of course). In essence, what you do is:
1. clone the repository
2. organize your git workflow, e.g. by creating an extra branch
3. develop your bot module
4. add the entry in BOTS
5. install using `pip install -e $pathtolocalrepo`

**Comment by exitnode** [comment]
Thanks again for you time.

Yes, I had a look into the developer's guide but did not understand the procedure. At the moment I have installed IntelMQ via deb packages. Does this mean that I would have to uninstall IntelMQ and install it again from my own cloned repo after adding a new bot?

**Comment by wagner-certat** [comment]
> Yes, I had a look into the developer's guide but did not understand the procedure. At the moment I have installed IntelMQ via deb packages. Does this mean that I would have to uninstall IntelMQ and install it again from my own cloned repo after adding a new bot?

At the moment this is the only supported way to add custom bots (except for the approach you took). We plan to improve this behavior for version 3.0, but that doesn't help in this situation.

You can also look at this third-party tool but I am not sure if it works in this case: https://github.com/jhemp/intelmq-tools#user-content-installing-a-bot (@jhemp can provide support for it)

**Comment by jhemp** [comment]
I quess the entry_points.txt of intelmq has not been updated, therefore the script you have for your executable is not working
However this is not required in the end, if the bot is present in the  python path you can just write a simple bash file as follows:
#!/bin/python3.6
import bot_folder.parsers.exampleparser.parser
import sys
sys.exit(
    bot_folder.parsers.exampleparser.parser.BOT.run()
)

**Comment by exitnode** [comment]
Thank you both very much!
Problem is now solved by creating the script proposed by @jhemp 
I will nevertheless reconsider our bot deployment strategy and will probably go the official way one day.

**Comment by wagner-certat** [comment]
Closing because of inactivity. Please reopen if needed.
