### ISSUE TITLE
Microsoft CTip Parser

### ISSUE THREAD

**Issue by CysihZ** [certtools/intelmq#1677]
Hi Sebix , 

I get this error when I try to parse data from microsoft. 

2020-12-09 13:22:34,207 - Microsoft-CTIP-Parser - INFO - MicrosoftCTIPParserBot initialized with id Microsoft-CTIP-Parser and intelmq 2.2.2 and python 3.6.3 (default, Apr 10 2019, 14:37:36) as process 26724.
2020-12-09 13:22:34,207 - Microsoft-CTIP-Parser - INFO - Bot is starting.
2020-12-09 13:22:34,208 - Microsoft-CTIP-Parser - INFO - Bot initialization completed.
2020-12-09 13:22:34,215 - Microsoft-CTIP-Parser - ERROR - Failed to parse line.
Traceback (most recent call last):
  File "/opt/intelmq/venv36/lib64/python3.6/site-packages/intelmq/lib/bot.py", line 978, in process
    events = list(filter(bool, value))
  File "/opt/intelmq/venv36/lib64/python3.6/site-packages/intelmq/bots/parsers/microsoft/parser_ctip.py", line 186, in parse_line
    yield from self.parse_azure(line, report)
  File "/opt/intelmq/venv36/lib64/python3.6/site-packages/intelmq/bots/parsers/microsoft/parser_ctip.py", line 254, in parse_azure
    if AZURE[key] != '__IGNORE__':
KeyError: 'DestinationIpInfo.DestinationIpv4Int'

For input i used the Microsoft Azur Collector. I am collection the  container Name: ctip-c2 information an feed them into the Microsoft-CTIP-Parser .

**Comment by CysihZ** [comment]
I also could provide you the message dump files if you need it.

**Comment by wagner-certat** [comment]
The currently released version (2.2.2) does not contain support for that field / the c2 feed, but we got a fix for that recently (https://github.com/certtools/intelmq/commit/72c43ba6b160efb5a2612150d13d031103c4447e#diff-577edf46a267353967fceedf20104222e4fa3f5087e439367e1c437ff3e53a94)

I see that you are using a venv, so you could - instead of waiting for me to release the next bugfix version - update to the current commit in the maintenance branch or copy this file https://github.com/certtools/intelmq/blob/maintenance/intelmq/bots/parsers/microsoft/parser_ctip.py to `/opt/intelmq/venv36/lib64/python3.6/site-packages/intelmq/bots/parsers/microsoft/parser_ctip.py` (very hacky, but would work and is fast)

**Comment by CysihZ** [comment]
Thanks for you help i did it the hacky way ;) 
I didn't know that there is already a fix for this issue.
