### ISSUE TITLE
sieve expert datetime math operations fail on second message

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#1710]
The basic datetime math operations work fine on the first message, but not on the next one:

```
sieve-expert: Bot has found a problem.
Traceback (most recent call last):
  File "/.../intelmq/intelmq/lib/bot.py", line 274, in start
    self.process()
  File "/.../intelmq/intelmq/bots/experts/sieve/expert.py", line 97, in process
    procedure = self.process_rule(rule, event)
  File "/.../intelmq/intelmq/bots/experts/sieve/expert.py", line 123, in process_rule
    procedure = self.process_action(action.action, event)
  File "/.../intelmq/intelmq/bots/experts/sieve/expert.py", line 269, in process_action
    action.value = SieveExpertBot.compute_basic_math(action, event)
  File "/.../intelmq/intelmq/bots/experts/sieve/expert.py", line 252, in compute_basic_math
    return (date - datetime.timedelta(minutes=parse_relative(action.value))).isoformat()
  File "/.../intelmq/intelmq/lib/utils.py", line 493, in parse_relative
    raise ValueError("Could not process result of regex for attribute " + repr(relative_time))
ValueError: Could not process result of regex for attribute '2021-01-11T15:25:04+00:00'
```

For debugging I printed the key/values of the `action` variable in `compute_basic_math`. In the first run it is:
```
{'key': 'time.source', 'operator': '-=', 'value': '1 hour', '_tx_position': 26, '_tx_position_end': 54, 'parent': <textx:sieve.Action instance at 0x7f315994b588>}
```
and in the second it is:
```
{'key': 'time.source', 'operator': '-=', 'value': '2021-01-11T15:25:04+00:00', '_tx_position': 26, '_tx_position_end': 54, 'parent': <textx:sieve.Action instance at 0x7f315994b588>}
```

The (probable) reason is that the new code changes the `action.value` value here: https://github.com/certtools/intelmq/pull/1696/files#diff-03fef6f11573511a58ca52162269f48eefd1504b6e139142f1c0b2a68368341fR256 and this value is then retained.

While the fix should be easy, writing a test seems not to be easy. Using multiple input messages at one is not sufficient, as the testing framework starts the bot for each message separately.

**Comment by waldbauer-certat** [comment]
Fixed in #1708
