### ISSUE TITLE
intelmqctl check fails in develop

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#1815]
```
Traceback (most recent call last):
  File "/usr/local/bin/intelmqctl", line 11, in <module>
    load_entry_point('intelmq', 'console_scripts', 'intelmqctl')()
  File "/home/sebastianw/dev/intelmq/intelmq/bin/intelmqctl.py", line 1905, in main
    return x.run()
  File "/home/sebastianw/dev/intelmq/intelmq/bin/intelmqctl.py", line 1044, in run
    retval, results = args.func(**args_dict)
  File "/home/sebastianw/dev/intelmq/intelmq/bin/intelmqctl.py", line 1564, in check
    for bot_id, bot in group.items():
AttributeError: 'str' object has no attribute 'items'
```
https://github.com/certtools/intelmq/blob/272ae20704b824811770e2b77d5268205b970e86/intelmq/bin/intelmqctl.py#L1564

**Comment by wagner-certat** [comment]
That line should probably be
```python
for group_name, group in utils.list_all_bots().items():
```
