### ISSUE TITLE
intelmqdump recovery fails

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#1845]
#1840 fixes #1822, but there's the next error:
```
...
(r)ecover by ids, recover (a)ll, delete (e)ntries, (d)elete file, (s)how by ids, (q)uit, edit id (v)? a
Traceback (most recent call last):
  File "/usr/local/bin/intelmqdump", line 11, in <module>
    load_entry_point('intelmq', 'console_scripts', 'intelmqdump')()
  File "/home/sebastianw/dev/intelmq/intelmq/bin/intelmqdump.py", line 333, in main
    pipe = pipeline.PipelineFactory.create(logger=logger, pipeline_args=params)
  File "/home/sebastianw/dev/intelmq/intelmq/lib/pipeline.py", line 51, in create
    pipe = getattr(intelmq.lib.pipeline, broker)(logger=logger, pipeline_args=pipeline_args, load_balance=load_balance, is_multithreaded=is_multithreaded)
TypeError: 'module' object is not callable
```

**Comment by wagner-certat** [comment]
fixed
