### ISSUE TITLE
intelmqctl run process broken (parameter refactoring)

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#1846]
```
intelmq@medan:~> intelmqctl run lookylooexpert-expert process -m '{"source.url": "http://cert.at/"}' -s
Starting lookylooexpert-expert...
lookylooexpert-expert: LookyLooExpertBot initialized with id lookylooexpert-expert and intelmq 3.0.0.alpha.1 and python 3.8.8 (default, Feb 19 2021, 16:53:21) [GCC] as process 11909.
lookylooexpert-expert: Bot is starting.
lookylooexpert-expert: Bot initialization completed.
Traceback (most recent call last):
  File "/usr/local/bin/intelmqctl", line 11, in <module>
    load_entry_point('intelmq', 'console_scripts', 'intelmqctl')()
  File "/home/sebastianw/dev/intelmq/intelmq/bin/intelmqctl.py", line 1905, in main
    return x.run()
  File "/home/sebastianw/dev/intelmq/intelmq/bin/intelmqctl.py", line 1044, in run
    retval, results = args.func(**args_dict)
  File "/home/sebastianw/dev/intelmq/intelmq/bin/intelmqctl.py", line 1054, in bot_run
    retval, results = self.bot_process_manager.bot_run(**kwargs)
  File "/home/sebastianw/dev/intelmq/intelmq/bin/intelmqctl.py", line 179, in bot_run
    output = bd.run()
  File "/home/sebastianw/dev/intelmq/intelmq/lib/bot_debugger.py", line 62, in run
    self.instance._Bot__connect_pipelines()
  File "/home/sebastianw/dev/intelmq/intelmq/lib/bot.py", line 557, in __connect_pipelines
    self.__source_pipeline = PipelineFactory.create(logger=self.logger,
  File "/home/sebastianw/dev/intelmq/intelmq/lib/pipeline.py", line 40, in create
    broker = getattr(pipeline_args, 'source_pipeline_broker')
AttributeError: 'dict' object has no attribute 'source_pipeline_broker'
```

**Comment by wagner-certat** [comment]
And #1845 applies here as well

**Comment by wagner-certat** [comment]
Depending on the branch looked at, there are a different number of `getattr(pipeline_args` calls in PipelineFactory.create, but there should be none as pipeline_args is a dict now

**Comment by wagner-certat** [comment]
The issue here only affects #1840, not develop -> Closing here finally
