### ISSUE TITLE
intelmqctl restart: 'global' is not ignored, leading to exception

### ISSUE THREAD

**Issue by vetsolution** [certtools/intelmq#1869]
Hello,
I try to update my intelmq installation to the latest development version.

pip install is ok but when I run intelmqctl check. I've got following errors:
```
Reading configuration files.
Checking runtime and pipeline configuration.
Bot 'global' has no 'description'.
Bot 'global' has no 'group'.
Bot 'global' has no 'module'.
Bot 'global' has no 'name'.
Bot 'global' has no 'enabled'.
Could not connect to pipeline: create() got multiple values for argument 'logger'
Checking harmonization configuration.
Checking for bots.
Some issues have been found, please check the above output.
```

I suppose that I have to update my runtime.conf but I dont know what to check. 

Can you help me ?

**Comment by wagner-certat** [comment]
8df0305af871dbfca380518aca8543eca38f9d70 (PR #1840) contains a fix for this

**Comment by wagner-certat** [comment]
And the logger issue will be fixed by f3c4ee91d68743220694fb5fd1f69e31ceb926e5 (same PR)

**Comment by vetsolution** [comment]
patch works, thank

**Comment by vetsolution** [comment]
Hello,
Sorry to re-open the Issue. But the fix cause another problem. I cannot start nor stop bots  :s

``` 
root@laptop-michel:/opt/dev_intelmq/intelmq# intelmqctl restart
Restarting Botnet...
Stopping bot Botnet...
Stopping bot Arctichub-Malware-Parser...
Stopping bot Arctichub-Vuln-Parser...
Stopping bot File-Output-Malware...
Stopping bot File-Output-vuln...
Bot URL-Fetcher-Malware-infection was NOT RUNNING.
Bot URL-Fetcher-Vuln was NOT RUNNING.
Traceback (most recent call last):
  File "/usr/local/bin/intelmqctl", line 33, in <module>
    sys.exit(load_entry_point('intelmq', 'console_scripts', 'intelmqctl')())
  File "/opt/dev_intelmq/intelmq/bin/intelmqctl.py", line 1863, in main
    return x.run()
  File "/opt/dev_intelmq/intelmq/bin/intelmqctl.py", line 1033, in run
    retval, results = args.func(**args_dict)
  File "/opt/dev_intelmq/intelmq/bin/intelmqctl.py", line 1081, in bot_restart
    return self.botnet_restart(group=group)
  File "/opt/dev_intelmq/intelmq/bin/intelmqctl.py", line 1195, in botnet_restart
    retval_stop, _ = self.botnet_stop(group=group)
  File "/opt/dev_intelmq/intelmq/bin/intelmqctl.py", line 1161, in botnet_stop
    self.bot_stop(bot_id, getstatus=False)
  File "/opt/dev_intelmq/intelmq/bin/intelmqctl.py", line 1061, in bot_stop
    status = self.bot_process_manager.bot_stop(bot_id, getstatus)
  File "/opt/dev_intelmq/intelmq/bin/intelmqctl.py", line 227, in bot_stop
    module = self.__runtime_configuration[bot_id]['module']
KeyError: 'module'
root@laptop-michel:/opt/dev_intelmq/intelmq# intelmqctl start
Starting Botnet...
Starting Arctichub-Malware-Parser...
Starting Arctichub-Vuln-Parser...
Starting File-Output-Malware...
Starting File-Output-vuln...
Starting URL-Fetcher-Malware-infection...
Starting URL-Fetcher-Vuln...
Traceback (most recent call last):
  File "/usr/local/bin/intelmqctl", line 33, in <module>
    sys.exit(load_entry_point('intelmq', 'console_scripts', 'intelmqctl')())
  File "/opt/dev_intelmq/intelmq/bin/intelmqctl.py", line 1863, in main
    return x.run()
  File "/opt/dev_intelmq/intelmq/bin/intelmqctl.py", line 1033, in run
    retval, results = args.func(**args_dict)
  File "/opt/dev_intelmq/intelmq/bin/intelmqctl.py", line 1049, in bot_start
    return self.botnet_start(group=group)
  File "/opt/dev_intelmq/intelmq/bin/intelmqctl.py", line 1134, in botnet_start
    self.bot_start(bot_id, getstatus=False)
  File "/opt/dev_intelmq/intelmq/bin/intelmqctl.py", line 1051, in bot_start
    status = self.bot_process_manager.bot_start(bot_id, getstatus)
  File "/opt/dev_intelmq/intelmq/bin/intelmqctl.py", line 196, in bot_start
    module = self.__runtime_configuration[bot_id]['module']
KeyError: 'module'

```

**Comment by wagner-certat** [comment]
While it's clear that the develop branch is not stable and some bugs exists, that behaviour is weird. We did not change anything related to the "module" item in the configuration. Can you share the `URL-Fetcher-Vuln`-part of the runtime conf? (censored, of course)

**Comment by vetsolution** [comment]
```
 "URL-Fetcher-Vuln": {
        "bot_id": "URL-Fetcher-Vuln",
        "description": "Generic URL Fetcher is the bot responsible to get the report from an URL.",
        "enabled": true,
        "group": "Collector",
        "groupname": "collectors",
        "module": "intelmq.bots.collectors.http.collector_http",
        "name": "URL Fetcher",
        "parameters": {
            "destination_queues": {
                "_default": [
                    "Arctichub-Vuln-Parser-queue"
                ]
            },
            "extract_files": false,
            "http_password": null,
            "http_url": "[URL]",
            "http_url_formatting": false,
            "http_username": null,
            "name": "Vulnerable services",
            "provider": "...",
            "rate_limit": 3600,
            "ssl_client_certificate": null
        },
        "run_mode": "continuous"
    },
    "global": {
        "accuracy": 100,
        "destination_pipeline_broker": "redis",
        "destination_pipeline_db": 2,
        "destination_pipeline_host": "127.0.0.1",
        "destination_pipeline_password": null,
        "destination_pipeline_port": 6379,
        "error_dump_message": true,
        "error_log_exception": true,
        "error_log_message": false,
        "error_max_retries": 3,
        "error_procedure": "pass",
        "error_retry_delay": 15,
        "http_proxy": null,
        "http_timeout_max_tries": 3,
        "http_timeout_sec": 30,
        "http_user_agent": "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36",
        "http_verify_cert": true,
        "https_proxy": null,
        "load_balance": false,
        "log_processed_messages_count": 500,
        "log_processed_messages_seconds": 900,
        "logging_handler": "file",
        "logging_level": "INFO",
        "logging_path": "/opt/intelmq/var/log/",
        "logging_syslog": "/dev/log",
        "process_manager": "intelmq",
        "rate_limit": 0,
        "source_pipeline_broker": "redis",
        "source_pipeline_db": 2,
        "source_pipeline_host": "127.0.0.1",
        "source_pipeline_password": null,
        "source_pipeline_port": 6379,
        "ssl_ca_certificate": null,
        "statistics_database": 3,
        "statistics_host": "127.0.0.1",
        "statistics_password": null,
        "statistics_port": 6379
    }

```
`intelmqctl restart URL-Fetcher-Vuln` works fine
`/opt/dev_intelmq/intelmq/bots/collectors/http/collector_http.py` exists

But `intelmqctl restart global` fail. 

So I suppose that intelmqctl try to acces module key of global "bot" but it does not exists.

Thank for your help

**Comment by wagner-certat** [comment]
Ah, understood. `intelmqctl (re)start` needs to ignore global as well. `intelmqctl restart global` is not valid.

**Comment by wagner-certat** [comment]
@vetsolution can you please re-test with current develop? PR#1872 will then contain some more fixes regarding similar issues
