### ISSUE TITLE
hug -m intelmq_api.serve

### ISSUE THREAD

**Issue by oscarliz** [certtools/intelmq#2001]
Loading config from /etc/intelmq/api-config.json
Traceback (most recent call last):
  File "/usr/local/bin/hug", line 8, in <module>
    sys.exit(development_runner.hug.interface.cli())
  File "/usr/local/lib/python3.8/dist-packages/hug/interface.py", line 650, in __call__
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/hug/interface.py", line 646, in __call__
    result = self.output(self.interface(**pass_to_function), context)
  File "/usr/local/lib/python3.8/dist-packages/hug/interface.py", line 129, in __call__
    return __hug_internal_self._function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/hug/development_runner.py", line 91, in hug
    _start_api(
  File "/usr/local/lib/python3.8/dist-packages/hug/development_runner.py", line 42, in _start_api
    API(api_module).http.serve(host, port, no_404_documentation, show_intro)
  File "/usr/local/lib/python3.8/dist-packages/hug/api.py", line 277, in serve
    api = self.server()
  File "/usr/local/lib/python3.8/dist-packages/hug/api.py", line 371, in server
    self.api._ensure_started()
  File "/usr/local/lib/python3.8/dist-packages/hug/api.py", line 638, in _ensure_started
    startup_handler(self)
  File "/usr/local/lib/python3.8/dist-packages/intelmq_api/serve.py", line 46, in setup
    intelmq_api.api.initialize_api(api_config)
  File "/usr/local/lib/python3.8/dist-packages/intelmq_api/api.py", line 80, in initialize_api
    session_store = session.SessionStore(str(session_file),
  File "/usr/local/lib/python3.8/dist-packages/intelmq_api/session.py", line 86, in __init__
    self.init_sqlite_db()
  File "/usr/local/lib/python3.8/dist-packages/intelmq_api/session.py", line 100, in init_sqlite_db
    with self.connect() as con:
  File "/usr/local/lib/python3.8/dist-packages/intelmq_api/session.py", line 91, in connect
    return sqlite3.connect(self.dbname, check_same_thread=False,
sqlite3.OperationalError: unable to open database file

**Comment by ghost** [comment]
> sqlite3.OperationalError: unable to open database file

Is the file and the directory containing it writeable for the user?
