### ISSUE TITLE
RDAP expert tests fail on OBS because of an ERROR

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#2014]
The RDAP expert tests are failing on OBS on all plattforms, but not locally:

```
[  114s] test (intelmq.tests.bots.experts.rdap.test_expert.TestRDAPExpertBot) ... FAIL
[  114s] test_404 (intelmq.tests.bots.experts.rdap.test_expert.TestRDAPExpertBot) ... FAIL
[  114s] test_bot_name (intelmq.tests.bots.experts.rdap.test_expert.TestRDAPExpertBot)
[  114s] Test if Bot has a valid name. ... ok
[  114s] test_object_validation (intelmq.tests.bots.experts.rdap.test_expert.TestRDAPExpertBot) ... FAIL
[  114s] test_static_bot_check_method (intelmq.tests.bots.experts.rdap.test_expert.TestRDAPExpertBot)
[  114s] Check if the bot's static check() method completes without errors (exceptions). ... ok
```

```
[  280s] ======================================================================
[  280s] FAIL: test (intelmq.tests.bots.experts.rdap.test_expert.TestRDAPExpertBot)
[  280s] ----------------------------------------------------------------------
[  280s] Traceback (most recent call last):
[  280s]   File "/usr/lib/python3.8/site-packages/requests_mock/mocker.py", line 275, in inner
[  280s]     return func(*args, **kwargs)
[  280s]   File "/home/abuild/rpmbuild/BUILD/intelmq/intelmq/tests/bots/experts/rdap/test_expert.py", line 69, in test
[  280s]     self.run_bot()
[  280s]   File "/home/abuild/rpmbuild/BUILD/intelmq/intelmq/lib/test.py", line 361, in run_bot
[  280s]     self.assertLessEqual(len(re.findall(' - ERROR - ', self.loglines_buffer)), allowed_error_count)
[  280s] AssertionError: 1 not less than or equal to 0
[  280s] 
[  280s] ======================================================================
[  280s] FAIL: test_404 (intelmq.tests.bots.experts.rdap.test_expert.TestRDAPExpertBot)
[  280s] ----------------------------------------------------------------------
[  280s] Traceback (most recent call last):
[  280s]   File "/usr/lib/python3.8/site-packages/requests_mock/mocker.py", line 275, in inner
[  280s]     return func(*args, **kwargs)
[  280s]   File "/home/abuild/rpmbuild/BUILD/intelmq/intelmq/tests/bots/experts/rdap/test_expert.py", line 82, in test_404
[  280s]     self.run_bot()
[  280s]   File "/home/abuild/rpmbuild/BUILD/intelmq/intelmq/lib/test.py", line 361, in run_bot
[  280s]     self.assertLessEqual(len(re.findall(' - ERROR - ', self.loglines_buffer)), allowed_error_count)
[  280s] AssertionError: 1 not less than or equal to 0
[  280s] 
[  280s] ======================================================================
[  280s] FAIL: test_object_validation (intelmq.tests.bots.experts.rdap.test_expert.TestRDAPExpertBot)
[  280s] ----------------------------------------------------------------------
[  280s] Traceback (most recent call last):
[  280s]   File "/usr/lib/python3.8/site-packages/requests_mock/mocker.py", line 275, in inner
[  280s]     return func(*args, **kwargs)
[  280s]   File "/home/abuild/rpmbuild/BUILD/intelmq/intelmq/tests/bots/experts/rdap/test_expert.py", line 76, in test_object_validation
[  280s]     self.run_bot()
[  280s]   File "/home/abuild/rpmbuild/BUILD/intelmq/intelmq/lib/test.py", line 361, in run_bot
[  280s]     self.assertLessEqual(len(re.findall(' - ERROR - ', self.loglines_buffer)), allowed_error_count)
[  280s] AssertionError: 1 not less than or equal to 0
```

**Comment by wagner-certat** [comment]
The problem is missing redis, as the RDAP expert uses the cache, but the test case does not declare it. Worked locally, as a redis instance was running.
