### ISSUE TITLE
beta-branch - install instructions dont' work 

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#206]
Following the install instructions...
then starting intelmq:

```
# sudo -u intelmq ./intelmqctl

Traceback (most recent call last):
  File "./intelmqctl", line 13, in <module>
    from intelmq.lib.pipeline import PipelineFactory, Redis
ImportError: cannot import name PipelineFactory
```

and:

```
Traceback (most recent call last):
  File "/opt/intelmq/bin/intelmqctl", line 13, in <module>
    from intelmq.lib.pipeline import PipelineFactory, Redis
  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/pipeline.py", line 2, in <module>
    import zmq
ImportError: No module named zmq
```

**Comment by SYNchroACK** [comment]
```
pip install -r REQUIREMENTS
```

**Comment by aaronkaplan** [comment]
fixed already in the last commit. 
For Debian based systems, I  prefer to use apt-get install wherever possible. 
Also sysadmins/devops prefer this approach because it allows them to keep packages updated continuously.
with pip install they usually have no direct control over what gets installed and updated when.
