### ISSUE TITLE
Fix `intelmqct run bot-id message get`

### ISSUE THREAD

**Issue by schacht-certat** [certtools/intelmq#2078]
```
Traceback (most recent call last):
  File "/usr/bin/intelmqctl", line 11, in <module>
    load_entry_point('intelmq==3.0.0', 'console_scripts', 'intelmqctl')()
  File "/usr/lib/python3/dist-packages/intelmq/bin/intelmqctl.py", line 1903, in main
    return x.run()
  File "/usr/lib/python3/dist-packages/intelmq/bin/intelmqctl.py", line 1042, in run
    retval, results = args.func(**args_dict)
  File "/usr/lib/python3/dist-packages/intelmq/bin/intelmqctl.py", line 1052, in bot_run
    retval, results = self.bot_process_manager.bot_run(**kwargs)
  File "/usr/lib/python3/dist-packages/intelmq/bin/intelmqctl.py", line 186, in bot_run
    output = bd.run()
  File "/usr/lib/python3/dist-packages/intelmq/lib/bot_debugger.py", line 78, in run
    self._message(self.message_kind, self.msg)
  File "/usr/lib/python3/dist-packages/intelmq/lib/bot_debugger.py", line 125, in _message
    if not bool(self.instance._Bot__source_queues):
AttributeError: 'FileOutputBot' object has no attribute '_Bot__source_queues'
```

**Comment by schacht-certat** [comment]
fixed by 9d2f96f
