### ISSUE TITLE
intelmqctl: 'IntelMQController' object has no attribute 'parameters'

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#2084]
Using branch develop:
```
intelmq@localhost:~> intelmqctl list queues -q
Loading the defaults configuration failed!Traceback (most recent call last):
  File "/dev/intelmq/intelmq/bin/intelmqctl.py", line 93, in __init__
    self.load_defaults_configuration()
  File "/dev/intelmq/intelmq/bin/intelmqctl.py", line 395, in load_defaults_configuration
    setattr(self.parameters, option, value)
AttributeError: 'IntelMQController' object has no attribute 'parameters'
cymru-whois-expert-queue - 4
deduplicator-expert-queue - 8950
tor-nodes-expert-queue - 4
url2fqdn-expert-queue - 3761
url2fqdn-expert-queue-internal - 1
```

**Comment by wagner-certat** [comment]
https://github.com/certtools/intelmq/blob/344f6b9a89c0a5f0d641acac40f050dcd567ea34/intelmq/bin/intelmqctl.py#L395
