### ISSUE TITLE
Output Bot - MongoDB export crash.

### ISSUE THREAD

**Issue by Th4nat0s** [certtools/intelmq#212]
With v1 beta version, i got the following error with the output plugin mongo.
I use default feed of the beta

'''
2015-06-04 16:07:45,648 - MongoDB-output - ERROR - 'str' object does not support item assignment
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/intelmq/lib/bot.py", line 103, in start
    self.process()
  File "build/bdist.linux-x86_64/egg/intelmq/bots/outputs/mongodb/output.py", line 13, in process
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 406, in insert
    gen(), check_keys, self.uuid_subtype, client)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 382, in gen
    doc['_id'] = ObjectId()
TypeError: 'str' object does not support item assignment
2015-06-04 16:07:45,650 - MongoDB-output - ERROR - Check the following exception:
'str' object does not support item assignment
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/intelmq/lib/bot.py", line 103, in start
    self.process()
  File "build/bdist.linux-x86_64/egg/intelmq/bots/outputs/mongodb/output.py", line 13, in process
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 406, in insert
    gen(), check_keys, self.uuid_subtype, client)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 382, in gen
    doc['_id'] = ObjectId()
TypeError: 'str' object does not support item assignment
'''

**Comment by SYNchroACK** [comment]
True. I didnt test it but it will be fixed. If you want, propose a fix.

Thank you @Th4nat0s

**Comment by Th4nat0s** [comment]
Didn't understand where is the issue in the record !! :)

**Comment by SYNchroACK** [comment]
Fixed https://github.com/certtools/intelmq/commit/8f94772c159aabe9cf1574e0ba90e7c0ec3579ad

**Comment by SYNchroACK** [comment]
@Th4nat0s any news?

**Comment by SYNchroACK** [comment]
@Th4nat0s  ?

**Comment by Th4nat0s** [comment]
I'm deeply sorry guys, even at night I have no free time.. time should come back on october...

**Comment by SYNchroACK** [comment]
The current version already solves this issue
