### ISSUE TITLE
Docker Action fails with: cannot remove 'html'

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#2127]
The action "Build and upload docker image" fails since about two months with
```
 ---> eaa19446bc76
Successfully built eaa19446bc76
Successfully tagged intelmq-full:latest
rm: cannot remove 'html': No such file or directory
```

**Comment by sebix** [comment]
The full traceback is actually:
```
Traceback (most recent call last):
  File "/usr/bin/intelmqsetup", line 33, in <module>
    sys.exit(load_entry_point('intelmq', 'console_scripts', 'intelmqsetup')())
  File "/usr/bin/intelmqsetup", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: intelmq
The command '/bin/sh -c cd /etc/intelmq     && pip3 install hug url-normalize geolib imbox jinja2 pyasn textx tld time-machine otxv2     && pip3 install --force pymisp[fileobjects,openioc,virustotal]     && pip3 install --no-cache-dir -e .     && intelmqsetup' returned a non-zero code: 1
rm: cannot remove 'html': No such file or directory
```

**Comment by waldbauer-certat** [comment]
Fixed with latest push to intelmq-docker

**Comment by sebix** [comment]
Thanks!
