### ISSUE TITLE
intelmqdump crashes on getting bot status

### ISSUE THREAD

**Issue by wagner-intevation** [certtools/intelmq#2188]
```
> intelmqdump $x
Processing $x: %y dumps
[...]
Traceback (most recent call last):
  File "/usr/local/bin/intelmqdump", line 33, in <module>
    sys.exit(load_entry_point('intelmq', 'console_scripts', 'intelmqdump')())
  File "/home/dev/intelmq/intelmq/bin/intelmqdump.py", line 287, in main
    bot_status = ctl.bot_status(botid)
  File "/home/dev/intelmq/intelmq/bin/intelmqctl.py", line 484, in bot_status
    status = self._processmanager.bot_status(bot_id)
AttributeError: 'NoneType' object has no attribute 'bot_status'
```

**Comment by wagner-intevation** [comment]
Very likely a result of https://github.com/certtools/intelmq/pull/2067
