### ISSUE TITLE
cymru_whois is broken in beta version

### ISSUE THREAD

**Issue by Th4nat0s** [certtools/intelmq#221]
Hello (again).. 

```
2015-06-08 22:37:21,222 - cymru-whois-expert - ERROR - global name 'socket' is not defined
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/bot.py", line 101, in start
    self.process()
  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/bots/experts/cymru_whois/expert.py", line 36, in process
    ip_integer = IPAddress.to_int(ip)
  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/harmonization.py", line 155, in to_int
    except socket.error:
NameError: global name 'socket' is not defined
```

And indeed it miss a "export socket" in lib/harmonization.py

Then....

````
global name 'ip' is not defined 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/bot.py", line 101, in start
    self.process()
  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/bots/experts/cymru_whois/expert.py", line 36, in process
    ip_integer = IPAddress.to_int(ip)
  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/harmonization.py", line 154, in to_int
    ip_integer = socket.inet_pton(socket.AF_INET, ip)
NameError: global name 'ip' is not defined
```
need to change Ip by value here..

``` 
    @staticmethod
    def to_int(value):
        try:
            ip_integer = socket.inet_pton(socket.AF_INET, value)
        except socket.error:
            try:
                ip_integer = socket.inet_pton(socket.AF_INET6, value)
            except socket.error:
                return None
```
Finally...
```
Check the following exception: 
local variable 'minimum' referenced before assignment
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/bot.py", line 101, in start
    self.process()
  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/bots/experts/cymru_whois/expert.py", line 43, in process
    cache_key = bin(ip_integer)[2 : minimum + 2]
UnboundLocalError: local variable 'minimum' referenced before assignment
```

The test wait an int and the result of version is a string.. quick fix with casting...
```
  ip_version = int(IPAddress.version(ip))
            ip_integer = IPAddress.to_int(ip)

            if ip_version == 4:
                minimum = MINIMUM_BGP_PREFIX_IPV4
            elif ip_version == 6:
                minimum = MINIMUM_BGP_PREFIX_IPV6
```

Pull request : https://github.com/certtools/intelmq/pull/220

That's quickly what I see. but maybe it need better fix for ip_version. Because they're is a lot of misses.. for example hphost feed give "source.fqdn" and it trigger nothing.

Is it scheduled to have a dedicated bot "host 2 ip" before ? a host could have many ip's. Or this plug should do all the stuff ?

**Comment by Th4nat0s** [comment]
After a check of IP... Well... it run.... but doesnt seems to work yet.... :)

**Comment by SYNchroACK** [comment]
I think now is ok: ef928394f42f4e815508af646339090fadb4b647
Check and give feedback please.

**Comment by Th4nat0s** [comment]
Work fine now ! nice.

**Comment by SYNchroACK** [comment]
Cool
