### ISSUE TITLE
taxonomy expert is broken in the beta version

### ISSUE THREAD

**Issue by Th4nat0s** [certtools/intelmq#222]
Hello ...

```
invalid key 'classification.taxonomy' 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/bot.py", line 101, in start
    self.process()
  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/bots/experts/taxonomy/expert.py", line 37, in process
    event.add("classification.taxonomy", taxonomy, sanitize=True)
  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/message.py", line 53, in add
    raise exceptions.InvalidKey(key)
InvalidKey: invalid key 'classification.taxonomy'
```

Need at least : 

```
       "classification.taxonomy": {
                    "type": "String",
                    "description": "test ..."
            },
```

in /intelmq/intelmq/conf/harmonization.conf

Here the quick fix... with json beautify https://github.com/certtools/intelmq/pull/223

**Comment by SYNchroACK** [comment]
Thanks @Th4nat0s
