### ISSUE TITLE
IntelMQ manager/API  from intelmq_api.serve import __hug_wsgi__

### ISSUE THREAD

**Issue by mariuskarotkis** [certtools/intelmq#2248]
Can't login to IntelMQ manager

`Ubuntu 20.04.5 LTS`

Installed from: https://download.opensuse.org/repositories/home:/sebix:/intelmq/xUbuntu_20.04/all/intelmq_3.0.2-1_all.deb

![image](https://user-images.githubusercontent.com/3322571/195336527-b00405d1-f01e-4bdf-97b0-d76d01fa552d.png)

`/var/log/apache2/error.log`
```
mod_wsgi (pid=976): Exception occurred processing WSGI script '/usr/lib/python3/dist-packages/intelmq_api/intelmq-api.wsgi'.
Traceback (most recent call last):
 File "/usr/lib/python3/dist-packages/intelmq_api/intelmq-api.wsgi", line 11, in applicatio
 from intelmq_api.serve import __hug_wsgi__
 ImportError: No module named intelmq_api.serve
```

`hug -m intelmq_api.serve`
```
Loading config from /etc/intelmq/api-config.json
Exception ignored in thread started by: <cyfunction reload_checker at 0x7fa46e7bfa00>
Traceback (most recent call last):
  File "hug/development_runner.py", line 108, in hug.development_runner.reload_checker
TypeError: 'NoneType' object is unsliceable
```

**Comment by sebix** [comment]
In https://github.com/certtools/intelmq/discussions/2243 a similar error was reported

**Comment by mariuskarotkis** [comment]
@sebix 
https://software.opensuse.org/download.html?project=home:sebix:intelmq&package=intelmq

`Ubuntu 20.04`

```
# echo 'deb http://download.opensuse.org/repositories/home:/sebix:/intelmq/xUbuntu_20.04/ /' | sudo tee /etc/apt/sources.list.d/home:sebix:intelmq.list
# curl -fsSL https://download.opensuse.org/repositories/home:sebix:intelmq/xUbuntu_20.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_sebix_intelmq.gpg > /dev/null
# sudo apt update

Get:1 http://download.opensuse.org/repositories/home:/sebix:/intelmq/xUbuntu_20.04  InRelease [1,562 B]
Hit:2 http://lt.archive.ubuntu.com/ubuntu focal InRelease
Hit:3 http://lt.archive.ubuntu.com/ubuntu focal-updates InRelease
Err:1 http://download.opensuse.org/repositories/home:/sebix:/intelmq/xUbuntu_20.04  InRelease
  The following signatures were invalid: EXPKEYSIG E811A89C85E36691 home:sebix:intelmq OBS Project <home:sebix:intelmq@build.opensuse.org>
Hit:4 http://lt.archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:5 http://lt.archive.ubuntu.com/ubuntu focal-security InRelease
Hit:6 http://repo.zabbix.com/zabbix/6.0/ubuntu focal InRelease
Reading package lists... Done
W: GPG error: http://download.opensuse.org/repositories/home:/sebix:/intelmq/xUbuntu_20.04  InRelease: The following signatures were invalid: EXPKEYSIG E811A89C85E36691 home:sebix:intelmq OBS Project <home:sebix:intelmq@build.opensuse.org>
E: The repository 'http://download.opensuse.org/repositories/home:/sebix:/intelmq/xUbuntu_20.04  InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

```
# sudo apt-key list | grep "expired: "

pub   rsa2048 2020-07-23 [SC] [expired: 2022-10-05]
```

**Comment by ndnikolaev** [comment]
Is there any chance key to be updated?

**Comment by sebix** [comment]
@mariuskarotkis 
The current key expires in two years:
```
$ curl -L https://download.opensuse.org/repositories/home:sebix:intelmq:unstable/xUbuntu_20.04/Release.key 2> /dev/null | gpg --show-key - | grep expire
pub   rsa2048 2020-07-03 [SC] [expires: 2024-11-08]
```
You may need to re-import the key.

**Comment by laciKE** [comment]
> curl -L https://download.opensuse.org/repositories/home:sebix:intelmq:unstable/xUbuntu_20.04/Release.key 2> /dev/null | gpg --show-key - | grep expire

@sebix thanks, this helps. However, it uses home:sebix:intelmq:unstable repository, while the [documentation](https://intelmq.readthedocs.io/en/maintenance/user/installation.html#native-packages) still references the home:sebix:intelmq repository, which has the expired key:

```
curl -L https://download.opensuse.org/repositories/home:sebix:intelmq/xUbuntu_20.04/Release.key 2> /dev/null | gpg --show-key - | grep expire
pub   rsa2048/0xE811A89C85E36691 2020-07-23 [SC] [expired: 2022-10-05]
```

**Comment by sebix** [comment]
I re-built a package to re-create the repository:
```
curl -L https://download.opensuse.org/repositories/home:sebix:intelmq/xUbuntu_20.04/Release.key 2> /dev/null | gpg --show-key - | grep expire
```
You may now get an update for package without any changes.

**Comment by sebix** [comment]
The API was in the meantime also migrated from hug to fastapi
