### ISSUE TITLE
malc0de self signed SSL certificate does not work out of the box 

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#2282]
In the current default (out of the box) config, there is a malc0de collector.
There, the SSL certificate check fails:

```bash

cat  malc0de-windows-format-collector*

[...]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='malc0de.com', port=443): Max retries exceeded with url: /bl/BOOT (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/intelmq/lib/bot.py", line 310, in start
    self.process()
  File "/usr/lib/python3/dist-packages/intelmq/bots/collectors/http/collector_http.py", line 84, in process
    resp = self.http_get(http_url)
  File "/usr/lib/python3/dist-packages/intelmq/lib/mixins/http.py", line 103, in http_get
    return self.__session.get(url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/intelmq/lib/mixins/http.py", line 29, in send
    return super().send(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='malc0de.com', port=443): Max retries exceeded with url: /bl/BOOT (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)')))2022-12-05 13:29:12,734 - malc0de-windows-format-collector - ERROR - Bot has found a problem.
```

**Solution**: disable SSL verification check for malc0de, since we can not control the certificate on their side.

**Comment by waldbauer-certat** [comment]
You can disable it in the bot configuration itself using `http_verify_cert: False`

It is part of the HTTP Mixin

**Comment by aaronkaplan** [comment]
**Update**: the malc0de URL does not exist anymore, that explains the SSL certificate problem :) Problem is somewhere else hehe... I contacted the malc0de guys (let's see).
