### ISSUE TITLE
dnspython compat layer is incompatible with dnspython 1.15

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#2289]
@kamil-certat 

This is in a test/build environment with dnspython 1.15.0
```
[  107s] ======================================================================
[  107s] ERROR: test_resolve_dns_supports_dnspython_v2 (intelmq.tests.lib.test_utils.TestUtils)
[  107s] ----------------------------------------------------------------------
[  107s] Traceback (most recent call last):
[  107s]   File "/usr/lib64/python3.6/unittest/mock.py", line 1183, in patched
[  107s]     return func(*args, **keywargs)
[  107s]   File "/home/abuild/rpmbuild/BUILD/intelmq/intelmq/tests/lib/test_utils.py", line 379, in test_resolve_dns_supports_dnspython_v2
[  107s]     with unittest.mock.patch.object(utils.dns.resolver, "resolve") as resolve_mocks:
[  107s]   File "/usr/lib64/python3.6/unittest/mock.py", line 1247, in __enter__
[  107s]     original, local = self.get_original()
[  107s]   File "/usr/lib64/python3.6/unittest/mock.py", line 1221, in get_original
[  107s]     "%s does not have the attribute %r" % (target, name)
[  107s] AttributeError: <module 'dns.resolver' from '/usr/lib/python3.6/site-packages/dns/resolver.py'> does not have the attribute 'resolve'
```

These tests are missing the skip_internet decorator, which will disable this test in that environment anyway, but it still indicates some problem with the compatibility layer.

**Comment by kamil-certat** [comment]
Thanks for the info, I'll take a look here
