### ISSUE TITLE
Pipeline acknowledge failed: Return value was None

### ISSUE THREAD

**Issue by ludoComp9** [certtools/intelmq#2421]
Hello,

From my IntelMQ instance running on Debian 12 (amd64) with IntelMQ 3.2.1, Cymru Whois bot expert failed with following error messages:
```
cymru-whois-expert: Loading destination pipeline and queues {'_default': ['File-Output-3-queue']}.
cymru-whois-expert: Connected to destination queues.
cymru-whois-expert: Pipeline failed.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/intelmq/lib/bot.py", line 348, in start
    self.process()
  File "/usr/lib/python3/dist-packages/intelmq/bots/experts/cymru_whois/expert.py", line 60, in process
    self.acknowledge_message()
  File "/usr/lib/python3/dist-packages/intelmq/lib/bot.py", line 751, in acknowledge_message
    self.__source_pipeline.acknowledge()
  File "/usr/lib/python3/dist-packages/intelmq/lib/pipeline.py", line 165, in acknowledge
    self._acknowledge()
  File "/usr/lib/python3/dist-packages/intelmq/lib/pipeline.py", line 303, in _acknowledge
    raise exceptions.PipelineError("Could not pop message from internal queue "
intelmq.lib.exceptions.PipelineError: pipeline failed - 'Could not pop message from internal queue for acknowledgement. Return value was None.'
cymru-whois-expert: Bot will continue in 15 seconds.
cymru-whois-expert: Loading source pipeline and queue 'cymru-whois-expert-queue'.
cymru-whois-expert: Connected to source queue.
cymru-whois-expert: Loading destination pipeline and queues {'_default': ['File-Output-3-queue']}.
cymru-whois-expert: Connected to destination queues.
cymru-whois-expert: Got no result from Cymru for IP address '90.84.41.204'.
cymru-whois-expert: Processed 500 messages since last logging.
[...]
```
Note:
dnspython module version is 2.3.0

Execution of this expert bot is really really slow.
Same configuration worked fine before IntelMQ 3.2.1.

Any idea ?

Regards,

**Comment by sebix** [comment]
Did the bot work normally after the hiccup?

**Comment by ludoComp9** [comment]
It worked fine with IntelMQ3.1

**Comment by kamil-certat** [comment]
Have you changed anything in the pipeline (redis etc.) configuration? How are other bots (experts, parsers, or outputs) working?

**Comment by sebix** [comment]
Can you check the process list if there is no other cymru expert running?

**Comment by ludoComp9** [comment]
Single one Cymru expert process is running:
```
intelmq     1603       1 83 13:25 ?        00:02:28 /usr/bin/python3 /usr/bin/intelmq.bots.parsers.shadowserver.parser Shadowserver-Parser
intelmq     1622       1 63 13:26 ?        00:01:44 /usr/bin/python3 /usr/bin/intelmq.bots.experts.deduplicator.expert deduplicator-expert
intelmq     1627       1 50 13:26 ?        00:01:21 /usr/bin/python3 /usr/bin/intelmq.bots.experts.taxonomy.expert taxonomy-expert
intelmq     1632       1 50 13:26 ?        00:01:18 /usr/bin/python3 /usr/bin/intelmq.bots.experts.url.expert URL-Expert
intelmq     1639       1 31 13:26 ?        00:00:48 /usr/bin/python3 /usr/bin/intelmq.bots.experts.gethostbyname.expert Gethostbyname-Expert-2
intelmq     1648       1 34 13:26 ?        00:00:51 /usr/bin/python3 /usr/bin/intelmq.bots.experts.asn_lookup.expert ASNLookup-Expert
intelmq     1651       1  0 13:26 ?        00:00:00 /usr/bin/python3 /usr/bin/intelmq.bots.experts.cymru_whois.expert cymru-whois-expert
```

**Comment by ludoComp9** [comment]
<img width="748" alt="image" src="https://github.com/certtools/intelmq/assets/78788761/040e4bef-9920-4dfa-a72e-3f13dbdee1f4">

**Comment by sebix** [comment]
I see no obvious reason so far, and it is hard to guess what the issue was. Thanks to the existing safeguard architecture of IntelMQ, we see no indications for a critical issue. The concept is, better raise a warning too much, than one too less.

**Comment by kamil-certat** [comment]
I would suggest looking into redis logs, and maybe verifying the bot before Cymru. Have you tried to re-create the Whois bot?

**Comment by sebix** [comment]
@ludoComp9 Did you see this error again?

**Comment by ludoComp9** [comment]
> @ludoComp9 Did you see this error again?

yes absolutely

**Comment by sebix** [comment]
And only with the cymru expert?
How often does it occur? A few times per year, multiple times a day?

Could you apply the following patch to show the resulting log messages?
```diff
--- a/intelmq/lib/pipeline.py
+++ b/intelmq/lib/pipeline.py
@@ -302,7 +302,7 @@ def _acknowledge(self):
             if not retval:
                 raise exceptions.PipelineError("Could not pop message from internal queue "
                                                "for acknowledgement. Return value was %r."
-                                               "" % retval)
+                                               " Internal queue length: %s" % (retval, self.pipe.llen(self.internal_queue)))
```
To check if the pop operation succeeded despite the bad return value or not.

You can set `error_retry_delay` for the bot to `0` to avoid the waiting time, which is useless for this kind of error.

**Comment by ludoComp9** [comment]
Same issue (still too low...)
From Shadowserver collector, I receive more than 1,5M events and lot of logs to parse are in waiting for process from Cymru-Expert instances.

<img width="533" height="587" alt="Image" src="https://github.com/user-attachments/assets/41d9990d-1ecc-42be-966b-1ff65a5ca5f2" />

With URL-Expert:
<img width="1372" height="520" alt="Image" src="https://github.com/user-attachments/assets/4ac2369f-2bb4-40ac-a0aa-338ca0dbdf0c" />

Note: Same issue with only one Gethostname-Expert, Cymru-Expert, Sieve-Expert

**Comment by sebix** [comment]
> Same issue (still too low...)

The patch won't change the behavior, it was meant as additional output to get more insight into what is happening.

Also, what operating system do you use, which version of redis/valkey and python-redis is installed?
```bash
lsb_release -a
redis-server --version
pip show redis
```

**Comment by ludoComp9** [comment]
`lbs_release -a`
```
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
```

Full Debian version: 12.11

`redis-server --version`
```
Redis server v=7.0.15 sha=00000000:0 malloc=jemalloc-5.3.0 bits=64 build=3f20e06e76a2b578
```

`pip show redis`
```
Name: redis
Version: 4.3.4
Summary: Python client for Redis database and key-value store
Home-page: https://github.com/redis/redis-py
Author: Redis Inc.
Author-email: oss@redis.com
License: MIT
Location: /usr/lib/python3/dist-packages
Requires: 
Required-by:
```
