### ISSUE TITLE
pyyaml PendingDeprecationWarning: you should no longer specify 'unsafe' -> test failure

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#2489]
- python311
- ruamel.yaml 0.18.6 (with C library)

`intelmq.tests.bots.experts.modify.test_expert.TestModifyExpertBot.test_events`

```
[   19s] /home/abuild/rpmbuild/BUILD/intelmq/intelmq/lib/utils.py:222: PendingDeprecationWarning: 
[   19s] you should no longer specify 'unsafe'.
[   19s] For **dumping only** use yaml=YAML(typ='full')
[   19s] 
[   19s]   config = YAML(typ="unsafe", pure=True).load(fpconfig)
```

This leads to
```
[   29s] ======================================================================
[   29s] FAIL: test_events (intelmq.tests.bots.experts.modify.test_expert.TestModifyExpertBot.test_events)
[   29s] Test if correct Events have been produced.
[   29s] ----------------------------------------------------------------------
[   29s] Traceback (most recent call last):
[   29s]   File "/home/abuild/rpmbuild/BUILD/intelmq/intelmq/tests/bots/experts/modify/test_expert.py", line 90, in test_events
[   29s]     self.run_bot(iterations=7)
[   29s]   File "/home/abuild/rpmbuild/BUILD/intelmq/intelmq/lib/test.py", line 401, in run_bot
[   29s]     self.assertTrue(fields['message'][-1] in '.:?!',
[   29s] AssertionError: False is not true : Logline '/home/abuild/rpmbuild/BUILD/intelmq/intelmq/lib/utils.py:222: PendingDeprecationWarning: ' does not end with .? or !.
[   29s] 
[   29s] ----------------------------------------------------------------------
```

**Comment by sebix** [comment]
unsafe was used for backwards compatibility with JSON: 09e1d594ea and as an attempt to preserve comments, but didn't work either (#2003).

As a fix for this will have quite some impact and risk, I'm hesitant to include the fix in 3.3.1, let's better postpone it for better testing.

**Comment by sebix** [comment]
Needs to be postponed
