### ISSUE TITLE
cif3 dependency is not compatible with Python >= 3.12

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#2543]
```
+ pip install -r intelmq/bots/outputs/cif3/REQUIREMENTS.txt
Collecting cifsdk<4.0,>=3.0.0rc4 (from -r intelmq/bots/outputs/cif3/REQUIREMENTS.txt (line 4))
  Downloading cifsdk-3.0.8.tar.gz (33 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      /tmp/pip-install-rc27x630/cifsdk_09c67ffb52ae4f629dddca40568419c3/versioneer.py:485: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "/opt/hostedtoolcache/Python/3.13.0/x64/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/opt/hostedtoolcache/Python/3.13.0/x64/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/hostedtoolcache/Python/3.13.0/x64/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-rzqm2bt_/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-rzqm2bt_/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-rzqm2bt_/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-rzqm2bt_/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 31, in <module>
        File "/tmp/pip-install-rc27x630/cifsdk_09c67ffb52ae4f629dddca40568419c3/versioneer.py", line 1473, in get_version
          return get_versions()["version"]
                 ~~~~~~~~~~~~^^
        File "/tmp/pip-install-rc27x630/cifsdk_09c67ffb52ae4f629dddca40568419c3/versioneer.py", line 1406, in get_versions
          cfg = get_config_from_root(root)
        File "/tmp/pip-install-rc27x630/cifsdk_09c67ffb52ae4f629dddca40568419c3/versioneer.py", line 412, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

**Comment by sebix** [comment]
The current version 4.0 (released in 2019) isn't compatible either and the maintenance of the library has been stopped: https://github.com/csirtgadgets/cifsdk-v4-py

That means we'll need to deprecate the output bot, unless someone steps in and maintains it.
