### ISSUE TITLE
Multiple bugs in Parsers

### ISSUE THREAD

**Issue by alnc** [certtools/intelmq#278]
**hphosts-parser**
```
2015-08-09 17:25:36,225 - hphosts-parser - INFO - Processed 92500 messages
2015-08-09 17:25:36,411 - hphosts-parser - ERROR - Bot has found a problem
2015-08-09 17:25:36,411 - hphosts-parser - ERROR - invalid value u'95.140.125.124' (<type 'unicode'>) for key 'source.fqdn'
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/intelmq/lib/bot.py", line 101, in start
    self.process()
  File "build/bdist.linux-x86_64/egg/intelmq/bots/parsers/hphosts/parser.py", line 42, in process
  File "build/bdist.linux-x86_64/egg/intelmq/lib/message.py", line 68, in add
    raise exceptions.InvalidValue(key, value)
InvalidValue: invalid value u'95.140.125.124' (<type 'unicode'>) for key 'source.fqdn'
2015-08-09 17:25:36,412 - hphosts-parser - ERROR - Check the following exception: 
invalid value u'95.140.125.124' (<type 'unicode'>) for key 'source.fqdn'
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/intelmq/lib/bot.py", line 101, in start
    self.process()
  File "build/bdist.linux-x86_64/egg/intelmq/bots/parsers/hphosts/parser.py", line 42, in process
  File "build/bdist.linux-x86_64/egg/intelmq/lib/message.py", line 68, in add
    raise exceptions.InvalidValue(key, value)
InvalidValue: invalid value u'95.140.125.124' (<type 'unicode'>) for key 'source.fqdn'
2015-08-09 17:25:36,412 - hphosts-parser - INFO - Bot will restart in 15 seconds
```

**phishtank-parser-queue**
```
'ascii' codec can't encode character u'\xa8' in position 122: ordinal not in range(128)
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/intelmq/lib/bot.py", line 101, in start
    self.process()
  File "build/bdist.linux-x86_64/egg/intelmq/bots/parsers/phishtank/parser.py", line 49, in process
  File "build/bdist.linux-x86_64/egg/intelmq/lib/message.py", line 63, in add
    value = self.__sanitize_value(key, value)
  File "build/bdist.linux-x86_64/egg/intelmq/lib/message.py", line 132, in __sanitize_value
    return class_reference().sanitize(value)
  File "build/bdist.linux-x86_64/egg/intelmq/lib/harmonization.py", line 263, in sanitize
    value = base64.b64encode(value)
  File "/usr/lib/python2.7/base64.py", line 53, in b64encode
    encoded = binascii.b2a_base64(s)[:-1]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa8' in position 122: ordinal not in range(128)
```

**urlvir-hosts-parser**
```
Check the following exception: 
invalid value u'217.199.161.78' () for key 'source.fqdn'
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/intelmq/lib/bot.py", line 101, in start
    self.process()
  File "build/bdist.linux-x86_64/egg/intelmq/bots/parsers/urlvir/parser_hosts.py", line 28, in process
  File "build/bdist.linux-x86_64/egg/intelmq/lib/message.py", line 68, in add
    raise exceptions.InvalidValue(key, value)
InvalidValue: invalid value u'217.199.161.78' () for key 'source.fqdn'
```

**vxvault-parser**
```
2015-08-11 04:21:07,538 - vxvault-parser - ERROR - Bot has found a problem
2015-08-11 04:21:07,538 - vxvault-parser - ERROR - invalid value u'185.14.28.123' (<type 'unicode'>) for key 'source.fqdn'
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/intelmq/lib/bot.py", line 101, in start
    self.process()
  File "build/bdist.linux-x86_64/egg/intelmq/bots/parsers/vxvault/parser.py", line 38, in process
  File "build/bdist.linux-x86_64/egg/intelmq/lib/message.py", line 68, in add
    raise exceptions.InvalidValue(key, value)
InvalidValue: invalid value u'185.14.28.123' (<type 'unicode'>) for key 'source.fqdn'
2015-08-11 04:21:07,539 - vxvault-parser - ERROR - Check the following exception: 
invalid value u'185.14.28.123' (<type 'unicode'>) for key 'source.fqdn'
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/intelmq/lib/bot.py", line 101, in start
    self.process()
  File "build/bdist.linux-x86_64/egg/intelmq/bots/parsers/vxvault/parser.py", line 38, in process
  File "build/bdist.linux-x86_64/egg/intelmq/lib/message.py", line 68, in add
    raise exceptions.InvalidValue(key, value)
InvalidValue: invalid value u'185.14.28.123' (<type 'unicode'>) for key 'source.fqdn'
2015-08-11 04:21:07,539 - vxvault-parser - INFO - Last Correct Message(event): None
```

**Comment by sebix** [comment]
The bug in `phishtank-parser-queue` is related to #281 (Unicode/ASCII handling)

**Comment by SYNchroACK** [comment]
All fixed except the PhishTank encoding issue.

**Comment by SYNchroACK** [comment]
@alnc can you confirm my last comment here?

**Comment by sebix** [comment]
Phishtank should work, at least for me.
