### ISSUE TITLE
Cymru expert error in data type / harmonization.conf file

### ISSUE THREAD

**Issue by pedromreis** [certtools/intelmq#308]
Recent changes on the harmonization.conf file, changing "source.allocated" type from String to DateTime breaks cymru-expert. 
Also, harmonization.conf file lacks "source.cc" and "source.bgp_prefix" needed by this bot.

**Comment by sebix** [comment]
Will have a look, thanks for reporting. Fix will hopefully come today.

**Comment by sebix** [comment]
Looking at the current master, it seems your assumptions are not correct: https://github.com/certtools/intelmq/blob/master/intelmq/bots/experts/cymru_whois/lib.py

There's no `source.cc`, it's `source.geolocation.cc`, which does exist. The same with `source.bgp_prefix`, it's `source.network` in the bot.

For the allocation time: Can you please provide the dumped message, which causes an error? Maybe the data format is not uniform.

**Comment by pedromreis** [comment]
humm, errors began this morning after installing the current version.
Let me check if I can replicate... maybe some error on my side :)

**Comment by pedromreis** [comment]
Here is the error I got, messages from alienvault processed by cymru, just now:
'''
Bot has found a problem.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/bot.py", line 117, in start
    self.process()
  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/bots/experts/cymru_whois/expert.py", line 71, in process
    force=True)
  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/message.py", line 87, in add
    raise exceptions.InvalidKey(key)
InvalidKey: invalid key u'source.cc'
'''

**Comment by sebix** [comment]
Reinstalled? Probably delete `/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/message.py` and `.pyc` manually before reinstall.

**Comment by pedromreis** [comment]
Ok, will try that.

**Comment by pedromreis** [comment]
That files are current:
```
intelmq-prod lib # ll
total 184
drwxr-sr-x 3 root staff  4096 Sep  1 16:36 ./
drwxr-sr-x 5 root staff  4096 Sep  1 16:36 ../
-rw-r--r-- 1 root staff 13629 Sep  1 16:36 bot.py
-rw-r--r-- 1 root staff 12239 Sep  1 16:36 bot.pyc
-rw-r--r-- 1 root staff   989 Sep  1 16:36 cache.py
-rw-r--r-- 1 root staff  1904 Sep  1 16:36 cache.pyc
drwxr-sr-x 2 root staff  4096 Sep  1 16:36 docs/
-rw-r--r-- 1 root staff  2417 Sep  1 16:36 exceptions.py
-rw-r--r-- 1 root staff  5359 Sep  1 16:36 exceptions.pyc
-rw-r--r-- 1 root staff 11621 Sep  1 16:36 harmonization.py
-rw-r--r-- 1 root staff 16013 Sep  1 16:36 harmonization.pyc
-rw-r--r-- 1 root staff     0 Sep  1 16:36 __init__.py
-rw-r--r-- 1 root staff   173 Sep  1 16:36 __init__.pyc
-rw-r--r-- 1 root staff  7355 Sep  1 16:36 message.py
-rw-r--r-- 1 root staff  9777 Sep  1 16:36 message.pyc
-rw-r--r-- 1 root staff  9089 Sep  1 16:36 pipeline.py
-rw-r--r-- 1 root staff 12567 Sep  1 16:36 pipeline.pyc
-rw-r--r-- 1 root staff 11848 Sep  1 16:36 test.py
-rw-r--r-- 1 root staff 14319 Sep  1 16:36 test.pyc
-rw-r--r-- 1 root staff  5910 Sep  1 16:36 utils.py
-rw-r--r-- 1 root staff  6458 Sep  1 16:36 utils.pyc
```

**Comment by SYNchroACK** [comment]
https://github.com/certtools/intelmq/blob/master/docs/User-Guide.md#upgrade

**Comment by sebix** [comment]
can this issue be closed now?
