### ISSUE TITLE
Clean-MX and Phishtank encoding issues

### ISSUE THREAD

**Issue by pedromreis** [certtools/intelmq#311]
Here it goes:

On clean-mx-virus-parser.dump
```
[...]
uIiwiNjAuMjIwLjAuMCAtIDYwLjIyMy4yNTUuMjU1IiwiVU5JQ09NLVNYIiwiPCFbQ0RBVEFbQ2hpbmEgVW5pY29tIFNoYW54aSBQcm92aW5jZSBOZXR3b3JrQ2hpbmEgVW5pY29tXV0+IiwiZjFnMW5zMS5kbnNwb2QubmV0IiwiZjFnMW5zMi5kbnNwb2QubmV0IiwiIiwiIiwiIgoiMjQwMDAiLCI4MDQwMzk5OSIsInN1YjE2IiwiMjAxNS0wOC0yOCAyMTozMTo1MSIsIjE5NzAtMDEtMDEgMDE6MDA6MDAiLCJDbGFtQVYiLCJXaW4uVHJvamFuLkdlbmVyaWNrZC0xNDAzIiwiaHR0cDovL3hpYXphaS5jZG5kb3duLm5ldC9jeC8yMDE1MDgyNTkvNDYvc2V0dXBfMjE2OWF1MFEuZXhlIiwidXAiLCJhbGl2ZSIsIjEyNS4zOS41LjMzIiwiQVM0ODM3IiwiMTI1LjM5LjUuOCIsImNkbmRvd24ubmV0IiwiQ04iLCJBUE5JQyIsImFidXNlQGNoaW5hdW5pY29tLmNuIiwiMTI1LjM2LjAuMCAtIDEyNS4zOS4yNTUuMjU1IiwiVU5JQ09NLVRKIiwiPCFbQ0RBVEFbQ2hpbmEgVW5pY29tIFRpYW5qaW4gcHJvdmluY2UgbmV0d29ya0NoaW5hIFVuaWNvbUNOQyBHcm91cCBDSElOQTE2OSBUaWFuamluIFByb3ZpbmNlIE5ldHdvcmtdXT4iLCJmMWcxbnMxLmRuc3BvZC5uZXQiLCJmMWcxbnMyLmRuc3BvZC5uZXQiLCIiLCIiLCIiCg==",
            "time.observation": "2015-09-02T17:16:19+00:00"
        },
        "source_queue": "cleanmx-virus-parser-queue",
        "traceback": "Traceback (most recent call last):\n  File \"/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/bot.py\", line 117, in start\n    self.process()\n  File \"/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/bots/parsers/cleanmx/parser_virus.py\", line 83, in process\n    event.add(key, value, sanitize=True)\n  File \"/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/message.py\", line 87, in add\n    raise exceptions.InvalidKey(key)\nInvalidKey: invalid key u'__IGNORE__'\n"
    }
}
```

and on clean-mx-phishing.parser.dump

```
[...]
zMDMwM11dPiIsIm5zMi4ybnNvM3MuY29tLiIsIm5zMS4ybnNvM3MuY29tLiIsIiIsIiIsIiIKIjI0MDAwIiwiNjM4ODQ5NCIsIjIwMTUtMDgtMzAgMDU6MTk6NTYiLCIxOTcwLTAxLTAxIDAxOjAwOjAwIiwiIiwiIiwiaHR0cDovL2ZhY2Vib29rLmNvbS5hY2NvdW50cy5sb2dpbi51c2VyaWQuMjI5NDU0LjJuc28zcy5jb20vd2VjL2Zibi8iLCJ1cCIsImFsaXZlIiwiMTA0LjIzOC4xNzkuMTI5IiwiMTA0LjIzOC4xNzkuMTI5IiwiMm5zbzNzLmNvbSIsIlVTIiwiQVJJTiIsImFidXNlQHZ1bHRyLmNvbSIsIjEwNC4yMzguMTc5LjAgLSAxMDQuMjM4LjE3OS4yNTUiLCJORVQtMTA0LTIzOC0xNzktMC0yNCIsIjwhW0NEQVRBW1Z1bHRyIEhvbGRpbmdzLCBMTEMgVkhMLTMzIDU2IE1hcmlldHRhIFN0cmVldCBBdGxhbnRhIEdBIDMwMzAzXV0+IiwibnMyLjJuc28zcy5jb20uIiwibnMxLjJuc28zcy5jb20uIiwiIiwiIiwiIgo=",
            "time.observation": "2015-09-02T17:15:36+00:00"
        },
        "source_queue": "cleanmx-phishing-parser-queue",
        "traceback": "Traceback (most recent call last):\n  File \"/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/bot.py\", line 117, in start\n    self.process()\n  File \"/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/bots/parsers/cleanmx/parser_phishing.py\", line 72, in process\n    event.add(key, value, sanitize=True)\n  File \"/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/message.py\", line 87, in add\n    raise exceptions.InvalidKey(key)\nInvalidKey: invalid key u'__IGNORE__'\n"
    }
}
```

**Comment by SYNchroACK** [comment]
check #283

**Comment by sebix** [comment]
The parsers using csv are all kind of broken, because the csv package can't deal with unicode. This also affects malwaredomainlist, turris and phishtank

**Comment by SYNchroACK** [comment]
true.

**Comment by SYNchroACK** [comment]
**Phishtank:**
```
2015-09-15 12:28:13,505 - phishtank-parser - DEBUG - Sending message.
2015-09-15 12:28:13,507 - phishtank-parser - DEBUG - Sending message.
2015-09-15 12:28:13,509 - phishtank-parser - ERROR - Bot has found a problem.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/bot.py", line 117, in start
    self.process()
  File "/usr/lib/python2.7/site-packages/intelmq-1.0.0-py2.7.egg/intelmq/bots/parsers/phishtank/parser.py", line 36, in process
    for row in csv.reader(StringIO(raw_report)):
  File "/usr/lib/python2.7/site-packages/unicodecsv/py2.py", line 118, in next
    row = self.reader.next()
UnicodeEncodeError: 'ascii' codec can't encode characters in position 69-72: ordinal not in range(128)
2015-09-15 12:28:13,510 - phishtank-parser - INFO - Last Correct Message(event): None.
2015-09-15 12:28:13,954 - phishtank-parser - INFO - Current Message(event): {u'raw': u'cGhpc2hfaWQsdXJsLHBoaXNoX2RldGFpbF91cmwsc3VibWlzc2lvbl90aW1lLHZlcmlmaWVkLHZlcmlmaWNhdGlvbl90aW1lLG9ubGluZSx0YXJnZXQKMzQ2Mjg1MCxodHRwOi8vaXJzLmJhcmNsYXlsb25kb24uY29tL2dvdi9yZXZlbnVlL2luZGV4LnBocCxodHRwOi8vd3d3LnBoaXNodGFuay5jb20vcGhpc2hfZGV0YWlsLnBocD9waGlzaF9pZD0zNDYyODUwLDIwMTUtMDktMTRUMTk6NDc6MTQrMDA6MDAseWVzLDIwMTUtMDktMTRUMTk6NTY6MjErMDA6MDAseWVzLCJJbnRlcm5hbCBSZXZlbnVlIFNlcnZpY2UiCjM0NjI4MjMsaHR0cDovL3d3dy5jLmFseGEuY29tLmJyL1NsbEJDL3puL2luZGV4LnBocCxodHRwO
2015-09-15 12:28:14,622 - phishtank-parser - INFO - Disconnecting from source pipeline.
2015-09-15 12:28:14,622 - phishtank-parser - INFO - Disconnecting from destination pipeline.
2015-09-15 12:28:14,622 - phishtank-parser - INFO - Bot stopped.
2015-09-15 12:28:14,622 - phishtank-parser - ERROR - Exiting.
2015-09-15 12:28:14,623 - phishtank-parser - INFO - Bot stopped.
2015-09-15 12:28:14,623 - phishtank-parser - ERROR - Exiting.
```

**Comment by sebix** [comment]
Which Python version?

**Comment by SYNchroACK** [comment]
2

**Comment by SYNchroACK** [comment]
Phishtank is ok now. I will open a new issue regarding the new format of feed
