### ISSUE TITLE
Blocklist.de - Certificate validation

### ISSUE THREAD

**Issue by SYNchroACK** [certtools/intelmq#321]
```
Bot has found a problem.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/bot.py", line 117, in start
    self.process()
  File "/usr/lib/python2.7/site-packages/intelmq-1.0.0-py2.7.egg/intelmq/bots/collectors/http/collector_http.py", line 50, in process
    verify=self.verify_cert)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: hostname 'lists.blocklist.de' doesn't match either of 'www.blocklist.de', 'blocklist.de'
```

**Comment by SYNchroACK** [comment]
**Workaround:** add to /opt/intelmq/etc/default.conf the following parameter:
```
    "verify_cert": false
```

**Comment by SYNchroACK** [comment]
https://docs.python.org/dev/library/ssl.html#ssl.HAS_SNI
https://bugzilla.redhat.com/show_bug.cgi?id=836834
https://bugs.launchpad.net/ubuntu/+source/python-requests/+bug/1299075

**Comment by sebix** [comment]
This workaround will be implemented: https://github.com/kennethreitz/requests/blob/master/requests/packages/urllib3/contrib/pyopenssl.py#L16
