### ISSUE TITLE
Spamhaus Drop Collector Bot -  HTTP response status code was 403

### ISSUE THREAD

**Issue by SYNchroACK** [certtools/intelmq#323]
```
2015-09-14 14:47:00,145 - spamhaus-drop-collector - INFO - Bot starts processings.
2015-09-14 14:47:00,145 - spamhaus-drop-collector - INFO - Loading source pipeline.
2015-09-14 14:47:00,146 - spamhaus-drop-collector - INFO - Loading source queue.
2015-09-14 14:47:00,146 - spamhaus-drop-collector - INFO - Source queue loaded None.
2015-09-14 14:47:00,146 - spamhaus-drop-collector - INFO - Connected to source queue.
2015-09-14 14:47:00,146 - spamhaus-drop-collector - INFO - Loading destination pipeline.
2015-09-14 14:47:00,146 - spamhaus-drop-collector - INFO - Loading destination queues.
2015-09-14 14:47:00,147 - spamhaus-drop-collector - INFO - Destination queues loaded [u'spamhaus-drop-parser-queue'].
2015-09-14 14:47:00,147 - spamhaus-drop-collector - INFO - Connected to destination queues.
2015-09-14 14:47:00,147 - spamhaus-drop-collector - INFO - Pipeline ready.
2015-09-14 14:47:00,147 - spamhaus-drop-collector - INFO - Start processing.
2015-09-14 14:47:00,147 - spamhaus-drop-collector - INFO - Downloading report from https://www.spamhaus.org/drop/drop.lasso
2015-09-14 14:47:01,091 - spamhaus-drop-collector - ERROR - Bot has found a problem.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/bot.py", line 117, in start
    self.process()
  File "/usr/lib/python2.7/site-packages/intelmq-1.0.0-py2.7.egg/intelmq/bots/collectors/http/collector_http.py", line 54, in process
    ''.format(resp.status_code))
ValueError: HTTP response status code was 403.
2015-09-14 14:47:01,093 - spamhaus-drop-collector - INFO - Last Correct Message(event): None.
2015-09-14 14:47:01,093 - spamhaus-drop-collector - INFO - Current Message(event): None.
2015-09-14 14:47:01,093 - spamhaus-drop-collector - INFO - Bot will restart in 15 seconds.
2015-09-14 14:47:16,109 - spamhaus-drop-collector - INFO - Bot woke up
2015-09-14 14:47:16,110 - spamhaus-drop-collector - INFO - Trying to start processing again.
2015-09-14 14:47:16,110 - spamhaus-drop-collector - INFO - Downloading report from https://www.spamhaus.org/drop/drop.lasso
2015-09-14 14:47:16,425 - spamhaus-drop-collector - ERROR - Bot has found a problem.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/bot.py", line 117, in start
    self.process()
  File "/usr/lib/python2.7/site-packages/intelmq-1.0.0-py2.7.egg/intelmq/bots/collectors/http/collector_http.py", line 54, in process
    ''.format(resp.status_code))
ValueError: HTTP response status code was 403.
2015-09-14 14:47:16,426 - spamhaus-drop-collector - INFO - Last Correct Message(event): None.
2015-09-14 14:47:16,426 - spamhaus-drop-collector - INFO - Current Message(event): None.
2015-09-14 14:47:16,426 - spamhaus-drop-collector - INFO - Bot will restart in 15 seconds.
```

**Comment by sebix** [comment]
Call https://www.spamhaus.org/drop/drop.lasso with the same IP address and see if you get a 403. It yes, you have been temporarily blocked because of too many requests.

**Comment by sebix** [comment]
This is due to the lack of SNI on your plattform. Please follow the docs on the installation to enable a workaround: https://github.com/certtools/intelmq/blob/master/docs/User-Guide.md#install-dependencies

**Comment by SYNchroACK** [comment]
you are right ;) ty
