### ISSUE TITLE
Taichung encoding issues

### ISSUE THREAD

**Issue by SYNchroACK** [certtools/intelmq#325]
```
2015-09-15 12:26:44,919 - taichung-parser - INFO - Bot starts processings.
2015-09-15 12:26:44,920 - taichung-parser - INFO - Loading source pipeline.
2015-09-15 12:26:44,920 - taichung-parser - INFO - Loading source queue.
2015-09-15 12:26:44,920 - taichung-parser - INFO - Source queue loaded taichung-parser-queue.
2015-09-15 12:26:44,920 - taichung-parser - INFO - Connected to source queue.
2015-09-15 12:26:44,920 - taichung-parser - INFO - Loading destination pipeline.
2015-09-15 12:26:44,920 - taichung-parser - INFO - Loading destination queues.
2015-09-15 12:26:44,921 - taichung-parser - INFO - Destination queues loaded [u'file-output-queue'].
2015-09-15 12:26:44,921 - taichung-parser - INFO - Connected to destination queues.
2015-09-15 12:26:44,921 - taichung-parser - INFO - Pipeline ready.
2015-09-15 12:26:44,921 - taichung-parser - INFO - Start processing.
2015-09-15 12:26:44,921 - taichung-parser - DEBUG - Receiving Message.
2015-09-15 12:27:11,964 - taichung-parser - DEBUG - Receive message u'{"raw": "PCFET0NUWVBFIGh0bWwgUFVCTElDICItLy9XM0MvL0RURCBYSFRNTCAxLjAgU3RyaWN0Ly9FTiIgImh0dHA6Ly93d3cudzMub3JnL1RSL3hodG1sMS9EVEQveGh0bWwxLXN0cmljdC5kdGQiPgo8aHRtbCB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94aHRtbCI+PGhlYWQ+CgkJPG1ldGEgaHR0cC1lcXVpdj0iY29udGVudC10eXBlIiBjb250ZW50PSJ0ZXh0L2h0bWw7IGNoYXJzZXQ9dXRmLTgiIC8+CgkJPHRpdGxlPuiHuuS4reW4guaUv+W6nOaVmeiCsuWxgOWFqOeQg+izh+ioiue2siAtIOe2sui3r+euoeeQhuezu+e1sTwvdGl0bGU+CQkKCQk8bGluayByZWw9InNob3J0Y3V0IGljb24iIGhyZWY9Ii9pbWFnZXMvbG9nby9mYXZpY29uLml'...
2015-09-15 12:27:13,230 - taichung-parser - ERROR - Bot has found a problem.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/bot.py", line 117, in start
    self.process()
  File "/usr/lib/python2.7/site-packages/intelmq-1.0.0-py2.7.egg/intelmq/bots/parsers/taichung/parser.py", line 63, in process
    event.add('event_description.text', description, sanitize=True)
  File "/usr/lib/python2.7/site-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/message.py", line 108, in add
    raise exceptions.InvalidValue(key, value, reason=valid_value[1])
InvalidValue: invalid value u'DNS \u653b\u64ca' (<type 'unicode'>) for key u'event_description.text'did not match printable ASCII characters.
2015-09-15 12:27:13,231 - taichung-parser - INFO - Bot will restart in 15 seconds.
2015-09-15 12:27:28,247 - taichung-parser - INFO - Bot woke up
2015-09-15 12:27:28,248 - taichung-parser - INFO - Trying to start processing again.
2015-09-15 12:27:28,248 - taichung-parser - DEBUG - Receiving Message.
2015-09-15 12:27:28,452 - taichung-parser - DEBUG - Receive message u'{"raw": "PCFET0NUWVBFIGh0bWwgUFVCTElDICItLy9XM0MvL0RURCBYSFRNTCAxLjAgU3RyaWN0Ly9FTiIgImh0dHA6Ly93d3cudzMub3JnL1RSL3hodG1sMS9EVEQveGh0bWwxLXN0cmljdC5kdGQiPgo8aHRtbCB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94aHRtbCI+PGhlYWQ+CgkJPG1ldGEgaHR0cC1lcXVpdj0iY29udGVudC10eXBlIiBjb250ZW50PSJ0ZXh0L2h0bWw7IGNoYXJzZXQ9dXRmLTgiIC8+CgkJPHRpdGxlPuiHuuS4reW4guaUv+W6nOaVmeiCsuWxgOWFqOeQg+izh+ioiue2siAtIOe2sui3r+euoeeQhuezu+e1sTwvdGl0bGU+CQkKCQk8bGluayByZWw9InNob3J0Y3V0IGljb24iIGhyZWY9Ii9pbWFnZXMvbG9nby9mYXZpY29uLml'...
2015-09-15 12:27:29,170 - taichung-parser - ERROR - Bot has found a problem.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/bot.py", line 117, in start
    self.process()
  File "/usr/lib/python2.7/site-packages/intelmq-1.0.0-py2.7.egg/intelmq/bots/parsers/taichung/parser.py", line 63, in process
    event.add('event_description.text', description, sanitize=True)
  File "/usr/lib/python2.7/site-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/message.py", line 108, in add
    raise exceptions.InvalidValue(key, value, reason=valid_value[1])
InvalidValue: invalid value u'DNS \u653b\u64ca' (<type 'unicode'>) for key u'event_description.text'did not match printable ASCII characters.
2015-09-15 12:27:29,171 - taichung-parser - INFO - Bot will restart in 15 seconds.
2015-09-15 12:27:44,186 - taichung-parser - INFO - Bot woke up
2015-09-15 12:27:44,187 - taichung-parser - INFO - Trying to start processing again.
2015-09-15 12:27:44,187 - taichung-parser - DEBUG - Receiving Message.
2015-09-15 12:27:44,410 - taichung-parser - DEBUG - Receive message u'{"raw": "PCFET0NUWVBFIGh0bWwgUFVCTElDICItLy9XM0MvL0RURCBYSFRNTCAxLjAgU3RyaWN0Ly9FTiIgImh0dHA6Ly93d3cudzMub3JnL1RSL3hodG1sMS9EVEQveGh0bWwxLXN0cmljdC5kdGQiPgo8aHRtbCB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94aHRtbCI+PGhlYWQ+CgkJPG1ldGEgaHR0cC1lcXVpdj0iY29udGVudC10eXBlIiBjb250ZW50PSJ0ZXh0L2h0bWw7IGNoYXJzZXQ9dXRmLTgiIC8+CgkJPHRpdGxlPuiHuuS4reW4guaUv+W6nOaVmeiCsuWxgOWFqOeQg+izh+ioiue2siAtIOe2sui3r+euoeeQhuezu+e1sTwvdGl0bGU+CQkKCQk8bGluayByZWw9InNob3J0Y3V0IGljb24iIGhyZWY9Ii9pbWFnZXMvbG9nby9mYXZpY29uLml'...
2015-09-15 12:27:45,204 - taichung-parser - ERROR - Bot has found a problem.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/bot.py", line 117, in start
    self.process()
  File "/usr/lib/python2.7/site-packages/intelmq-1.0.0-py2.7.egg/intelmq/bots/parsers/taichung/parser.py", line 63, in process
    event.add('event_description.text', description, sanitize=True)
  File "/usr/lib/python2.7/site-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/message.py", line 108, in add
    raise exceptions.InvalidValue(key, value, reason=valid_value[1])
InvalidValue: invalid value u'DNS \u653b\u64ca' (<type 'unicode'>) for key u'event_description.text'did not match printable ASCII characters.
2015-09-15 12:27:45,428 - taichung-parser - INFO - Disconnecting from source pipeline.
2015-09-15 12:27:45,429 - taichung-parser - INFO - Disconnecting from destination pipeline.
2015-09-15 12:27:45,429 - taichung-parser - INFO - Bot stopped.
2015-09-15 12:27:45,429 - taichung-parser - ERROR - Exiting.
2015-09-15 12:27:45,429 - taichung-parser - INFO - Bot stopped.
2015-09-15 12:27:45,429 - taichung-parser - ERROR - Exiting.
```

**Comment by sebix** [comment]
These are not encoding issues.

    InvalidValue: invalid value u'DNS \u653b\u64ca' (<type 'unicode'>) for key u'event_description.text'did not match printable ASCII characters.

Unicode chars are not allowed with current `harmonization.conf` for `event_description.text` (ascii only). This seems too strict, so I removed that restriction.
