### ISSUE TITLE
 collector_http_stream problem

### ISSUE THREAD

**Issue by dumar** [certtools/intelmq#332]
I have problem with  collector_http_stream it works, but then stops and i cant find the problem:

```
2015-09-18 08:48:18,743 - ---collector - DEBUG - Sending message.

2015-09-18 08:48:18,761 - ---collector - DEBUG - Sending message.

2015-09-18 08:48:18,789 - ---collector - ERROR - Bot has found a problem.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/bot.py", line 117, in start
    self.process()
  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/bots/collectors/http/collector_http_stream.py", line 19, in process
    self.conn.perform()
error: (23, 'Failed writing body (0 != 786)')
```

**Comment by SYNchroACK** [comment]
@dumar can you share which feed are you using?

**Comment by dumar** [comment]
Sorry for long reply. I would like not to at this time, but I was writing my own parser and tryed to use existing stream collector and this problem happened.

**Comment by sebix** [comment]
Does anyone know pages with http streams which we can use for tests? Content does not matter.
I never used and tested that module.

**Comment by dmth** [comment]
@dumar did you find a solution?

**Comment by wagner-certat** [comment]
No feedback. Please reopen if reproducible.
