### ISSUE TITLE
install: bug with setup.py or documentation

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#333]
Environment: Debian wheezy.
Should we require jessie? If so, this needs to be documented IMHO

```
aaron@intelmq ~/intelmq % sudo pip install -r REQUIREMENTS
Downloading/unpacking dnspython3>=1.12.0 (from -r REQUIREMENTS (line 1))
  Running setup.py egg_info for package dnspython3

Requirement already satisfied (use --upgrade to upgrade): geoip2>=0.5.1 in /usr/local/lib/python2.7/dist-packages/geoip2-0.5.1-py2.7.egg (from -r REQUIREMENTS (line 2))
Requirement already satisfied (use --upgrade to upgrade): imbox>=0.5.5 in /usr/local/lib/python2.7/dist-packages/imbox-0.5.5-py2.7.egg (from -r REQUIREMENTS (line 3))
Downloading/unpacking ipaddress>=1.0.14 (from -r REQUIREMENTS (line 4))
  Running setup.py egg_info for package ipaddress

Downloading/unpacking mock>=1.1.1 (from -r REQUIREMENTS (line 5))
  Running setup.py egg_info for package mock
    mock requires setuptools>=17.1. Aborting installation
    Complete output from command python setup.py egg_info:
    mock requires setuptools>=17.1. Aborting installation

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /home/aaron/intelmq/build/mock
Storing complete log in /root/.pip/pip.log
```

**Comment by aaronkaplan** [comment]
Further info: after upgrading to jessie, I now get 

```
~/intelmq % sudo pip install -r REQUIREMENTS

Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
```

**Comment by SYNchroACK** [comment]
It seems that you are using python2.7, not the default one, python 3.4

```
File "/usr/lib/python2.7/dist-packages/pip/__init__.py"
```

**Comment by aaronkaplan** [comment]
okay, got it. Sure, did not read the line below in UserGuide.md however,... even with python 2 and REQUIREMENTS2 I get:


```
% sudo pip2 install -r REQUIREMENTS2
Traceback (most recent call last):
  File "/usr/bin/pip2", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip2')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead
```

**Comment by aaronkaplan** [comment]
these error messsages seem like something went terribly wrong with the python installation of a VM.
Closing this issue and re-opening a new one for further error messages with python2.7
