### ISSUE TITLE
CleanMX Phishing Parser Bot - wrong keys

### ISSUE THREAD

**Issue by SYNchroACK** [certtools/intelmq#338]
```
2015-09-19 01:19:12,339 - cleanmx-phishing-parser - ERROR - Bot has found a problem.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/intelmq-1.0.0-py3.4.egg/intelmq/lib/bot.py", line 117, in start
    self.process()
  File "/usr/local/lib/python3.4/dist-packages/intelmq-1.0.0-py3.4.egg/intelmq/bots/parsers/cleanmx/parser_phishing.py", line 60, in process
    key = COLUMNS[key]
KeyError: None
2015-09-19 01:19:12,564 - cleanmx-phishing-parser - INFO - Last Correct Message(event): None.
2015-09-19 01:19:12,653 - cleanmx-phishing-parser - INFO - Current Message(event): {'time.observation': '2015-09-19T00:19:11+00:00', 'feed.name': 'CleanMX', 'raw': 'ImxpbmUiLCJpZCIsImZpcnN0dGltZSIsImxhc3R0aW1lIiwicGhpc2h0YW5rIiwidmlydXNuYW1lIiwidXJsIiwicmVjZW50IiwicmVzcG9uc2UiLCJpcCIsInJldmlldyIsImRvbWFpbiIsImNvdW50cnkiLCJzb3VyY2UiLCJlbWFpbCIsImluZXRudW0iLCJuZXRuYW1lIiwiZGRlc2NyIiwibnMxIiwibnMyIiwibnMzIiwibnM0IiwibnM1IgoiMSIsIjY1MDUyODciLCIyMDE1LTA5LTE5IDAxOjM3OjI4IiwiMTk3MC0wMS0wMSAwMTowMDowMCIsIiIsIiIsImh0dHA6Ly92ZXJpdHlpbnRlbC5jb20vY3NzL3BheXBhbC9iZj
```

**Comment by sebix** [comment]
What was the fix of this issue? Why did it even occur?

**Comment by SYNchroACK** [comment]
I think the problem was mentioned in #311 ...but ok, now this is the issue with the format problem.

**Comment by sebix** [comment]
This error occurs, when a value appears in a column without a header, e.g.:

    id,foo,bar
    1,"some","value","error"

Will provide a fix, which gives a warning in these cases, so we can have a more detailed look. The current file from cleanmx does not have these values.
