### ISSUE TITLE
BUG: postgresql output bot should not stop on error

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#351]
See issue #350 : when such an error occurs, the postgresql bot stops processing data.
It should continue processing the other data and not stop entirely.

From the log file:

```
2015-10-05 15:22:04,062 - postgresql-output - DEBUG - Query: u'INSERT INTO events ("source.geolocation.latitude", "feed.url", "source.geolocation.longitude", "event_description.text", "raw", "source.network", "source.registry", "source.as_name", "source.geolocation.city", "source.ip", "source.abuse_contact", "protocol.application", "time.observation", "source.geolocation.cc", "source.allocated", "classification.type", "source.asn", "feed.name") VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)' with values [43.801, u'https://lists.blocklist.de/lists/ssh.txt', 87.6005, u'IP reported as having run attacks on the service SSH', u'MTEwLjE1Mi4xNDUuMTg=', u'110.152.0.0/14', u'apnic', u'CHINANET-BACKBONE No.31,Jin-rong Street,CN', u'\xdcr\xfcmqi', u'110.152.145.18', u'cncert@cert.org.cn', u'ssh', u'2015-10-05T13:20:22+00:00', u'CN', u'2009-04-21T00:00:00+00:00', u'ids alert', 4134, u'BlockList.de']
2015-10-05 15:22:04,062 - postgresql-output - ERROR - Bot has found a problem.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/bot.py", line 95, in start
    self.process()
  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/bots/outputs/postgresql/output.py", line 56, in process
    self.cur.execute(query, values)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xdc' in position 0: ordinal not in range(128)
```

**Comment by sebix** [comment]
This is a configuration issue in the first place. Change the error-procedure to pass. The pass procedure will be default with #345.

**Comment by aaronkaplan** [comment]
okay, thanks . I thus close this issue.
