### ISSUE TITLE
BUG: dgarchive bot returns 401 even though the user/pass is correct

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#359]
```
2015-10-06 19:12:46,633 - fraunhofer-dga-collector - ERROR - Bot has found a problem.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/bot.py", line 95, in start
    self.process()
  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/bots/collectors/http/collector_http.py", line 62, in process
    ''.format(resp.status_code))
ValueError: HTTP response status code was 401.
2015-10-06 19:12:46,633 - fraunhofer-dga-collector - INFO - Last Correct Message(event): None.
2015-10-06 19:12:46,633 - fraunhofer-dga-collector - INFO - Current Message(event): None.
2015-10-06 19:12:46,635 - fraunhofer-dga-collector - INFO - Downloading report from https://dgarchive.caad.fkie.fraunhofer.de/today
2015-10-06 19:12:46,752 - fraunhofer-dga-collector - ERROR - Bot has found a problem.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/bot.py", line 95, in start
    self.process()
  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/bots/collectors/http/collector_http.py", line 62, in process
    ''.format(resp.status_code))
ValueError: HTTP response status code was 401.
2015-10-06 19:12:46,753 - fraunhofer-dga-collector - INFO - Last Correct Message(event): None.
2015-10-06 19:12:46,753 - fraunhofer-dga-collector - INFO - Current Message(event): None.
2015-10-06 19:12:46,754 - fraunhofer-dga-collector - INFO - Downloading report from https://dgarchive.caad.fkie.fraunhofer.de/today
2015-10-06 19:12:46,864 - fraunhofer-dga-collector - ERROR - Bot has found a problem.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/bot.py", line 95, in start
    self.process()
  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/bots/collectors/http/collector_http.py", line 62, in process
    ''.format(resp.status_code))
ValueError: HTTP response status code was 401.
2015-10-06 19:12:46,864 - fraunhofer-dga-collector - INFO - Last Correct Message(event): None.
2015-10-06 19:12:46,865 - fraunhofer-dga-collector - INFO - Current Message(event): None.
2015-10-06 19:12:46,866 - fraunhofer-dga-collector - INFO - Disconnecting from source pipeline.
2015-10-06 19:12:46,866 - fraunhofer-dga-collector - INFO - Disconnecting from destination pipeline.
2015-10-06 19:12:46,866 - fraunhofer-dga-collector - INFO - Bot stopped.
2015-10-06 19:12:46,866 - fraunhofer-dga-collector - ERROR - Exiting.
```

**Comment by aaronkaplan** [comment]
problem identified: the paramters must be http_username and http_password...

**Comment by sebix** [comment]
Yes, this has been changed in #344 by @SYNchroACK

**Comment by aaronkaplan** [comment]
On Oct 6, 2015, at 7:40 PM, Sebastian <notifications@github.com> wrote:


> Yes, this has been changed in #344 by @SYNchroACK
> 

okay. Anyway, I fixed it now. See the latest commit.
