### ISSUE TITLE
n6stomp parser malware.name issues

### ISSUE THREAD

**Issue by robcza** [certtools/intelmq#412]
Having problem with parsing malware.name in n6stomp. malware.name property seems a bit strict to me as I'm not aware of any standard in naming malware and have seen a lot of awkward strings that does not comply with this ```"regex": "^[-a-z0-9_ ]+$"```

Should we change the parser or loosen the regex?

```
2015-12-11 10:50:51,313 - n6stomp-parser - ERROR - Bot has found a problem.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/bot.py", line 97, in start
    self.process()
  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/bots/parsers/n6/parser_n6stomp.py", line 120, in process
    event.add("malware.name", dict_report["name"], sanitize=True)
  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/message.py", line 137, in add
    raise exceptions.InvalidValue(key, value, reason=valid_value[1])
InvalidValue: invalid value u'multiple-malware citadel:report' (<type 'unicode'>) for key u'malware.name' regex did not match.
```

**Comment by aaronkaplan** [comment]
> On 11 Dec 2015, at 12:02, Robert Šefr <notifications@github.com> wrote:
> 
> Having problem with parsing malware.name in n6stomp. malware.name property seems a bit strict to me as I'm not aware of any standard in naming malware and have seen a lot of awkward strings that does not comply with this "regex": "^[-a-z0-9_ ]+$"
> 
> Should we change the parser or loosen the regex?

fine for me. Please make a proposal what it should be :)

**Comment by mauroasilva** [comment]
Yeah I think we should loosen the regex... There are a few names that have dots and such.
