### ISSUE TITLE
malwaredomainlistparser: not unicode compatible

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#436]
Seems like the malwaredomain list parser barfs on non ascii characters.
Pls. fix. Thanks!

```

2016-01-13 14:59:06,743 - malware-domain-list-parser - DEBUG - Receive message u'{"feed.accuracy": 100.0, "feed.url": "http://www.malwaredomainlist.com/updatescsv.php", "time.observation": "2015-12-28T17:11:05+00:00", "raw": "IjIwMTUvMTIvMjhfMTc6MDciLCJ3d3cuc295dGVyLnBsLyIsIjEwOS45NS4xNTIuMTg3IiwidjE4Ny5jMy5kaG9zdGluZy5wbC4iLCJjb21wcm9taXNlZCBzaXRlIGxlYWRzIHRvIEFuZ2xlciBFSyIsImtvbnRha3RAbmF6d2EucGwiLCI0ODg5NiINCiIyMDE1LzEyLzI2XzE1OjUwIiwic2hlYW43Ni5uZXQvbWluZS9jYXN0bmV3L2xvZ2luLnBocCIsIjE2Ny4xMTQuMjA4LjIyOSIsInNlcnZlci5nZW5uZXR3b3Jrcy5pbi4iLCJLZXliYXNlIGtleWxvZ2dlciB3ZWIgcGF'...
2016-01-13 14:59:06,747 - malware-domain-list-parser - DEBUG - Sending message.
2016-01-13 14:59:06,751 - malware-domain-list-parser - DEBUG - Sending message.
2016-01-13 14:59:06,761 - malware-domain-list-parser - DEBUG - Sending message.
2016-01-13 14:59:06,766 - malware-domain-list-parser - DEBUG - Sending message.
2016-01-13 14:59:06,770 - malware-domain-list-parser - DEBUG - Sending message.
2016-01-13 14:59:06,773 - malware-domain-list-parser - DEBUG - Sending message.
2016-01-13 14:59:06,779 - malware-domain-list-parser - DEBUG - Sending message.
2016-01-13 14:59:06,783 - malware-domain-list-parser - DEBUG - Sending message.
2016-01-13 14:59:06,788 - malware-domain-list-parser - DEBUG - Sending message.
2016-01-13 14:59:06,800 - malware-domain-list-parser - DEBUG - Sending message.
2016-01-13 14:59:06,805 - malware-domain-list-parser - DEBUG - Sending message.
2016-01-13 14:59:06,812 - malware-domain-list-parser - DEBUG - Sending message.
2016-01-13 14:59:06,814 - malware-domain-list-parser - ERROR - Bot has found a problem.
Traceback (most recent call last):
  File "intelmq/lib/bot.py", line 106, in start
    self.process()
  File "/home/aaron/intelmq/intelmq/bots/parsers/malwaredomainlist/parser.py", line 42, in process
    for row in csv.reader(StringIO(raw_report)):
  File "/usr/local/lib/python2.7/dist-packages/unicodecsv-0.9.4-py2.7.egg/unicodecsv/__init__.py", line 106, in next
    row = self.reader.next()
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 125: ordinal not in range(128)
2016-01-13 14:59:06,817 - malware-domain-list-parser - INFO - Last Correct Message(event): None.
2016-01-13 14:59:06,819 - malware-domain-list-parser - INFO - Current Message(event): {u'raw': u'IjIwMTUvMTIvMjhfMTc6MDciLCJ3d3cuc295dGVyLnBsLyIsIjEwOS45NS4xNTIuMTg3IiwidjE4Ny5jMy5kaG9zdGluZy5wbC4iLCJjb21wcm9taXNlZCBzaXRlIGxlYWRzIHRvIEFuZ2xlciBFSyIsImtvbnRha3RAbmF6d2EucGwiLCI0ODg5NiINCiIyMDE1LzEyLzI2XzE1OjUwIiwic2hlYW43Ni5uZXQvbWluZS9jYXN0bmV3L2xvZ2luLnBocCIsIjE2Ny4xMTQuMjA4LjIyOSIsInNlcnZlci5nZW5uZXR3b3Jrcy5pbi4iLCJLZXliYXNlIGtleWxvZ2dlciB3ZWIgcGFuZWwiLCJSZWdpc3RyYW50IGh1YXllYWh0YXhAZ21haWwuY29tIiwiMTYyNzYiDQoiMjAxNS8xMi8yNl8xNTo1MCIsImx1Y2lhbm93ZWJwZWFjZ
```

**Comment by sebix** [comment]
I would need the original data to make reliable tests, so please don't remove the entry from the dumpfile until Tuesday.

**Comment by aaronkaplan** [comment]
> On 13 Jan 2016, at 15:17, Sebastian <notifications@github.com> wrote:
> 
> I would need the original data to make reliable tests, so please don't remove the entry from the dumpfile until Tuesday.
> 

sure. I'll keep a copy of it.
However, pls take a look at the base64 raw values. I don't see any non-ascii chars there. Which is weird.

**Comment by sebix** [comment]
The logs show at most 500 characters per message, everything else is
stripped.

**Comment by aaronkaplan** [comment]
> On 13 Jan 2016, at 15:41, Sebastian <notifications@github.com> wrote:
> 
> The logs show at most 500 characters per message, everything else is
> stripped.
> 

See my private mail. I found the non-ascii character responsible for the trouble :)
