### ISSUE TITLE
bot: phishtank collector issue

### ISSUE THREAD

**Issue by shirio57** [certtools/intelmq#454]
Hello,

I have a problem with phishtank collector, when I tried in the browser, everything works well but the collector crash

Do you have an idea why this issue occured ?

Here is the traceback:

```
2016-02-25 09:50:20,257 - collector-phishtank - ERROR - Bot has found a problem.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/intelmq-1.0.0-py3.4.egg/intelmq/lib/bot.py", line 102, in start
    self.process()
  File "/usr/local/lib/python3.4/dist-packages/intelmq-1.0.0-py3.4.egg/intelmq/bots/collectors/http/collector_http.py", line 63, in process
    verify=self.http_verify_cert)
  File "/usr/local/lib/python3.4/dist-packages/requests-2.5.1-py3.4.egg/requests/api.py", line 65, in get
    return request('get', url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests-2.5.1-py3.4.egg/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests-2.5.1-py3.4.egg/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests-2.5.1-py3.4.egg/requests/sessions.py", line 610, in send
    r.content
  File "/usr/local/lib/python3.4/dist-packages/requests-2.5.1-py3.4.egg/requests/models.py", line 730, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/local/lib/python3.4/dist-packages/requests-2.5.1-py3.4.egg/requests/models.py", line 655, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/local/lib/python3.4/dist-packages/requests-2.5.1-py3.4.egg/requests/packages/urllib3/response.py", line 256, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python3.4/dist-packages/requests-2.5.1-py3.4.egg/requests/packages/urllib3/response.py", line 186, in read
    data = self._fp.read(amt)
  File "/usr/lib/python3.4/http/client.py", line 537, in read
    return super(HTTPResponse, self).read(amt)
  File "/usr/lib/python3.4/http/client.py", line 566, in readinto
    return self._readinto_chunked(b)
  File "/usr/lib/python3.4/http/client.py", line 658, in _readinto_chunked
    n = self._safe_readinto(mvb)
  File "/usr/lib/python3.4/http/client.py", line 715, in _safe_readinto
    n = self.fp.readinto(mvb)
  File "/usr/lib/python3.4/socket.py", line 374, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
```

**Comment by aaronkaplan** [comment]
We tested - it's not the phishtank URL or key. As mentioned, if used directly in the browser, it works.
Could it be the user-agent?

**Comment by shirio57** [comment]
I have de default settings:
 - using collector_http
 - user agent: "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36"

**Comment by aaronkaplan** [comment]
@shirio57 is this problem now solved? Can we close this issue? Thanks for your feedback!

**Comment by shirio57** [comment]
yes it is closed, it was a configuration issue coming from our side, it works again now
