### ISSUE TITLE
parsing error cleanmx parser

### ISSUE THREAD

**Issue by pedromreis** [certtools/intelmq#490]
Is there any way to configure intelmq to skip the message on error?

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/intelmq-1.0.0.dev4-py3.4.egg/intelmq/lib/bot.py", line 102, in start
    self.process()
  File "/usr/lib/python3.4/site-packages/intelmq-1.0.0.dev4-py3.4.egg/intelmq/bots/parsers/cleanmx/parser_phishing.py", line 73, in process
    event.add(key, value)
  File "/usr/lib/python3.4/site-packages/intelmq-1.0.0.dev4-py3.4.egg/intelmq/lib/message.py", line 125, in add
    raise exceptions.InvalidValue(key, value, reason=valid_value[1])
intelmq.lib.exceptions.InvalidValue: invalid value 'cua (credit unio' (<class 'str'>) for key 'malware.name' regex did not match.
2016-04-18 11:34:37,882 - cleanmx-phishing-parser - INFO - Last Correct Message(event): None.
2016-04-18 11:34:38,077 - cleanmx-phishing-parser - INFO - Current Message(event): {'raw': 'ImxpbmUiLCJpZCIsImZpcnN0dGltZSIsImxhc3R0aW1lIiwicGhpc2h0YW5rIiwidmlydXNuYW1lIiwidXJsIiwicmVjZW50IiwicmVzcG9uc2UiLCJpcCIsInJldmlldyIsImRvbWFpbiIsImNvdW50cnkiLCJzb3VyY2UiLCJlbWFpbCIsImluZXRudW0iLCJuZXRuYW1lIiwiZGRlc2NyIiwibnMxIiwibnMyIiwibnMzIiwibnM0IiwibnM1IgoiMSIsIjc1NTg3OTAiLCIyMDE2LTA0LTE3IDIwOjQ2OjA0IiwiMTk3MC0wMS0wMSAwMTowMDowMCIsIiIsIkNhcmlwYXJtYSBDcmVkaXQiLCJodHRwOi8vZGltYXktbGVkLmNvbS9lcnJvcnMvZGVmYXVsdC9hZ3JpY29sZS5mci9sb2dpbi8iLCJ1cCIsImFsaXZlIiwiMTU1LjE
2016-04-18 11:34:38,082 - cleanmx-phishing-parser - INFO - Bot will restart in 15 seconds.
```

**Comment by sebix** [comment]
Either in configuration: https://github.com/certtools/intelmq/wiki/User-Guide#error-handling
Or in the code using a try-except clause: https://docs.python.org/3/tutorial/errors.html

**Comment by sebix** [comment]
related: #402
