### ISSUE TITLE
How to test.. the tests?

### ISSUE THREAD

**Issue by pedromreis** [certtools/intelmq#491]
python3 test_parser.py 
Traceback (most recent call last):
  File "test_parser.py", line 5, in <module>
    import intelmq.lib.test as test
  File "/usr/local/lib/python3.4/dist-packages/intelmq-1.0.0.dev4-py3.4.egg/intelmq/lib/test.py", line 13, in <module>
    import mock
ImportError: No module named 'mock'

tested some others, all the same error.

**Comment by pedromreis** [comment]
ok got the "mock" thing working.

I don't understand the test results:

382, in assertMessageEqual
    del expected['time.observation']
KeyError: 'time.observation'

and

AssertionError: Regex didn't match: 'BitsightParserBot initialized with id test-bot and version [0-9.]{5} \\([a-zA-Z, 0-9:]+\\).' not found in 'BitsightParserBot initialized with id test-bot and version 3.4.3+ (default, Oct 14 2015, 16:03:50).'

full output:

Now, executing:  python3 test_parser.py 
...E.F......
======================================================================
ERROR: test_event (__main__.TestBitsightParserBot)
Test if correct Event has been produced.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_parser.py", line 25, in test_event
    self.assertMessageEqual(0, EXAMPLE_EVENT)
  File "/usr/local/lib/python3.4/dist-packages/intelmq-1.0.0.dev4-py3.4.egg/intelmq/lib/test.py", line 382, in assertMessageEqual
    del expected['time.observation']
KeyError: 'time.observation'

======================================================================
FAIL: test_log_init (__main__.TestBitsightParserBot)
Test if bot logs initialized message.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/intelmq-1.0.0.dev4-py3.4.egg/intelmq/lib/test.py", line 214, in test_log_init
    self.bot_id), "INFO")
  File "/usr/local/lib/python3.4/dist-packages/intelmq-1.0.0.dev4-py3.4.egg/intelmq/lib/test.py", line 347, in assertLoglineMatches
    self.assertRegex(fields["message"], pattern)
AssertionError: Regex didn't match: 'BitsightParserBot initialized with id test-bot and version [0-9.]{5} \\([a-zA-Z, 0-9:]+\\).' not found in 'BitsightParserBot initialized with id test-bot and version 3.4.3+ (default, Oct 14 2015, 16:03:50).'

----------------------------------------------------------------------
Ran 12 tests in 0.075s

FAILED (failures=1, errors=1)

---------------------------------- code ------------------------------
 -*- coding: utf-8 -*-

import unittest

import intelmq.lib.test as test
from intelmq.bots.parsers.bitsight.parser import BitsightParserBot

EXAMPLE_REPORT = {"feed.name": "BitSight", "__type": "Report", "raw": "eyJfdHMiOjE0NjA5ODQ5MzksImVudiI6eyJyZXF1ZXN0X21ldGhvZCI6IkdFVCIsInNlcnZlcl9hZGRyIjoiMTk1LjIyLjI4LjE5NiIsInNlcnZlcl9wb3J0IjoiODAiLCJyZW1vdGVfYWRkciI6Ijg1LjI0My4xMjkuMTg0IiwicmVtb3RlX3BvcnQiOiI1MjA4NiIsInNlcnZlcl9uYW1lIjoiY3lzdGFseDAyLmNvbSJ9LCJ0cm9qYW5mYW1pbHkiOiJDYXJ1ZmF4IiwiX2dlb19lbnZfcmVtb3RlX2FkZHIiOnsiY291bnRyeV9uYW1lIjoiUG9ydHVnYWwifX0=", "feed.accuracy": 100.0, "feed.url": "http://alerts.bitsighttech.com:8080/stream?", "time.observation": "2016-04-18T13:08:59+00:00"}

EXAMPLE_EVENT = {"extra": "{\"request_method\": \"GET\"}", "source": {"port": 52086, "ip": "85.243.129.184"}, "event_description": {"text": "Sinkhole attempted connection"}, "feed": {"name": "BitSight", "accuracy": 100.0, "url": "http://alerts.bitsighttech.com:8080/stream?"}, "raw": "ZXlKZmRITWlPakUwTmpBNU9EUTVNemtzSW1WdWRpSTZleUp5WlhGMVpYTjBYMjFsZEdodlpDSTZJa2RGVkNJc0luTmxjblpsY2w5aFpHUnlJam9pTVRrMUxqSXlMakk0TGpFNU5pSXNJbk5sY25abGNsOXdiM0owSWpvaU9EQWlMQ0p5WlcxdmRHVmZZV1JrY2lJNklqZzFMakkwTXk0eE1qa3VNVGcwSWl3aWNtVnRiM1JsWDNCdmNuUWlPaUkxTWpBNE5pSXNJbk5sY25abGNsOXVZVzFsSWpvaVkzbHpkR0ZzZURBeUxtTnZiU0o5TENKMGNtOXFZVzVtWVcxcGJIa2lPaUpEWVhKMVptRjRJaXdpWDJkbGIxOWxiblpmY21WdGIzUmxYMkZrWkhJaU9uc2lZMjkxYm5SeWVWOXVZVzFsSWpvaVVHOXlkSFZuWVd3aWZYMD0=", "time": {"observation": "2016-04-18T13:08:59+00:00", "source": "2016-04-18T13:08:59+00:00"}, "malware": {"name": "carufax"}, "destination": {"fqdn": "cystalx02.com", "port": 80, "ip": "195.22.28.196"}, "classification": {"type": "malware"}}

class TestBitsightParserBot(test.BotTestCase, unittest.TestCase):
    @classmethod
    def set_bot(cls):
        cls.bot_reference = BitsightParserBot
        cls.default_input_message = EXAMPLE_REPORT

    def test_event(self):
        """ Test if correct Event has been produced. """
        self.run_bot()
        self.assertMessageEqual(0, EXAMPLE_EVENT)
#
#
#

if __name__ == '__main__':
    unittest.main()

**Comment by pedromreis** [comment]
I think I figured it out... +- some error still, but the same in all bots...
