### ISSUE TITLE
New intelmqctl command interface partly broken

### ISSUE THREAD

**Issue by swilde** [certtools/intelmq#506]
With the new commandline interface of intelmqctl variouse actions are
broken.  Here are some examples I found so far:

```
$ intelmqctl list
Traceback (most recent call last):
  File "/usr/bin/intelmqctl", line 9, in <module>
    load_entry_point('intelmq==1.0.0.dev4', 'console_scripts', 'intelmqctl')()
  File "/usr/lib/python3/dist-packages/intelmq/bin/intelmqctl.py", line 522, in main
    x.run()
  File "/usr/lib/python3/dist-packages/intelmq/bin/intelmqctl.py", line 262, in run
    if self.args.parameter[0] not in ['bots', 'queues']:
IndexError: list index out of range
```
(this should display usage information IMO as an argument to list is
missing)

```
$ intelmqctl start
[...]
$ intelmqctl status
intelmqctl: file-output is running.
intelmqctl: malware-domain-list-collector is running.
intelmqctl: malware-domain-list-parser is running.
$ intelmqctl status file-output
intelmqctl: ['file-output'] is stopped.
```
(note: the status for a specific bot says "stopped", the bot is
running though.)

```
$ intelmqctl start file-output
intelmqctl: Starting ['file-output']...
Traceback (most recent call last):
  File "/usr/bin/intelmqctl", line 9, in <module>
    load_entry_point('intelmq==1.0.0.dev4', 'console_scripts', 'intelmqctl')()
  File "/usr/lib/python3/dist-packages/intelmq/bin/intelmqctl.py", line 522, in main
    x.run()
  File "/usr/lib/python3/dist-packages/intelmq/bin/intelmqctl.py", line 250, in run
    results = call_method(self.args.parameter)
  File "/usr/lib/python3/dist-packages/intelmq/bin/intelmqctl.py", line 308, in bot_start
    module = self.startup[bot_id]['module']
TypeError: unhashable type: 'list'
```
(Starting single bots doesn't work at all)

**Comment by aaronkaplan** [comment]
On Tue, May 10, 2016 at 01:15:53AM -0700, Sascha Wilde wrote:
> With the new commandline interface of intelmqctl variouse actions are
> broken.  Here are some examples I found so far:

Thanks for the report.

**Comment by sebix** [comment]
Fixed in master. Basically a `[0]` was missing :)
