### ISSUE TITLE
intelmqctl: error message for list bots

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#514]
Hi please take a look. Something broke.

```
$ intelmqctl list bots
(...)
Description: Turris Greylist Parser is the bot responsible to parse the report and sanitize the information.
Traceback (most recent call last):
  File "/usr/local/bin/intelmqctl", line 9, in <module>
    load_entry_point('intelmq==1.0.0.dev4', 'console_scripts', 'intelmqctl')()
  File "/usr/local/lib/python3.4/dist-packages/intelmq/bin/intelmqctl.py", line 526, in main
    x.run()
  File "/usr/local/lib/python3.4/dist-packages/intelmq/bin/intelmqctl.py", line 269, in run
    results = call_method()
  File "/usr/local/lib/python3.4/dist-packages/intelmq/bin/intelmqctl.py", line 399, in list_bots
    "".format(bot_id, self.startup[bot_id]['description']))
KeyError: 'description'

**Comment by sebix** [comment]
One of your configured bots does not have a description (see `startup.conf`). But the tool should not fail.
