### ISSUE TITLE
installation upgrade sets wrong perms on /opt/intelmq/var/log

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#515]
Installation upgrade:

```
% sudo -HE pip3 install --upgrade  .                                                                                                          master
Processing /home/aaron/intelmq
Requirement already up-to-date: dnspython3>=1.11.1 in /usr/local/lib/python3.4/dist-packages (from intelmq==1.0.0.dev4)
Requirement already up-to-date: psutil>=1.2.1 in /usr/local/lib/python3.4/dist-packages (from intelmq==1.0.0.dev4)
Requirement already up-to-date: python-dateutil>=2.0 in /usr/local/lib/python3.4/dist-packages (from intelmq==1.0.0.dev4)
Requirement already up-to-date: python-termstyle>=0.1.10 in /usr/lib/python3/dist-packages (from intelmq==1.0.0.dev4)
Requirement already up-to-date: pytz>=2014.1 in /usr/local/lib/python3.4/dist-packages (from intelmq==1.0.0.dev4)
Requirement already up-to-date: redis>=2.10.3 in /usr/local/lib/python3.4/dist-packages (from intelmq==1.0.0.dev4)
Requirement already up-to-date: requests>=2.2.0 in /usr/local/lib/python3.4/dist-packages (from intelmq==1.0.0.dev4)
Requirement already up-to-date: six>=1.5 in /usr/local/lib/python3.4/dist-packages (from python-dateutil>=2.0->intelmq==1.0.0.dev4)
Installing collected packages: intelmq
  Found existing installation: intelmq 1.0.0.dev4
    Uninstalling intelmq-1.0.0.dev4:
      Successfully uninstalled intelmq-1.0.0.dev4
  Running setup.py install for intelmq ... done
Successfully installed intelmq-1.0.0.dev4


 % sudo -Eu intelmq /opt/intelmq/bin/intelmqctl --botnet stop                                                                                   master
Traceback (most recent call last):
  File "/opt/intelmq/bin/intelmqctl", line 540, in <module>
    x = IntelMQContoller()
  File "/opt/intelmq/bin/intelmqctl", line 157, in __init__
    logger = utils.log('intelmqctl', log_level='DEBUG')
  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0.dev4-py2.7.egg/intelmq/lib/utils.py", line 251, in log
    handler = logging.FileHandler("%s/%s.log" % (log_path, name))
  File "/usr/lib/python2.7/logging/__init__.py", line 911, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 936, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: u'/opt/intelmq/var/log/intelmqctl.log'


ls -ald /opt/intelmq/var/log
drwxr-xr-x 2 root root 4096 May 11 21:55 /opt/intelmq/var/log
```

This is repeatable. Whenever you pip install , the ownership does not get set correctly.
Hence, nothing will start anymore.

**Comment by sebix** [comment]
It's even documented :) https://github.com/certtools/intelmq/blob/master/docs/User-Guide.md#upgrade

I'm not sure if you should put the `chown` command into the `setup.py`...

**Comment by aaronkaplan** [comment]
On Wed, May 11, 2016 at 01:34:14PM -0700, Sebastian wrote:
> It's even documented :) https://github.com/certtools/intelmq/blob/master/docs/User-Guide.md#upgrade
> 

That's true.

But ... I often intentionally take the role of "stupid tester" and
report things which look inconsistent to me.

> I'm not sure if you should put the `chown` command into the `setup.py`...

hmmm... maybe. 
Anyway, a deb or yum package should fix this issue.

**Comment by sebix** [comment]
fixed by packages (either fixed or won't fix, depends on the type of packages you want) -> closing
