### ISSUE TITLE
asn_lookup bot can't parse data

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#516]
Either something in the documentation on [https://intelmq.org/2016/04/27/asn-lookup-made-easy.html](https://intelmq.org/2016/04/27/asn-lookup-made-easy.html) or in the asn_lookup bot is broken.

While following the instructions from https://intelmq.org/2016/04/27/asn-lookup-made-easy.html and installing the ipasn database, and starting the asn_lookup bot, I came across the following error message:

```
# tail -f asn-lookup-expert.log
2016-05-11 22:01:34,946 - asn-lookup-expert - DEBUG - Loading Harmonization configuration.
2016-05-11 22:01:35,558 - asn-lookup-expert - ERROR - Bot initialization failed.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0.dev4-py2.7.egg/intelmq/lib/bot.py", line 73, in __init__
    self.init()
  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0.dev4-py2.7.egg/intelmq/bots/experts/asn_lookup/expert.py", line 17, in init
    self.database = pyasn.pyasn(self.parameters.database)
  File "/usr/local/lib/python2.7/dist-packages/pyasn/__init__.py", line 56, in __init__
    self._records = self.radix.load_ipasndb(ip_asn_db_file, binary=binary)
RuntimeError: Error while parsing/adding IPASN database (mode: text, record: 614772)!

```

I am using:
% pip3 list | grep pyasn
pyasn (1.5.0b7)

@dmth : did you test this before submitting it? If so, I wonder what the differences to our setup are.

**Comment by aaronkaplan** [comment]
Further comments: it is indeed the data from RIPE stats which can not be parsed by pyasn!
This is a bug report at pyasn.

Proof:
`` pyasn_download.py --latest
-> results in file: rib.20160511.2000.bz2

% pyasn_util_convert.py --single rib.20160511.2000.bz2 /tmp/ipasn.dat
MRT RIB log importer 1.5.0b7
parse_mrt_file(): starting  parse for MrtTable(ts:1462996801, type:13, sub-type:1, data-len:866, seq:None, prefix:None)
  MRT record 100000 @10s
  MRT record 200000 @20s
  MRT record 300000 @30s
  MRT record 400000 @40s
  MRT record 500000 @50s
  MRT record 600000 @60s
IPASN database saved (641676 prefixes)
```
-> works!

@dmth: Sorry you **have** to **test** things before you document/commit them.

**Comment by dmth** [comment]
Thank you for reporting this. We tested the bot with Python3, seems like you are using 2.7?

/usr/local/lib/python2.7/dist-packages/pyasn

**Comment by aaronkaplan** [comment]
On Thu, May 12, 2016 at 12:30:02AM -0700, Dustin Demuth wrote:
> Thank you for reporting this. We tested the bot with Python3, seems like you are using 2.7?
> 
> /usr/local/lib/python2.7/dist-packages/pyasn
> 

That would be a stupid mistake on my side :)

Okay, I'll re-inspect this and possibly will have to correct my claim.
Thx!
a.

**Comment by dmth** [comment]
I just reinstalled intelmq from most recent packages  and gave my tutorial from intelmq.org another short. Seems to work fine.

```
2016-05-12 09:11:01,962 - asn-lookup-expert - INFO - ASNLookupExpertBot initialized with id asn-lookup-expert and version 3.4.3 (default, Oct 14 2015, 20:28:29).
2016-05-12 09:11:01,963 - asn-lookup-expert - DEBUG - Loading defaults configuration.
2016-05-12 09:11:01,963 - asn-lookup-expert - DEBUG - Defaults configuration: parameter 'accuracy' loaded  with value '100'.
2016-05-12 09:11:01,963 - asn-lookup-expert - DEBUG - Defaults configuration: parameter 'logging_syslog' loaded  with value '/dev/log'.
2016-05-12 09:11:01,963 - asn-lookup-expert - DEBUG - Defaults configuration: parameter 'error_procedure' loaded  with value 'pass'.
2016-05-12 09:11:01,963 - asn-lookup-expert - DEBUG - Defaults configuration: parameter 'destination_pipeline_port' loaded  with value '6379'.
2016-05-12 09:11:01,963 - asn-lookup-expert - DEBUG - Defaults configuration: parameter 'error_retry_delay' loaded  with value '15'.
2016-05-12 09:11:01,963 - asn-lookup-expert - DEBUG - Defaults configuration: parameter 'http_user_agent' loaded  with value 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36'.
2016-05-12 09:11:01,964 - asn-lookup-expert - DEBUG - Defaults configuration: parameter 'error_dump_message' loaded  with value 'True'.
2016-05-12 09:11:01,964 - asn-lookup-expert - DEBUG - Defaults configuration: parameter 'error_log_message' loaded  with value 'True'.
2016-05-12 09:11:01,964 - asn-lookup-expert - DEBUG - Defaults configuration: parameter 'destination_pipeline_db' loaded  with value '2'.
2016-05-12 09:11:01,964 - asn-lookup-expert - DEBUG - Defaults configuration: parameter 'load_balance' loaded  with value 'False'.
2016-05-12 09:11:01,964 - asn-lookup-expert - DEBUG - Defaults configuration: parameter 'http_verify_cert' loaded  with value 'True'.
2016-05-12 09:11:01,964 - asn-lookup-expert - DEBUG - Defaults configuration: parameter 'source_pipeline_port' loaded  with value '6379'.
2016-05-12 09:11:01,964 - asn-lookup-expert - DEBUG - Defaults configuration: parameter 'logging_handler' loaded  with value 'file'.
2016-05-12 09:11:01,964 - asn-lookup-expert - DEBUG - Defaults configuration: parameter 'source_pipeline_db' loaded  with value '2'.
2016-05-12 09:11:01,965 - asn-lookup-expert - DEBUG - Defaults configuration: parameter 'error_max_retries' loaded  with value '3'.
2016-05-12 09:11:01,965 - asn-lookup-expert - DEBUG - Defaults configuration: parameter 'error_log_exception' loaded  with value 'True'.
2016-05-12 09:11:01,965 - asn-lookup-expert - DEBUG - Defaults configuration: parameter 'rate_limit' loaded  with value '0'.
2016-05-12 09:11:01,965 - asn-lookup-expert - DEBUG - Defaults configuration: parameter 'http_proxy' loaded  with value 'None'.
2016-05-12 09:11:01,965 - asn-lookup-expert - DEBUG - Defaults configuration: parameter 'destination_pipeline_host' loaded  with value '127.0.0.1'.
2016-05-12 09:11:01,965 - asn-lookup-expert - DEBUG - Defaults configuration: parameter 'broker' loaded  with value 'redis'.
2016-05-12 09:11:01,965 - asn-lookup-expert - DEBUG - Defaults configuration: parameter 'source_pipeline_host' loaded  with value '127.0.0.1'.
2016-05-12 09:11:01,965 - asn-lookup-expert - DEBUG - Defaults configuration: parameter 'http_ssl_proxy' loaded  with value 'None'.
2016-05-12 09:11:01,965 - asn-lookup-expert - DEBUG - Loading system configuration
2016-05-12 09:11:01,966 - asn-lookup-expert - DEBUG - System configuration: parameter 'logging_level' loaded  with value 'DEBUG'.
2016-05-12 09:11:01,966 - asn-lookup-expert - DEBUG - System configuration: parameter 'logging_path' loaded  with value '/opt/intelmq/var/log/'.
2016-05-12 09:11:01,966 - asn-lookup-expert - INFO - Bot is starting.
2016-05-12 09:11:01,966 - asn-lookup-expert - DEBUG - Loading runtime configuration
2016-05-12 09:11:01,966 - asn-lookup-expert - DEBUG - Runtime configuration: parameter 'database' loaded with value '/tmp/ipasn.dat'.
2016-05-12 09:11:01,966 - asn-lookup-expert - DEBUG - Loading pipeline configuration
2016-05-12 09:11:01,967 - asn-lookup-expert - DEBUG - Pipeline configuration: parameter 'source-queue' loaded with the value 'asn-lookup-expert-queue'.
2016-05-12 09:11:01,967 - asn-lookup-expert - DEBUG - Pipeline configuration: parameter'destination-queues' loaded with the value 'file-output-queue'.
2016-05-12 09:11:01,967 - asn-lookup-expert - DEBUG - Loading Harmonization configuration.
2016-05-12 09:11:02,672 - asn-lookup-expert - INFO - Bot starts processings.
2016-05-12 09:11:02,672 - asn-lookup-expert - INFO - Loading source pipeline.
2016-05-12 09:11:02,673 - asn-lookup-expert - INFO - Loading source queue.
2016-05-12 09:11:02,673 - asn-lookup-expert - INFO - Source queue loaded asn-lookup-expert-queue.
2016-05-12 09:11:02,673 - asn-lookup-expert - INFO - Connected to source queue.
2016-05-12 09:11:02,673 - asn-lookup-expert - INFO - Loading destination pipeline.
2016-05-12 09:11:02,673 - asn-lookup-expert - INFO - Loading destination queues.
2016-05-12 09:11:02,673 - asn-lookup-expert - INFO - Destination queues loaded ['file-output-queue'].
2016-05-12 09:11:02,674 - asn-lookup-expert - INFO - Connected to destination queues.
2016-05-12 09:11:02,674 - asn-lookup-expert - INFO - Pipeline ready.
2016-05-12 09:11:02,674 - asn-lookup-expert - INFO - Start processing.
2016-05-12 09:11:02,674 - asn-lookup-expert - DEBUG - Receiving Message.
2016-05-12 09:11:03,299 - asn-lookup-expert - DEBUG - Receive message '{"source.asn": <SNIP>'...
2016-05-12 09:11:03,300 - asn-lookup-expert - DEBUG - Sending messag
```

I modified the "malwaredomaionlistparser" in order to NOT include ASN-Data. Still Output contains data on the AS and the Network.

**Comment by sebix** [comment]
Works for me to.
