### ISSUE TITLE
Pipeline failed - AttributeError: 'NoneType' object has no attribute 'decode'

### ISSUE THREAD

**Issue by MAHDTech** [certtools/intelmq#538]
Can anyone else confirm this issue:

To re-produce, create a simple bot configuration
1. Malc0de IP Collector
2. Malc0de IP Parser
3. File Output Bot
4. Start BotNet

```
Pipeline failed.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/intelmq-1.0.0.dev4-py3.4.egg/intelmq/lib/pipeline.py", line 113, in receive
    return utils.decode(self.pipe.lindex(self.internal_queue, -1))
  File "/usr/lib/python3.4/site-packages/intelmq-1.0.0.dev4-py3.4.egg/intelmq/lib/utils.py", line 70, in decode
    return str(text.decode(encoding))
AttributeError: 'NoneType' object has no attribute 'decode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/intelmq-1.0.0.dev4-py3.4.egg/intelmq/lib/bot.py", line 102, in start
    self.process()
  File "/usr/lib/python3.4/site-packages/intelmq-1.0.0.dev4-py3.4.egg/intelmq/bots/outputs/file/output.py", line 16, in process
    event = self.receive_message()
  File "/usr/lib/python3.4/site-packages/intelmq-1.0.0.dev4-py3.4.egg/intelmq/lib/bot.py", line 258, in receive_message
    message = self.source_pipeline.receive()
  File "/usr/lib/python3.4/site-packages/intelmq-1.0.0.dev4-py3.4.egg/intelmq/lib/pipeline.py", line 117, in receive
    raise exceptions.PipelineError(exc)
intelmq.lib.exceptions.PipelineError: pipeline failed - AttributeError("'NoneType' object has no attribute 'decode'",)
```

**Comment by MAHDTech** [comment]
This is looking for like a redis configuration issue, can any confirm whats a quick test to ensure I have it working correctly?

**Comment by MAHDTech** [comment]
never mind, this one was a missing SELinux configuration.

issue cloed.

**Comment by MAHDTech** [comment]
I thought it was SELinux, but even on a fresh VM with SELinux set in permissive mode I can get the same error occasionally, and when it occurs the output file has very few entries, it just bombs out and doesn't pass as expected if issue.

`2016-06-03 06:11:48,215 - Output-File - DEBUG - Receiving Message.
2016-06-03 06:11:48,215 - Output-File - ERROR - Pipeline failed.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/intelmq-1.0.0.dev4-py3.4.egg/intelmq/lib/pipeline.py", line 113, in receive
    return utils.decode(self.pipe.lindex(self.internal_queue, -1))
  File "/usr/lib/python3.4/site-packages/intelmq-1.0.0.dev4-py3.4.egg/intelmq/lib/utils.py", line 70, in decode
    return str(text.decode(encoding))
AttributeError: 'NoneType' object has no attribute 'decode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/intelmq-1.0.0.dev4-py3.4.egg/intelmq/lib/bot.py", line 102, in start
    self.process()
  File "/usr/lib/python3.4/site-packages/intelmq-1.0.0.dev4-py3.4.egg/intelmq/bots/outputs/file/output.py", line 16, in process
    event = self.receive_message()
  File "/usr/lib/python3.4/site-packages/intelmq-1.0.0.dev4-py3.4.egg/intelmq/lib/bot.py", line 258, in receive_message
    message = self.source_pipeline.receive()
  File "/usr/lib/python3.4/site-packages/intelmq-1.0.0.dev4-py3.4.egg/intelmq/lib/pipeline.py", line 117, in receive
    raise exceptions.PipelineError(exc)
intelmq.lib.exceptions.PipelineError: pipeline failed - AttributeError("'NoneType' object has no attribute 'decode'",)
2016-06-03 06:11:48,216 - Output-File - INFO - Disconnecting from source pipeline.
2016-06-03 06:11:48,216 - Output-File - INFO - Disconnecting from destination pipeline.
2016-06-03 06:11:48,217 - Output-File - INFO - Bot will restart in 15 seconds.
`

**Comment by sebix** [comment]
> all log messages after this with the IOCs are not written to the actual file.

This phrase is not clear. Is the log missing some lines, or is the output file missing some lines?

> ```
  File "/usr/lib/python3.4/site-packages/intelmq-1.0.0.dev4-py3.4.egg/intelmq/lib/pipeline.py", line 113, in receive
    return utils.decode(self.pipe.lindex(self.internal_queue, -1))
  File "/usr/lib/python3.4/site-packages/intelmq-1.0.0.dev4-py3.4.egg/intelmq/lib/utils.py", line 70, in decode
    return str(text.decode(encoding))
AttributeError: 'NoneType' object has no attribute 'decode'```
`None`/`nil` is returned by redis, if the requested value (position -1, last entry) is not available. But the line above checks the length of the list. So this could be race condition, because the length check and the pop are two different commands.

I know removed the length check in my branch entirely and thus made the pop from the internal queue atomic and `None`-resistant.

**Comment by MAHDTech** [comment]
Apologies, I meant that the event.txt output file has no further IOCs, if watching redis (Monitor) I do see them going into redis, but nothing is ever outputted to the bot, even after manually restarting the file output bot.

I will update intelmq and try again.

What is the best way to determine the version I am running (intelmqctl --version just has 1.0.0.dev4 - is this latest?)

**Comment by MAHDTech** [comment]
OK, I have updated and retested and the same issue is occurring.

To give some further information, If I perform a wget on the malc0de file as a test and then

`cat IP_Blacklist.txt | wc -l `

The number is 109 (minus the 5 header lines) the total of IOC is 104.

When I download the same file using intelmq bot, the IOC total is 19, the last entry in the log (nearest to the type issue) is the final IOC written to the file

**Comment by MAHDTech** [comment]
`2016-06-08 02:08:42,568 - Output-File - DEBUG - Receiving Message.
2016-06-08 02:08:42,568 - Output-File - ERROR - Pipeline failed.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/intelmq-1.0.0.dev4-py3.4.egg/intelmq/lib/pipeline.py", line 112, in receive
    return utils.decode(self.pipe.lindex(self.internal_queue, -1))
  File "/usr/lib/python3.4/site-packages/intelmq-1.0.0.dev4-py3.4.egg/intelmq/lib/utils.py", line 70, in decode
    return str(text.decode(encoding))
AttributeError: 'NoneType' object has no attribute 'decode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/intelmq-1.0.0.dev4-py3.4.egg/intelmq/lib/bot.py", line 120, in start
    self.process()
  File "/usr/lib/python3.4/site-packages/intelmq-1.0.0.dev4-py3.4.egg/intelmq/bots/outputs/file/output.py", line 16, in process
    event = self.receive_message()
  File "/usr/lib/python3.4/site-packages/intelmq-1.0.0.dev4-py3.4.egg/intelmq/lib/bot.py", line 276, in receive_message
    message = self.__source_pipeline.receive()
  File "/usr/lib/python3.4/site-packages/intelmq-1.0.0.dev4-py3.4.egg/intelmq/lib/pipeline.py", line 118, in receive
    raise exceptions.PipelineError(exc)
intelmq.lib.exceptions.PipelineError: pipeline failed - AttributeError("'NoneType' object has no attribute 'decode'",)
`

After the error occurs, the bot loops,

`2016-06-08 02:08:42,604 - Output-File - INFO - Disconnecting from source pipeline.
2016-06-08 02:08:42,604 - Output-File - INFO - Disconnecting from destination pipeline.
2016-06-08 02:08:42,605 - Output-File - INFO - Bot will restart in 15 seconds.
2016-06-08 02:08:57,585 - Output-File - INFO - Bot woke up
2016-06-08 02:08:57,586 - Output-File - INFO - Trying to start processing again.
2016-06-08 02:08:57,586 - Output-File - INFO - Loading source pipeline.
2016-06-08 02:08:57,586 - Output-File - INFO - Loading source queue.
2016-06-08 02:08:57,587 - Output-File - INFO - Source queue loaded Output-File-queue.
2016-06-08 02:08:57,587 - Output-File - INFO - Connected to source queue.
2016-06-08 02:08:57,587 - Output-File - INFO - Loading destination pipeline.
2016-06-08 02:08:57,587 - Output-File - INFO - Loading destination queues.
2016-06-08 02:08:57,587 - Output-File - INFO - Destination queues loaded None.
2016-06-08 02:08:57,588 - Output-File - INFO - Connected to destination queues.
2016-06-08 02:08:57,588 - Output-File - INFO - Pipeline ready.
2016-06-08 02:08:57,588 - Output-File - DEBUG - Receiving Message.
2016-06-08 02:08:57,620 - Output-File - INFO - Bot woke up
2016-06-08 02:08:57,621 - Output-File - INFO - Trying to start processing again.
2016-06-08 02:08:57,621 - Output-File - INFO - Loading source pipeline.
2016-06-08 02:08:57,621 - Output-File - INFO - Loading source queue.
2016-06-08 02:08:57,621 - Output-File - INFO - Source queue loaded Output-File-queue.
2016-06-08 02:08:57,622 - Output-File - INFO - Connected to source queue.
2016-06-08 02:08:57,622 - Output-File - INFO - Loading destination pipeline.
2016-06-08 02:08:57,622 - Output-File - INFO - Loading destination queues.
2016-06-08 02:08:57,622 - Output-File - INFO - Destination queues loaded None.
2016-06-08 02:08:57,622 - Output-File - INFO - Connected to destination queues.
2016-06-08 02:08:57,623 - Output-File - INFO - Pipeline ready.
2016-06-08 02:08:57,623 - Output-File - DEBUG - Receiving Message.
`

**Comment by sebix** [comment]
> Apologies, I meant that the events.txt output file has no further IOCs after the crash, if watching redis (Monitor) I do see them going into redis, but nothing is ever outputted to the file, even after manually restarting the file output bot.

Ok, this *is* a problem.
> What is the best way to determine the version I am running (intelmqctl --version just has 1.0.0.dev4 - is this latest?)

Once I merged the fix, I will increase the version number. As you are working with master, which is the current development branch, the version number is not increased with each commit.
> OK, I have updated and retested and the same issue is occurring.

I haven't changed anything in upstream master, so this is totally expected.
