### ISSUE TITLE
Error on Shadow Server Microsoft Sinkhole parser

### ISSUE THREAD

**Issue by pedromreis** [certtools/intelmq#545]
```python
Bot has found a problem.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/intelmq-1.0.0.dev4-py3.4.egg/intelmq/lib/bot.py", line 120, in start
    self.process()
  File "/usr/lib/python3.4/site-packages/intelmq-1.0.0.dev4-py3.4.egg/intelmq/bots/parsers/shadowserver/microsoft_sinkhole_parser.py", line 44, in process
    for row in csv.DictReader(io.StringIO(raw_report), dictreader=True):
  File "/usr/lib64/python3.4/csv.py", line 85, in __init__
    self.reader = reader(f, dialect, *args, **kwds)
TypeError: 'dictreader' is an invalid keyword argument for this function
```

**Comment by sebix** [comment]
Will be solved by new parsers developed by @dmth here: https://github.com/Intevation/intelmq/tree/shadowserver-feeds/intelmq/bots/parsers/shadowserver

**Comment by dmth** [comment]
As sebix said, new parsers will solve this problem.
Please see my comment in https://github.com/certtools/intelmq/issues/544 and test the parsers

**Comment by aaronkaplan** [comment]
needs more testing.
