### ISSUE TITLE
sleep fails for pipeline errors in collectors

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#560]
From n6stomp-collector's log file:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/intelmq/lib/bot.py", line 127, in start
AttributeError: 'NoneType' object has no attribute 'sleep'
2016-06-28 11:42:57,095 - n6stomp-collector - INFO - Last Correct Message(event): None.
2016-06-28 11:42:57,095 - n6stomp-collector - INFO - Current Message(event): None.
2016-06-28 11:42:57,096 - n6stomp-collector - INFO - Bot will restart in 15 seconds.
2016-06-28 11:43:12,111 - n6stomp-collector - INFO - Bot woke up
2016-06-28 11:43:12,111 - n6stomp-collector - INFO - Trying to start processing again.
2016-06-28 11:43:12,112 - n6stomp-collector - ERROR - Bot has found a problem.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/intelmq/lib/bot.py", line 127, in start
AttributeError: 'NoneType' object has no attribute 'sleep'
```

**Comment by dmth** [comment]
In #562 you wrote:

> It's a bug which was introduced by the parser architecture changes.

I don't get why the parser would affect the collector.

Do you know when these errors were introduced? I can't reproduce them on our side (build around 01.07.2016)

**Comment by aaronkaplan** [comment]
> On 12 Jul 2016, at 09:34, Dustin Demuth <notifications@github.com> wrote:
> 
> In #562 you wrote:
> 
> It's a bug which was introduced by the parser architecture changes.
> 
> I don't get why the parser would affect the collector.
> 
> Do you know when these errors were introduced? I can't reproduce them on our side (build around 01.07.2016)
> 

I'd have to bisect.

Fact is the bot class says source_pipeline.sleep()
But source_pipeline is None for collectors .

It's connected to the base class.

**Comment by dmth** [comment]
> Fact is the bot class says source_pipeline.sleep()
> But source_pipeline is None for collectors .

This would affect all collectors, not just N6, right?

**Comment by aaronkaplan** [comment]
> On 12 Jul 2016, at 09:57, Dustin Demuth <notifications@github.com> wrote:
> 
> Fact is the bot class says source_pipeline.sleep()
> But source_pipeline is None for collectors .
> 
> This would affect all collectors, not just N6, right?
> 
Indeed.
I simply noticed with n6 yesterday.

**Comment by dmth** [comment]
I suggest to change the title of this issue accordingly..

**Comment by sebix** [comment]
The issue exists since b53809b8cc19e8bb4e162e0adc18bd5e316d127e (June 2015). The bug is only triggered, when a pipeline error happens and only for collectors.
