### ISSUE TITLE
cymru lookup bug

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#597]
```
Bot has found a problem.
Traceback (most recent call last):
  File "/home/aaron/intelmq/intelmq/lib/bot.py", line 125, in start
    self.process()
  File "/home/aaron/intelmq/intelmq/bots/experts/cymru_whois/expert.py", line 54, in process
    result = Cymru.query(ip)
  File "/home/aaron/intelmq/intelmq/bots/experts/cymru_whois/lib.py", line 40, in query
    if "asn" in result:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by aaronkaplan** [comment]
reason:

```
 --------------------------------------------------
{'bot_id': 'cymru-whois-expert',
 'message': {'__type': 'Event',
             'classification.identifier': 'feodeo',
             'classification.taxonomy': 'Malicious Code',
             'classification.type': 'c&c',
             'feed.accuracy': 100.0,
             'feed.code': 'abuse.ch',
             'feed.name': 'Abuse.ch',
             'feed.url': 'https://feodotracker.abuse.ch/blocklist/?download=ipblocklist',
             'malware.name': 'cridex',
             'raw': 'OXXXXXXX==',
             'source.geolocation.cc': 'LV',
             'source.geolocation.latitude': 57.0,
             'source.geolocation.longitude': 25.0,
             'source.ip': '1.2.3.4',
             'time.observation': '2016-07-21T07:41:45+00:00',
             'time.source': '2016-07-21T07:42:02+00:00'},
 'source_queue': 'cymru-whois-expert-queue',
 'traceback': ['Traceback (most recent call last):',
               '  File "/home/aaron/intelmq/intelmq/lib/bot.py", line 125, '
               'in start',
               '    self.process()',
               '  File '
               '"/home/aaron/intelmq/intelmq/bots/experts/cymru_whois/expert.py", '
               'line 54, in process',
               '    result = Cymru.query(ip)',
               '  File '
               '"/home/aaron/intelmq/intelmq/bots/experts/cymru_whois/lib.py", '
               'line 40, in query',
               '    if "asn" in result:',
               "TypeError: argument of type 'NoneType' is not iterable"]}

```
