### ISSUE TITLE
shadowserver: elasticsearch feed

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#598]
Error message:

```
Failed to parse line.
Traceback (most recent call last):
  File "/home/aaron/intelmq/intelmq/lib/bot.py", line 458, in process
    events = list(filter(bool, self.parse_line(line, report)))
  File "/home/aaron/intelmq/intelmq/bots/parsers/shadowserver/parser.py", line 179, in parse_line
    event.add(key, value)
  File "/home/aaron/intelmq/intelmq/lib/message.py", line 126, in add
    raise exceptions.InvalidValue(key, value, reason=valid_value[1])
intelmq.lib.exceptions.InvalidValue: invalid value 'elasticsearch' () for key 'protocol.application' regex did not match.

```

**Comment by aaronkaplan** [comment]
my mistake. The /opt/intelmq/etc/harmonization.conf was simply old ...
