### ISSUE TITLE
core: nicer error message when out of disk space / RAM

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#612]
I'd like to see a more meaningful error message when we are out of disk space or RAM when operating with 
- redis
- log files

```
2016-07-25 19:04:54,965 - rt-openportmapper - ERROR - Pipeline failed.
Traceback (most recent call last):
  File "/home/aaron/intelmq/intelmq/lib/pipeline.py", line 105, in send
    self.pipe.lpush(destination_queue, message)
  File "/usr/local/lib/python3.4/dist-packages/redis/client.py", line 1227, in lpush
    return self.execute_command('LPUSH', name, *values)
  File "/usr/local/lib/python3.4/dist-packages/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python3.4/dist-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 582, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aaron/intelmq/intelmq/lib/bot.py", line 125, in start
    self.process()
  File "/home/aaron/intelmq/intelmq/bots/collectors/rt/collector_rt.py", line 86, in process
    self.send_message(report)
  File "/home/aaron/intelmq/intelmq/lib/bot.py", line 284, in send_message
    self.__destination_pipeline.send(raw_message)
  File "/home/aaron/intelmq/intelmq/lib/pipeline.py", line 107, in send
    raise exceptions.PipelineError(exc)
intelmq.lib.exceptions.PipelineError: pipeline failed - ResponseError('MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.',)

```

**Comment by sebix** [comment]
Bots could stop automatically if (`MemoryError`, `IOError: [Errno 28] No space left on device`) happen, independent of their error-configuration.
For pipeline errors we could search for the string `MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk` and directly stop in this case too.

+ Writing an according error log message explaining things.

**Comment by sebix** [comment]
Other relevant errors:

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 439, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 494, in _connect
    raise err
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 482, in _connect
    sock.connect(socket_address)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aaron/intelmq/intelmq/lib/pipeline.py", line 106, in send
    self.pipe.lpush(destination_queue, message)
  File "/usr/local/lib/python3.4/dist-packages/redis/client.py", line 1227, in lpush
    return self.execute_command('LPUSH', name, *values)

  File "/usr/local/lib/python3.4/dist-packages/redis/client.py", line 578, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 99 connecting to 127.0.0.1:6379. Cannot assign requested address.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aaron/intelmq/intelmq/bin/intelmqdump.py", line 246, in main
    pipe.send(msg)
  File "/home/aaron/intelmq/intelmq/lib/pipeline.py", line 108, in send
    raise exceptions.PipelineError(exc)
intelmq.lib.exceptions.PipelineError: pipeline failed - ConnectionError('Error 99 connecting to 127.0.0.1:6379. Cannot assign requested address.',)

```

**Comment by sebix** [comment]
Proposal:

* The pipeline raises a `MemoryError` when `redis.exceptions.ResponseError` or a `redis.exceptions.ConnectionError` happen
* The bots exit (more or less) immediately if a `MemoryError` or `IOError: [Errno 28] No space left on device` happens and log a proper and understandable error message (additional to the detailed message from e.g. redis)
