### ISSUE TITLE
postgresql output: sometimes some field is too long

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#615]
```
2016-07-25 21:01:11,058 - postgresql-output - WARNING - Message dumped.
2016-07-25 21:09:07,462 - postgresql-output - ERROR - Bot has found a problem.
Traceback (most recent call last):
  File "/home/aaron/intelmq/intelmq/lib/bot.py", line 125, in start
    self.process()
  File "/home/aaron/intelmq/intelmq/bots/outputs/postgresql/output.py", line 64, in process
    self.cur.execute(query, values)
psycopg2.DataError: value too long for type character varying(2000)
```

Please inspect via .dump file.

EDIT by @sebix: Complete traceback

**Comment by aaronkaplan** [comment]
fixed. it was actually a mistake in our eventsdb (postgres) - not a bug in the intelmq code
