### ISSUE TITLE
Regular pipeline timeouts produce errors

### ISSUE THREAD

**Issue by gsiv** [certtools/intelmq#643]
I've noticed that most bots regularly produce TimeoutErrors like the following:

```
2016-08-08 17:03:05,683 - shadowserver-parser-ssl-poodle - DEBUG - Sending message.
2016-08-08 17:03:05,844 - shadowserver-parser-ssl-poodle - DEBUG - Waiting for incoming message.
2016-08-09 06:56:25,582 - shadowserver-parser-ssl-poodle - ERROR - Pipeline failed.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/redis/connection.py", line 120, in _read_from_socket
    data = self._sock.recv(socket_read_size)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/intelmq/lib/pipeline.py", line 114, in receive
    self.internal_queue, 0)
  File "/usr/lib/python3/dist-packages/redis/client.py", line 1179, in brpoplpush
    return self.execute_command('BRPOPLPUSH', src, dst, timeout)
  File "/usr/lib/python3/dist-packages/redis/client.py", line 565, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/lib/python3/dist-packages/redis/client.py", line 577, in parse_response
    response = connection.read_response()
  File "/usr/lib/python3/dist-packages/redis/connection.py", line 569, in read_response
    response = self._parser.read_response()
  File "/usr/lib/python3/dist-packages/redis/connection.py", line 224, in read_response
    response = self._buffer.readline()
  File "/usr/lib/python3/dist-packages/redis/connection.py", line 162, in readline
    self._read_from_socket()
  File "/usr/lib/python3/dist-packages/redis/connection.py", line 133, in _read_from_socket
    raise TimeoutError("Timeout reading from socket")
redis.exceptions.TimeoutError: Timeout reading from socket

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/intelmq/lib/bot.py", line 121, in start
    self.process()
  File "/usr/lib/python3/dist-packages/intelmq/lib/bot.py", line 449, in process
    report = self.receive_message()
  File "/usr/lib/python3/dist-packages/intelmq/lib/bot.py", line 281, in receive_message
    message = self.__source_pipeline.receive()
  File "/usr/lib/python3/dist-packages/intelmq/lib/pipeline.py", line 119, in receive
    raise exceptions.PipelineError(exc)
intelmq.lib.exceptions.PipelineError: pipeline failed - TimeoutError('Timeout reading from socket',)
2016-08-09 06:56:25,584 - shadowserver-parser-ssl-poodle - DEBUG - Disconnecting from source pipeline.
2016-08-09 06:56:25,585 - shadowserver-parser-ssl-poodle - DEBUG - Disconnecting from destination pipeline.
2016-08-09 06:56:25,585 - shadowserver-parser-ssl-poodle - INFO - Bot will restart in 15 seconds.
2016-08-09 06:56:40,600 - shadowserver-parser-ssl-poodle - INFO - Bot woke up
2016-08-09 06:56:40,601 - shadowserver-parser-ssl-poodle - INFO - Trying to start processing again.
2016-08-09 06:56:40,601 - shadowserver-parser-ssl-poodle - DEBUG - Loading source pipeline.
2016-08-09 06:56:40,601 - shadowserver-parser-ssl-poodle - DEBUG - Loading source queue.
2016-08-09 06:56:40,602 - shadowserver-parser-ssl-poodle - DEBUG - Source queue loaded shadowserver-parser-ssl-poodle-queue.
2016-08-09 06:56:40,602 - shadowserver-parser-ssl-poodle - DEBUG - Connected to source queue.
2016-08-09 06:56:40,602 - shadowserver-parser-ssl-poodle - DEBUG - Loading destination pipeline.
2016-08-09 06:56:40,603 - shadowserver-parser-ssl-poodle - DEBUG - Loading destination queues.
2016-08-09 06:56:40,603 - shadowserver-parser-ssl-poodle - DEBUG - Destination queues loaded ['deduplicator-expert-queue'].
2016-08-09 06:56:40,603 - shadowserver-parser-ssl-poodle - DEBUG - Connected to destination queues.
2016-08-09 06:56:40,603 - shadowserver-parser-ssl-poodle - INFO - Pipeline ready.
2016-08-09 06:56:40,603 - shadowserver-parser-ssl-poodle - DEBUG - Waiting for incoming message.
```

@bernhard-herzog already found that the disconnect always happens after about
50,000s which led him to find the following in `intelmq/lib/pipeline.py`:

```
self.socket_timeout = getattr(self.parameters,
                              "{}_pipeline_socket_timeout".format(
                                  queues_type),
                              50000)
```

**Comment by sebix** [comment]
The [docs](https://redis-py.readthedocs.io/en/latest/index.html?highlight=timeout) say:
> If timeout is 0, then block indefinitely.

for pop-actions, but we already do this in [receive](https://github.com/certtools/intelmq/blob/master/intelmq/lib/pipeline.py#L113). Not sure if this also applies to the Redis-object as a whole. So I'd try to set the timeout 0 and we additionally catch TimeoutErrors for the brpoplpush().

**Comment by SYNchroACK** [comment]
@gsiv any update on this issue? Im curious about it

**Comment by bernhardreiter** [comment]
What was the usecase for this timeout anyway? @sebix ?

**Comment by sebix** [comment]
This is the commit which introduced the timeout: https://github.com/certtools/intelmq/commit/b53809b8cc19e8bb4e162e0adc18bd5e316d127e#diff-469e0830e543dd0b6c9a7ed0a1402facR47
