### ISSUE TITLE
postgresql output: deal with duplicate keys

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#684]
The postgresql bot does not ignore duplicates keys. It stack traces (of course).

```
2016-09-17 11:52:31,429 - postgresql-output - ERROR - Bot has found a problem.
Traceback (most recent call last):
  File "/home/aaron/intelmq/intelmq/lib/bot.py", line 154, in start
    self.process()
  File "/home/aaron/intelmq/intelmq/bots/outputs/postgresql/output.py", line 64, in process
    self.cur.execute(query, values)
psycopg2.IntegrityError: duplicate key value violates unique constraint "events_pkey"
DETAIL:  Key (id)=(1166646) already exists.


```

Proposed solution: create a WARNING, potentially dump the message and continue.
What do you think?

The other real question actually is, why are there duplicate keys? It's supposed to be a sequence counter in the eventdb.

Weird. 

```SQL
eventdb=> select * from events where id=1166646;
eventdb=> delete from events where id=1166646;
DELETE 1
eventdb=> delete from events where id=1166647;
DELETE 1
eventdb=> delete from events where id=1166648;
DELETE 1
eventdb=> delete from events where id=1166649;
DELETE 1
eventdb=> delete from events where id=1166650;
DELETE 1
eventdb=> select count(*) from events where id> 1166650;
  count
---------
 1611845
(1 row)
```

Why so many?

**Comment by aaronkaplan** [comment]
Fixed it by hard-setting the sequence id to a new , higher value. Not pretty. I wonder why this happened. It's probably something that we should address in the documentation when migrating DBs or upgrading postgresql versions.

```SQL
eventdb=> select setval('events_id_seq', 18603540);
  setval
----------
 18603540
(1 row)
```
