### ISSUE TITLE
shadowserver parser fails to parse opensnmp data

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#699]
Stacktrace when running opensnmp-parser:

```
2016-09-19 14:45:05,455 - opensnmp-parser - ERROR - Bot has found a problem.
Traceback (most recent call last):
  File "/home/aaron/intelmq/intelmq/lib/bot.py", line 158, in start
    self.__sleep()
  File "/home/aaron/intelmq/intelmq/lib/bot.py", line 241, in __sleep
    while remaining > 0:
TypeError: unorderable types: str() > int()

```

**Comment by aaronkaplan** [comment]
explanation: we had a string in the config (rate_limit parameter) instead of an int.

**Comment by sebix** [comment]
probably a duplicate of certtools/intelmq-manager#81
