### ISSUE TITLE
unittests failing for setup

### ISSUE THREAD

**Issue by sashank** [certtools/intelmq#713]
i have just downloaded intelmq (am running ubuntu 14.04.4 LTS) , i have gone through all the INSTALL steps religiously.  Should i worry about the below ? will it impact my production installation in some way ? am just getting started with intelmq , any help is appreciated. even other unittests failing , i shall raise separate issue 

```
ubuntu05:/home/intelmq/intelmq$ python3 setup.py test
running test
running egg_info
writing intelmq.egg-info/PKG-INFO
writing dependency_links to intelmq.egg-info/dependency_links.txt
writing top-level names to intelmq.egg-info/top_level.txt
writing requirements to intelmq.egg-info/requires.txt
writing entry points to intelmq.egg-info/entry_points.txt
reading manifest file 'intelmq.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching '.gitignore'
warning: no previously-included files found matching '.pep8'
warning: no previously-included files found matching '.travis.yml'
writing manifest file 'intelmq.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 91, in <module>
    'intelmq/bots/experts/asn_lookup/update-asn-data',
  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
self.run_command(cmd)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 135, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 116, in with_project_on_sys_path
    func()
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 160, in run_tests
    testLoader = cks
  File "/usr/lib/python3.4/unittest/main.py", line 92, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.4/unittest/main.py", line 139, in parseArgs
    self.createTests()
  File "/usr/lib/python3.4/unittest/main.py", line 146, in createTests
    self.module)
  File "/usr/lib/python3.4/unittest/loader.py", line 146, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.4/unittest/loader.py", line 146, in <listcomp>
suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.4/unittest/loader.py", line 117, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 36, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python3.4/unittest/loader.py", line 117, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 36, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python3.4/unittest/loader.py", line 117, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 36, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python3.4/unittest/loader.py", line 117, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 36, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
 File "/usr/lib/python3.4/unittest/loader.py", line 114, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'test_collector'
```

**Comment by aaronkaplan** [comment]
do we also mention the dependencies in the install steps?

**Comment by sebix** [comment]
No, they are optional. They are documented in the bot's docs only.

**Comment by aaronkaplan** [comment]
Yes, but I was hinting at the usability issue we encountered . Thanks @sashank for reporting this!
What I am saying: if some user did not find a clear explanation where he needs to look, then it's IMHO a usability *bug* and we should look into this.
I think we should mention pretty much in the beginning of the UserGuide that there are individual settings necessary for individual bots (and where to find the documentation on that).

My 2 cents,
a.
