### ISSUE TITLE
Error in bot tcpoutput

### ISSUE THREAD

**Issue by rmsferreira** [certtools/intelmq#755]
When y try to output from Intelmq to remote syslog using tcpoutput bot, a error ocure:

```
2016-10-20 18:00:57,605 - tcp-output - INFO - Bot is starting.
2016-10-20 18:00:57,605 - tcp-output - ERROR - Bot initialization failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/intelmq/lib/bot.py", line 78, in __init__
    self.init()
  File "/usr/local/lib/python3.4/dist-packages/intelmq/bots/outputs/tcp/output.py", line 13, in init
    self.separator = utils.encode(self.parameters.separator)
AttributeError: 'Parameters' object has no attribute 'separator'
```

EDIT by @sebix: Syntax

**Comment by sebix** [comment]
The parameter got lost between 00978629cf0a847f3b2fbd3eddc9a235dae1cd37 and 64b22d962136ac37e148e6c7a173559bfac8798e but can't find it in the diff.

Just add this parameter to the bot in the runtime.conf: `"separator": "\n"`
