### ISSUE TITLE
Replace IP in Cymru whois test

### ISSUE THREAD

**Issue by sykaeh** [certtools/intelmq#768]
I would suggest replacing the IP in the Cymru Whois Expert Bot Test. Cymru seems to be returning different names for the AS even during (almost) simultaneous calls (once with one `,` and once with three `,`). It has happened a couple of times that the continuous integration tests for one Python version have failed while they passed on the other Python versions.

```
FAIL: test_unicode_as_name (intelmq.tests.bots.experts.cymru_whois.test_expert.TestCymruExpertBot)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/certtools/intelmq/intelmq/tests/bots/experts/cymru_whois/test_expert.py", line 94, in test_unicode_as_name
    self.assertMessageEqual(0, UNICODE_OUTPUT)
  File "/home/travis/build/certtools/intelmq/intelmq/lib/test.py", line 385, in assertMessageEqual
    self.assertDictEqual(expected, event_dict)
nose.proxy.AssertionError: {'destination.as_name': 'Local Datacenter Soluções em Comunicação Ltda.,,, BR',  [truncated]... != {'destination.as_name': 'Local Datacenter Soluções em Comunicação Ltda., BR', 'd [truncated]...
  {'__type': 'Event',
   'destination.allocated': '2007-08-10T00:00:00+00:00',
-  'destination.as_name': 'Local Datacenter Soluções em Comunicação Ltda.,,, BR',
?                                                                         --
+  'destination.as_name': 'Local Datacenter Soluções em Comunicação Ltda., BR',
   'destination.asn': 28333,
   'destination.geolocation.cc': 'BR',
   'destination.ip': '189.50.192.1',
   'destination.network': '189.50.192.0/23',
   'destination.registry': 'LACNIC'}
```

**Comment by sebix** [comment]
Changed the AS, let's see if this one's more stable.
