### ISSUE TITLE
http*_proxy parameters missing in BOTS file for generic mail and url collectors

### ISSUE THREAD

**Issue by dmth** [certtools/intelmq#820]
Since `set_request_parameters` is used by the collectors, the bots won't start if they are generated by the manager, as the necessary parameters http_proxy and https_proxy are missing.

```
diff --git a/intelmq/bots/BOTS b/intelmq/bots/BOTS
index 45f0428..5060a49 100644
--- a/intelmq/bots/BOTS
+++ b/intelmq/bots/BOTS
@@ -36,8 +36,10 @@
                 "feed": "",
                 "provider": "",
                 "folder": "INBOX",
-                "http_password": "<password>",
                 "http_username": "<user>",
+                "http_password": "<password>",
+                "http_proxy": "",
+                "https_proxy": "",
                 "mail_host": "<host>",
                 "mail_password": "<password>",
                 "mail_ssl": true,
@@ -55,8 +57,10 @@
                 "feed": "",
                 "provider": "",
                 "http_url": "<insert url of feed>",
-                "http_username": null,
-                "http_password": null,
+                "http_username": "<user>",
+                "http_password": "<password>",
+                "http_proxy": "",
+                "https_proxy": "",
                 "ssl_client_certificate": null,
                 "rate_limit": 3600
             }
```

**Comment by sebix** [comment]
Yes, thanks.

But they could also be in defaults.conf and the default values for these keys should definitely be `None`, not some string.

**Comment by sebix** [comment]
Both `http_proxy` and `https_proxy` are currently both defined in `defaults.conf`, so I can't replicate reproduce.

**Comment by dmth** [comment]
those parameters are also defined in defaults.conf here, but they are not read at my end... need to check on that.

**Comment by dmth** [comment]
Ok, the reason is simple.... my defaults.conf contains `http_proxy` and the deprecated `http_ssl_proxy` nevertheless, the code does not handle the deprecation. 

```
2016-12-13 17:21:37,342 - generic-url-fetcher-collector - WARNING - Parameter 'http_ssl_proxy' is deprecated and will be removed in version 1.0!
2016-12-13 17:21:37,343 - generic-url-fetcher-collector - ERROR - Bot initialization failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/intelmq/lib/bot.py", line 85, in __init__
    self.init()
  File "/usr/local/lib/python3.4/dist-packages/intelmq/bots/collectors/http/collector_http.py", line 26, in init
    self.set_request_parameters()
  File "/usr/local/lib/python3.4/dist-packages/intelmq/lib/bot.py", line 605, in set_request_parameters
    if not self.parameters.https_proxy:
AttributeError: 'Parameters' object has no attribute 'https_proxy'

```

```
/opt/intelmq/etc# cat defaults.conf 
{
    "accuracy": 100,
    "broker": "redis",
    "destination_pipeline_db": 2,
    "destination_pipeline_host": "127.0.0.1",
    "destination_pipeline_port": 6379,
    "error_dump_message": true,
    "error_log_exception": true,
    "error_log_message": true,
    "error_max_retries": 3,
    "error_procedure": "pass",
    "error_retry_delay": 15,
    "http_proxy": null,
    "http_ssl_proxy": null,
    "http_user_agent": "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36",
    "http_verify_cert": true,
    "load_balance": false,
    "logging_handler": "file",
    "logging_level": "DEBUG",
    "logging_path": "/opt/intelmq/var/log/",
    "logging_syslog": "/dev/log",
    "rate_limit": 0,
    "source_pipeline_db": 2,
    "source_pipeline_host": "127.0.0.1",
    "source_pipeline_port": 6379
}
```

**Comment by dmth** [comment]
```
diff --git a/intelmq/lib/bot.py b/intelmq/lib/bot.py
index b2d2e8a..9586927 100644
--- a/intelmq/lib/bot.py
+++ b/intelmq/lib/bot.py
@@ -602,7 +602,7 @@ def set_request_parameters(self):
         if hasattr(self.parameters, 'http_ssl_proxy'):
             self.logger.warning("Parameter 'http_ssl_proxy' is deprecated and will be removed in "
                                 "version 1.0!")
-            if not self.parameters.https_proxy:
+            if not hasattr(self.parameters, 'https_proxy'):
                 self.parameters.https_proxy = self.parameters.http_ssl_proxy
 
         self.http_header = getattr(self.parameters, 'http_header', {})
```

**Comment by dmth** [comment]
https://github.com/Intevation/intelmq/commit/4a4b986f632ed4fe35d42b507385d771bc4aa24a fixes the problem
