### ISSUE TITLE
Mongo Output Bot

### ISSUE THREAD

**Issue by SYNchroACK** [certtools/intelmq#943]
**Error**
```
# tail -f /opt/intelmq/var/log/mongodb-output.log 
2017-04-08 03:30:41,021 - mongodb-output - ERROR - Bot initialization failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/intelmq/lib/bot.py", line 78, in __init__
    self.init()
  File "/usr/local/lib/python3.5/dist-packages/intelmq/bots/outputs/mongodb/output.py", line 31, in init
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/intelmq/bots/outputs/mongodb/output.py", line 55, in connect
    if self.parameters.db_user and self.parameters.db_pass:
AttributeError: 'Parameters' object has no attribute 'db_user'
2017-04-08 03:30:41,022 - mongodb-output - INFO - Bot stopped.
```

**runtime.conf**
```
    "mongodb-output": {
        "parameters": {
            "collection": "mycollection",
            "database": "mydatabase",
            "hierarchical_output": true,
            "host": "127.0.0.1",
            "port": 27017
        },
        "group": "Output",
        "name": "MongoDB",
        "module": "intelmq.bots.outputs.mongodb.output",
        "description": "MongoDB is the bot responsible to send events to a MongoDB database."
    }
```

**Possible solution**
```
if getattr(self.parameters, 'db_user', False) and getattr(self.parameters, 'db_pass', False) :
    self.logger.debug('Trying to authenticate to database {}.'.format(self.parameters.database))
    try:
        db.authenticate(name=self.parameters.db_user,
                                  password=self.parameters.db_pass)
    except pymongo.errors.OperationFailure:
        raise ValueError('Authentication to database {} failed'.format(self.parameters.database))
```

**Comment by wagner-certat** [comment]
Thanks for testing this. Pushed the very small fix (using hasattr).
