### ISSUE TITLE
XMPP Bots not properly stopping

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#970]
These bots are using threads and have to be killed multiple times.

See for example this log:

```
2017-05-08 05:38:52,150 - xmpp-bsi-collector - INFO - Idling for 3600.0s now.
2017-05-08 06:25:17,283 - xmpp-bsi-collector - INFO - Received SIGHUP, initializing again later.
2017-05-08 06:25:17,283 - xmpp-bsi-collector - INFO - Handling SIGHUP, initializing again now.
2017-05-08 06:25:17,284 - xmpp-bsi-collector - INFO - XMPPCollectorBot initialized with id xmpp-bsi-collector and version 3.4.2 (default, Oct  8 2014, 10:45:20) as process 7050.
2017-05-08 06:25:17,284 - xmpp-bsi-collector - INFO - Bot is starting.
2017-05-08 06:25:17,286 - xmpp-bsi-collector - INFO - Initiated.
2017-05-08 06:25:17,294 - xmpp-bsi-collector - ERROR - Could not connect to XMPP-Server.
2017-05-08 06:25:17,294 - xmpp-bsi-collector - ERROR - Could not disconnect from XMPP Server.
2017-05-08 06:25:17,294 - xmpp-bsi-collector - INFO - Bot stopped.
2017-05-10 08:03:32,964 - xmpp-bsi-collector - ERROR - Error during message handling.
Traceback (most recent call last):
  File "/home/aaron/intelmq/intelmq/bots/collectors/xmpp/collector.py", line 198, in log_message
    self.send_message(report)
  File "/home/aaron/intelmq/intelmq/lib/bot.py", line 677, in send_message
    super(CollectorBot, self).send_message(*messages)
  File "/home/aaron/intelmq/intelmq/lib/bot.py", line 343, in send_message
    self.__destination_pipeline.send(raw_message)
AttributeError: 'NoneType' object has no attribute 'send'
```

As you can see, the bot has been stopped, but the XMPP listener is still running.

**Comment by wagner-certat** [comment]
In interactive mode I get a different error for the second KeyboardInterrupt:

```
xmpp-collector-collector: Idling for 3600.0s now.
^Cxmpp-collector-collector: Received KeyboardInterrupt.
xmpp-collector-collector: Could not disconnect from XMPP Server.
xmpp-collector-collector: Disconnected from source pipeline.
xmpp-collector-collector: Disconnected from destination pipeline.
xmpp-collector-collector: Bot stopped.
Bot exited with code 0.
^CException ignored in: <module 'threading' from '/usr/lib64/python3.4/threading.py'>
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 1285, in _shutdown
    t.join()
  File "/usr/lib64/python3.4/threading.py", line 1051, in join
    self._wait_for_tstate_lock()
  File "/usr/lib64/python3.4/threading.py", line 1067, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

**Comment by wagner-certat** [comment]
See also fritzy/SleekXMPP#153

**Comment by wagner-certat** [comment]
Sending SIGINT again in shutdown() to the process itself does not change anything. With SIGTERM and SIGKILL we abort the graceful shutdown :/

The only idea I currently have is instead of calling `sys.exit()` we could send SIGTERM to the bot if there are more then 1 threads (the main thread).

**Comment by dmth** [comment]
I'm a little confused here. The Output-bot contains a `shutdown` method which is expected to call `xmpp.disconnect()` ([code](https://github.com/certtools/intelmq/blob/master/intelmq/bots/outputs/xmpp/output.py#L166)).
So if this method is called, the XMPP-Connection should cease to exist. As we are calling `disconnect`without parameters, the connection should not be blocked.

The log you've quoted above states:
`Could not disconnect from XMPP Server.` So `disconnect` did not evaluate to `true`.
The error might lie in the usage of `disconnect()` as it seems to have a sort of asynchronous behaviour: the method [XMLStream (impl. of disconnect)](https://github.com/fritzy/SleekXMPP/blob/develop/sleekxmpp/xmlstream/xmlstream.py#L664) makes use of the [StateMachine (link to code) ](https://github.com/fritzy/SleekXMPP/blob/develop/sleekxmpp/thirdparty/statemachine.py), which might return false in case of timeouts. I'd did not look deep enough into it to understand it all.

The [docs of sleekxmpp](https://github.com/fritzy/SleekXMPP/blob/develop/docs/getting_started/sendlogout.rst) suggest to contact them when experiencing troubles.

**Comment by aaronkaplan** [comment]
I think it's best to (unfortunately) have an exception for this bot... At least send out a warning on the console/intelmqctl that this bot is still running and that a sysadmin needs to kill it manually.

and/or do the following in the ctl:
  if the module == xmpp:
     send the SIGTERM afterwards if it's still running.
